### ISSUE TITLE
configurable ports

### ISSUE THREAD

**Issue by x-t** [themoonisacheese/2bored2wait#1]
as i already have a web server on port 80, it'd be nice to have that easily changed instead of having to read the source code and find lines
https://github.com/themoonisacheese/2bored2wait/blob/master/main.js#L12
and
https://github.com/themoonisacheese/2bored2wait/blob/master/main.js#L35

**Comment by themoonisacheese** [comment]
A config file is in the works.

**Comment by themoonisacheese** [comment]
fixed since https://github.com/themoonisacheese/2bored2wait/commit/2e64a4ebe26fc5433bfcc16802736008718f5fa9
