### ISSUE TITLE
Stuck On "extract:prismarine-tokens-fixed: verb lock using C:\Users\Branta\AppData\Roaming\npm-cache\_lock" When Installing

### ISSUE THREAD

**Issue by AfkBranta** [themoonisacheese/2bored2wait#106]
title explains it all, I tried reinstalling and it still gets stuck on it, and I literally left it on for an entire day and it was still on it.

**Comment by YeetyDankEngine** [comment]
Is this with npm?

**Comment by AfkBranta** [comment]
and yes its with npm

**Comment by YeetyDankEngine** [comment]
Try reinstall nodejs
