### ISSUE TITLE
rest api: undefined username

### ISSUE THREAD

**Issue by MrGeorgen** [themoonisacheese/2bored2wait#108]
It probably intended to show the minecraft username, but the variable is never set to the username. 
https://github.com/themoonisacheese/2bored2wait/blob/7cf49be791a7ac47817828c271bc3da089051723/webserver.js#L19

**Comment by themoonisacheese** [comment]
this was meant to be used to show the minecraft username, but i never figured a nice way of getting it, on top of being a slight security risk in the sense that if someone somehow finds your unsecured control page, they could know whether or not you're in the queue. Then again if they find that page they can straight up yeet you out of queue in the first place so yeah.
