### ISSUE TITLE
How to install for servers (tutorial coming soon)

### ISSUE THREAD

**Issue by ngt1133** [themoonisacheese/2bored2wait#11]
How i can run 2bored2wait on server, and after waiting queue i can connect from main PC to server's 2bored2wait, typing on main PC minecraft client server ip. (I need this, because after restarting main PC (On which this program is installed and opened) i am get disconnected) Sorry for so bad english.

**Comment by themoonisacheese** [comment]
Hi,

If you want to use this on another machine. here's what you need to do:

first, you need to do the installation steps on the other machine (we'll call it the server). Be sure to set openBrowserOnStart in config.json to false. If there is already a web server running on port 80, you need to change the port specified in config.json as well.

when the server is set up, you can run the proxy normally and access its control webpage using the server's IP address as an URL. If a port different than 80 is specified, you also need to use it in the url like so: `http://xx.xx.xx.xx:pp`

once the queue is started, you can access it in minecraft using the same IP.

finally, if the server is not on the same network as you, or if you want to use it from another network ( say, the server is at your home and you want to access it from work), you need to open 2 ports: one for minecraft and the other one for the webpage. these are the ports specified in config.json (defaults: 25565 and 80)

finally, if you can access the server from anywhere, so can anyone. if that's the case, be sure to set a strong password in config.json.

**Comment by ngt1133** [comment]
big thx

**Comment by viluzi** [comment]
thanks, i just wish i found this before i set it up on 2b2w.tk:26656

**Comment by AverageComet250** [comment]
This needs closing

**Comment by MrGeorgen** [comment]
properly explained from @themoonisacheese and the tutorial will likely never be done
