### ISSUE TITLE
Handing off the project

### ISSUE THREAD

**Issue by themoonisacheese** [themoonisacheese/2bored2wait#110]
As of today, @MrGeorgen has now committed more lines than i ever have. Granted, some of those were due to git doing weird stuff, but it doesn't change the fact that at some point, i will have to address multiple issues, namely:

- I have not played on 2b2t for over year
- I have not played minecraft at all in over 9 months
- I do not wish to continue working on 2bored2wait
- My reluctance to hand off the project to someone who cares at least slightly about it has lead to minor mishaps (#97)  

However, giving commit access to someone i don't know is still a really scary thing to do, especially when talking about a tool that deals with people's accounts and has my name on it. To alleviate this, I intend on naming both @MrGeorgen, for their major work in carrying this project to where it is now, and @dsetareh, for their amazing work on writing docker voodoo, as maintainers on this repo.

Unless someone has objections to this, this will happen somewhere during next month (to leave time for people to find this buried in the issues tab).

**Comment by ZillyHuhn** [comment]
Its nice to see a cool project like this not dieing but actaully finding a new maintainer :)

Thanks for your initial work @themoonisacheese

**Comment by MrGeorgen** [comment]
> Its nice to see a cool project like this not dieing but actaully finding a new maintainer :)
> 
> Thanks for your initial work @themoonisacheese

Yeah that's the cool thing about free software.

Thanks for your clear code and good comments @themoonisacheese
I understood it pretty fast even though I had never programmed in Javascript before and this project is the first where I wrote more than 100 lines. The reason for my github page being so blank is that most project are on my own [website](https://git.redstoneunion.de/MrGeorgen)

It is also nice to see that I seem to have encouraged others to contributing

**Comment by MrGeorgen** [comment]
Some of my commits were unstable, I/we should probably use the dev branch more

**Comment by themoonisacheese** [comment]
i mean yes, but also it was my responsibility as maintainer to actually check that the code i merged was functional and stable and I didn't do that.

**Comment by wylie39** [comment]
I'm also glad it's not going to die like so many projects when their maintainer losses interest. I recently found this project and I'm excited to help. One thing I would love to see is better commit and PR messages I found it hard to understand what things were done and why. 

Thanks for keeping this project alive.

**Comment by themoonisacheese** [comment]
as of today, both @MrGeorgen and @dsetareh have been invited as collaborators on this repo.
