### ISSUE TITLE
stuck in weird spectator mode when connecting after queue finishes

### ISSUE THREAD

**Issue by skylykat** [themoonisacheese/2bored2wait#126]
when not logging on while in queue and connect after the queue finishes, i get stuck in spectator mode, but i cant walk through blocks and i cant see inventory (or place, break blocks and chat). but i can still see my character in f5 (not invisible, as in normal spectator) and can fly. i dont know how to explain but i hope you understand

**Comment by EmlJnke** [comment]
Yeah I have this Issue too, at some point i just randomly died because I (most likely) happened to bug in the ceiling. The position is reset to the login position again and again, so you're unable to move..

**Comment by MrGeorgen** [comment]
Yeah the weird thing this issue only occurs on 2b2t, on my local test server I can't reproduce it

**Comment by themoonisacheese** [comment]
2b2t implementing drastic protocol deviations specifically to break nonstandard use cases is situated on the bottom of my "wow that's surprising" list

**Comment by MrGeorgen** [comment]
The abilities packet is now cached. The client now does not think it can fly anymore. I'm not sure if can break blocks because of a server restart I only had a few seconds

**Comment by MrGeorgen** [comment]
I got on 2b2t again and it only fixes the flying issue

**Comment by JackTYM** [comment]
i’m not sure how much help this is, but dying allows me to move again. The way i died was using baritone/auto walk to walk into the ocean and drowning

**Comment by MrGeorgen** [comment]
> i’m not sure how much help this is, but dying allows me to move again. The way i died was using baritone/auto walk to walk into the ocean and drowning

Yeah if you respawn almost all data will be send again.

I know now also why, if click the items only appear in the inventory, but not in hotbar. It is because 2b2t sends a set slot packet with the windowid -2 [source](https://wiki.vg/Protocol#Set_Slot) While I could not verify that, it seems the only way this could be possible

**Comment by MrGeorgen** [comment]
The inventory is now fixed. I will not close this issue because some things are still buggy after reconnecting, but it is playable

**Comment by MrGeorgen** [comment]
will be closed because other reconnecting problems are tracked at other issues
