### ISSUE TITLE
Errors in console

### ISSUE THREAD

**Issue by TheHaroldster** [themoonisacheese/2bored2wait#13]
2b2w just doesn't work. I filled in my username and password correctly, but when I click start queueing, it doesn't do anything other than error out in Inspect Element. https://imgur.com/a/idA4dKM

**Comment by themoonisacheese** [comment]
Did you specify a password in config.json? If so, you need to use it. If not, you need to keep the box empty. If you're already doing that, i'm assuming you downloaded 2b2w in the hour After my Reddit post, during which there was a bug with password that would do that. If that's the case, please download it again (you Can just overwrite webserver.js as that's where the fix went).

If that issue persists, then I have a problem on my hands.

**Comment by TheHaroldster** [comment]
Oh, thank you. Redownloading worked.
