### ISSUE TITLE
Docker completely broken

### ISSUE THREAD

**Issue by YeetyDankEngine** [themoonisacheese/2bored2wait#132]
I set up the bot in a Docker container, with Discord bot set to true. I can send every command to the bot, except for the "play"command. It just says "Error - Unknown Command".

**Comment by YeetyDankEngine** [comment]
Also at random times some commands don't work at all

**Comment by MrGeorgen** [comment]
are sure you provided the time argument for the "play" command?

**Comment by YeetyDankEngine** [comment]
Yes, I did, but for me the Docker is actually completely broken. It doesn't even let me join. But the non-Docker one works fine. I'm using Ubuntu 20.04 Server if that helps.

**Comment by MrGeorgen** [comment]
I will do some testing because I never actually tested the docker version

**Comment by YeetyDankEngine** [comment]
Thanks

**Comment by MrGeorgen** [comment]
The docker image is outdated.(sry for taking this long to figure it out.) If you build it yourself it should work. I will upload the new version soon

**Comment by MrGeorgen** [comment]
docker images are now updated. please note that the user on docker has changed
