### ISSUE TITLE
config.json issue

### ISSUE THREAD

**Issue by Mang00e** [themoonisacheese/2bored2wait#133]
When I type npm start, it says I need a "config.json" file, even though I already have it AND it's correctly filled out.

![image](https://user-images.githubusercontent.com/66450304/99140603-218df280-25f8-11eb-8286-818f38a5b9f3.png)
![image](https://user-images.githubusercontent.com/66450304/99140611-3074a500-25f8-11eb-9aee-9eb6f99a9373.png)
![image](https://user-images.githubusercontent.com/66450304/99140618-379bb300-25f8-11eb-8e07-15d6f9979922.png)

**Comment by MrGeorgen** [comment]
you put an ip address under ports.minecraft. A vaild port would 80. The error message is a bit misleading because the crash was caused by a json syntax error.  I improved the error message to show json parsing errors.
