### ISSUE TITLE
Can Someone Help me?

### ISSUE THREAD

**Issue by BloodyNoah** [themoonisacheese/2bored2wait#134]
C:\Users\codyh\Desktop\Neuer Ordner\2bored2wait-master>npm start

> 2bored2wait@1.0.0 start C:\Users\codyh\Desktop\Neuer Ordner\2bored2wait-master
> node main.js

C:\Users\codyh\Desktop\Neuer Ordner\2bored2wait-master\main.js:21
        throw("error loading config file:\n" + err);
        ^
error loading config file:
SyntaxError: Unexpected number in JSON at position 62
(Use `node --trace-uncaught ...` to show where the exception was thrown)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 2bored2wait@1.0.0 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 2bored2wait@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\codyh\AppData\Roaming\npm-cache\_logs\2020-11-15T19_09_19_752Z-debug.log

C:\Users\codyh\Desktop\Neuer Ordner\2bored2wait-master>

**Comment by MrGeorgen** [comment]
you have a syntax error in config.json

**Comment by maxrumsey** [comment]
@BloodyNoah Could you please send a copy of your 'config.json' file, or run it through a online JSON config file validator.

**Comment by BloodyNoah** [comment]
@maxrumsey sure 
{
    "discordBot": false,
    "webserver": true,
    "ports":{
        "minecraft": 8080
       "web": 28963
    },
    "openBrowserOnStart": true,
    "password":"", // password for the webinterface
    "MCversion":"1.12.2",
    "logging": true, // log errors and queue place
    "reconnect": {
        "onError": true, // reconnect on error or if 2b2t kicks you
        "notConnectedQueueEnd": false // restart the queue if you are not connect at the end of it
    },
    "minecraftserver": { // the server you want to connect. Make not much sense to change it, was just added for development purpose
        "hostname": "2b2t.org",
	"is2b2t": true, // to allow proxies inbetween 2bored2wait and 2b2t
        "port": 25565,
        "version": "1.12.2",
        "onlinemode": true,
        "username": "lol" // the username to use if onlinemode is false
    },
    "notification": { // sends a message via discord if the place in the queue reaches the specified number
        "enabled": true, // you must send the bot a message once.
        "queuePlace": 20
    },
    "userStatus": true, // show username in discord bot status, in case of alts
    "antiAntiAFK": true, // to bypass antiAFK plugins
    "chunkCaching": true,
    "joinOnStart": false, // join the server when 2b2w is started
    "whitelist": false // only let the same minecraft account join 2b2w as the one connected to 2b2t
}

**Comment by MrGeorgen** [comment]
> @maxrumsey sure
> {
> "discordBot": false,
> "webserver": true,
> "ports":{
> "minecraft": 8080
> "web": 28963
> },
> "openBrowserOnStart": true,
> "password":"", // password for the webinterface
> "MCversion":"1.12.2",
> "logging": true, // log errors and queue place
> "reconnect": {
> "onError": true, // reconnect on error or if 2b2t kicks you
> "notConnectedQueueEnd": false // restart the queue if you are not connect at the end of it
> },
> "minecraftserver": { // the server you want to connect. Make not much sense to change it, was just added for development purpose
> "hostname": "2b2t.org",
> "is2b2t": true, // to allow proxies inbetween 2bored2wait and 2b2t
> "port": 25565,
> "version": "1.12.2",
> "onlinemode": true,
> "username": "lol" // the username to use if onlinemode is false
> },
> "notification": { // sends a message via discord if the place in the queue reaches the specified number
> "enabled": true, // you must send the bot a message once.
> "queuePlace": 20
> },
> "userStatus": true, // show username in discord bot status, in case of alts
> "antiAntiAFK": true, // to bypass antiAFK plugins
> "chunkCaching": true,
> "joinOnStart": false, // join the server when 2b2w is started
> "whitelist": false // only let the same minecraft account join 2b2w as the one connected to 2b2t
> }
you need a comma after "minecraft": 8080

**Comment by BloodyNoah** [comment]
@MrGeorgen OMG it works thank you :D
