### ISSUE TITLE
got an error at the end of the queue

### ISSUE THREAD

**Issue by Potatossauro** [themoonisacheese/2bored2wait#136]
![2020 11 19-09 44 (2)](https://user-images.githubusercontent.com/41968475/99668877-0e8e7e80-2a4d-11eb-83e3-87ceb2b4b80c.png)
working fine but when the queue finished and tried to reconnect this error is given

**Comment by Potatossauro** [comment]
it was a 2b2t server queue crash

**Comment by Potatossauro** [comment]
Happened again

**Comment by YeetyDankEngine** [comment]
Looks like a JavaScript syntaxing issue

**Comment by MrGeorgen** [comment]
a packet parsing issue I think, report it to minecraft-protocol if you like
