### ISSUE TITLE
Cannot Launch using npm start

### ISSUE THREAD

**Issue by JackTYM** [themoonisacheese/2bored2wait#137]
Title.

`C:\Users\**REDACTED**\Documents\Minecraft Stuffs\2bored2wait-master\main.js:21                                                       throw("error loading config file:\n" + err);                                                                            ^                                                                                                               error loading config file:                                                                                              SyntaxError: Unexpected token D in JSON at position 14                                                                  (Use `node --trace-uncaught ...` to show where the exception was thrown)                                                npm ERR! code ELIFECYCLE                                                                                                npm ERR! errno 1                                                                                                        npm ERR! 2bored2wait@1.0.0 start: `node main.js`                                                                        npm ERR! Exit status 1                                                                                                  npm ERR!                                                                                                                npm ERR! Failed at the 2bored2wait@1.0.0 start script.                                                                  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.                                                                                                                                              npm ERR! A complete log of this run can be found in:                                                                    npm ERR!     C:\Users\**REDACTED**\AppData\Roaming\npm-cache\_logs\2020-11-28T17_46_34_420Z-debug.log `

log file:

`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v14.15.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle 2bored2wait@1.0.0~prestart: 2bored2wait@1.0.0
6 info lifecycle 2bored2wait@1.0.0~start: 2bored2wait@1.0.0
7 verbose lifecycle 2bored2wait@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle 2bored2wait@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\**REDACTED**\Documents\Minecraft Stuffs\2bored2wait-master\node_modules\.bin;%INTEL_DEV_REDIST%redist\intel64\compiler;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\libnvvp;C:\Program Files\Oculus\Support\oculus-runtime;C:\Program Files (x86)\VMware\VMware Player\bin\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Git\cmd;C:\Program Files (x86)\dotnet\;C:\Program Files\nodejs\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Git\cmd;C:\Users\**REDACTED**\AppData\Local\Programs\Python\Python38\Scripts\;C:\Users\**REDACTED**\AppData\Local\Programs\Python\Python38\;C:\Users\**REDACTED**\AppData\Local\Programs\Python\Launcher\;C:\Users\**REDACTED**\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Win7TaskManager";C:\Users\**REDACTED**\AppData\Local\GitHubDesktop\bin;C:\Users\**REDACTED**\AppData\Roaming\npm
9 verbose lifecycle 2bored2wait@1.0.0~start: CWD: C:\Users\**REDACTED**\Documents\Minecraft Stuffs\2bored2wait-master
10 silly lifecycle 2bored2wait@1.0.0~start: Args: [ '/d /s /c', 'node main.js' ]
11 silly lifecycle 2bored2wait@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle 2bored2wait@1.0.0~start: Failed to exec start script
13 verbose stack Error: 2bored2wait@1.0.0 start: `node main.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid 2bored2wait@1.0.0
15 verbose cwd C:\Users\**REDACTED**\Documents\Minecraft Stuffs\2bored2wait-master
16 verbose Windows_NT 10.0.19041
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v14.15.1
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error 2bored2wait@1.0.0 start: `node main.js`
22 error Exit status 1
23 error Failed at the 2bored2wait@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

Anything I can do to fix?

**Comment by MrGeorgen** [comment]
you have a syntax error in your config.json. The comments are not valid json, but they are removed before the json is parsed

**Comment by JackTYM** [comment]
My config.json is as follows:

`{
    "discordBot": DISCORDBOT_FLAG,
    "webserver": WEBSERVER_FLAG,
    "ports":{
        "minecraft":MINECRAFT_PROXY_PORT, // port for the proxy server
       "web":WEB_UI_PORT
    },
    "openBrowserOnStart": false,
    "password":"", // password for the webinterface
    "MCversion":"1.12.2",
    "logging": true, // log errors and queue place
    "reconnect": {
        "onError": true, // reconnect on error or if 2b2t kicks you
        "notConnectedQueueEnd": false // restart the queue if you are not connect at the end of it
    },
    "minecraftserver": { // the server you want to connect. Make not much sense to change it, was just added for development purpose
        "hostname": "2b2t.org",
	"is2b2t": true, // to allow proxies inbetween 2bored2wait and 2b2t
        "port": 25565,
        "version": "1.12.2",
        "onlinemode": true,
        "username": "lol" // the username to use if onlinemode is false
    },
    "notification": { // sends a message via discord if the place in the queue reaches the specified number
        "enabled": true, // you must send the bot a message once.
        "queuePlace": 20
    },
    "userStatus": true, // show username in discord bot status, in case of alts
    "antiAntiAFK": true, // to bypass antiAFK plugins
    "chunkCaching": true,
    "joinOnStart": false, // join the server when 2b2w is started
    "whitelist": false // only let the same minecraft account join 2b2w as the one connected to 2b2t
}
`

What do I need to change?

**Comment by MrGeorgen** [comment]
take a look at step 5 in the readme under "How to install"
