### ISSUE TITLE
Question: Need help with Discord BOT 

### ISSUE THREAD

**Issue by MrMasrozYTLIVE** [themoonisacheese/2bored2wait#138]
$ (node:5928) UnhandledPromiseRejectionWarning: DiscordAPIError: Cannot send messages to this user
I'm don't understand where im should write my id for DiscordBOT

**Comment by MrGeorgen** [comment]
If you dm the bot, it will write your id to `saveid`(a file called savid in the 2b2w directory). You could also write the id manually, but it is not required
