### ISSUE TITLE
How does the program work?

### ISSUE THREAD

**Issue by JackTYM** [themoonisacheese/2bored2wait#139]
I got the program running, waited 2 1/2 hours for the queue to finish, then realized, how do i join on my client? Is that the purpose of this client to wait in the queue without an entire client running and then be able to join on one after?

**Comment by MrGeorgen** [comment]
yeah the purpose is you don't have to run an entire client. When the queue is nearly finished you can connect with your minecraft client to `localhost:(port set in the config`

**Comment by JackTYM** [comment]
ohh you connect with localhost in the client. Thank you!
