### ISSUE TITLE
better time calculator

### ISSUE THREAD

**Issue by MrGeorgen** [themoonisacheese/2bored2wait#141]
Hey I'm currently trying to a better time calculator( a time, place in the queue function) based on a exponential decay function. However I do not know how many of the 250 slots are not reversed for priority queue. This would be important to know because the priority queue is independent of the normal queue. So if anybody know this, please let me know

**Comment by wylie39** [comment]
Take a look at this [](https://2b2t.dev/)

**Comment by weedoe** [comment]
> Take a look at this (https://2b2t.dev/)

I don't see the amount of slots that are reserved on the server for users with priority queue on that site. It only shows a graph of the current amount of priority queue users in queue.

**Comment by themoonisacheese** [comment]
i don't think any slots are reserved for prio queue, it just seems like prio queue just bypasses normal queue and if someone is in prio queue then they will connect before anyone in regular queue connects.

**Comment by MrGeorgen** [comment]
> i don't think any slots are reserved for prio queue, it just seems like prio queue just bypasses normal queue and if someone is in prio queue then they will connect before anyone in regular queue connects.

This would mean that you get in through normal queue a few hours a day. But I think with some time and test data I can develop a function anyway. (I'm not sure if I have the time.)

**Comment by themoonisacheese** [comment]
> This would mean that you get in through normal queue a few hours a day.

that doesn't sound that preposterous

**Comment by weedoe** [comment]
I guess it starting early is a part of this issue, sorry about that

**Comment by themoonisacheese** [comment]
based off of the data shown at https://2b2t.io/ , where we can see that both queues can diminish at the same time, it  would be fair to assume that the server can pull from both queues while alternating between them. A naive guess of mine is that the server just alternates between both queues on a 1:1 ratio, and that prio queue is only faster by virtue of being less populated. however, it is entirely possible (and would be very hard to calculate based on the limited data) that another ratio is used, probably in favor of prio queue.

another option would be to try to estimate how the queue might change in the future, based off of historical data (eg the server might be less populated during american mornings and nights, etc) however i know barely enough about this to know hat i do not have the skill for it.

**Comment by MrGeorgen** [comment]
>it would be fair to assume that the server can pull from both queues while alternating between them

As stated [here](https://2b2t.miraheze.org/wiki/Queue#System) there are indeed slots reserved for priority queue. I'm sure if this is where I have this information from, but let's say there are 100 slots reserved for priority queue. I think if one from the 150 players leaves who got in through normal queue, a new player from normal queue gets in. But if a player of the 100 reserved players leaves, a new player form priority queue gets in.
If this is true a exponential decay function would work because on lower queue places it is less likely that someone before you leaves the queue. Because we can get as much points on function as we want it is not required to know how many slots are reserved for priority queue. We also need to move the function a bit down because the player currently playing can also leave the server. The function would look something like this:
f(x) = (a + c) * b^x - c
f(x): place in the queue
c: number of queue places not reversed for priority queue
a: start queue place
b: faktor based on how fast we move in the queue
x: time

**Comment by themoonisacheese** [comment]
> As stated [here](https://2b2t.miraheze.org/wiki/Queue#System) there are indeed slots reserved for priority queue.

looking at the revision history on that page, we can see that the claim of "reserved slots" is as old as the page itself, when it was written by user DrifAssault in march, who claims "I do not play 2b2t, but I am very interest at this", ie not a really trustworthy source (though they might still be right).

either way, if i understand correctly, the actual amount of reserved slots on the server matters very little, as the only slots that matter are the ones being occupied at any x  by players in the prio queue, as stat we have available on 2b2t.dev 

this means that:
c: we know this approximately, from 2b2t.dev / 2b2t.io
a: we obviously can know this
b: I assume this is calculated then refined as time goes on at runtime in order to have a more accurate estimate
x: is the value we're solving for
f(x): we know this, obviously

this leaves us with this math, which thanfully we don't have to do by hand (i've swapped f(x) for y as that's more neat to write):
```
(a+c) * b^x -c = y
(a+c) *b^x = y + c 
b^x = (y+c)/(a+c) 
x = log((y+c)/(a+c))/log(b)
```

the harder part is (apart from actually implementing this, namely the fetching data part) to compute b so that the x we solve for is sensical. this i have little idea how to do this, but i assume it involves calculating our current queue position, then adjusting b either up or down by some amount until the calculated position is close enough to the actual one. There is probably a better suited approach, which doesn't involve a lot of expensive calculations (which kinda ruin the whole idea of the proxy; if it's more taxing to run than a minecraft instance, might as well run a minecraft instance).

**Comment by themoonisacheese** [comment]
additionally, on their info page, 2b2t.io says that if we know how to use their api, we are free to do so.
here's how to use their api:
endpoints are http GET at:
queue
pingstats (server total)
prioqueue
they all take query parameter `range` (1h, 24h etc), which is simply parsed as time since when you want the stats .

response is a json array of tuples, the first element is a unix timestamp, and the second is the data relating to that particular endpoint.

endpoints can alternatively take query parameter `last`, value always true if specified.
in that case, response is a json array containing a single tuple, first element timestamp, second element is the last datapoint available

the webpage appears to be programmed to fetch new info every 20 seconds, which is a reasonable interval given slow nature of this

**Comment by MrGeorgen** [comment]
> the harder part is (apart from actually implementing this, namely the fetching data part) to compute b so that the x we solve for is sensical. this i have little idea how to do this, but i assume it involves calculating our current queue position, then adjusting b either up or down by some amount until the calculated position is close enough to the actual one. There is probably a better suited approach, which doesn't involve a lot of expensive calculations

we need to solve for b and use a time value for x and the corresponding queue place for y
```
(a+c) * b^x -c = y
(a+c) * b^x = y + c
b^x = (y+c)/(a+c)
b = ((y+c)/(a+c))^(1/x)
```
>c: we know this approximately, from 2b2t.dev / 2b2t.io

yeah we can guess it, but just need to know a second point on the function to calculate it... a bit later I noticed it is not that esay. I failed solving for c and wolfram alpha also failed. Note x1 and y1 correspond to one point of the function 
```
(a+c) * (((y1+c)/(a+c))^(1/x1))^x2 =y2
```
So we have to guess or I could ask my math teacher.
>additionally, on their info page, 2b2t.io says that if we know how to use their api, we are free to do so.

yeah I knew about the queue endpoint, thanks for the other information however

**Comment by MrGeorgen** [comment]
we use 2b2t.io by the way to get the queue length

**Comment by themoonisacheese** [comment]
> c: number of queue places not reversed for priority queue

either i'm confused by my own brain or by your phrasing; doesn't that mean that c is whatever the current amount of non-priority queuers? because if it is, we know the total size of queue and we know the size of prio queue, and we just substract them.

if not, then i have no idea what c is.

**Comment by MrGeorgen** [comment]
> > c: number of queue places not reversed for priority queue
> 
> either i'm confused by my own brain or by your phrasing; doesn't that mean that c is whatever the current amount of non-priority queuers? because if it is, we know the total size of queue and we know the size of prio queue, and we just substract them.
> 
> if not, then i have no idea what c is.

it is number of players that are on main server and got in through normal queue. However if the likelihood of a player who is playing leaving the server is different than someone leaving the queue than this number could also be something else. Thats why I tried to calculate it

**Comment by AverageComet250** [comment]
Can't you get the average time between a user's change of position in the queue and then times it by the amount of people in the queue to work out the time and also find the difference between it and the one that 2b2t gives and make sure it's not crazy high to tell if it's a possible time or a complete waste.

Logically speaking: I would count the time to go down in the queue, save the number to an array and repeat the process until I have three numbers in it. I would then calculate the average of those numbers and times it by my queue position. That would be my rough time to join the server. As I keep going through the queue, I would keep committing the time to go down a position to my array and thus allowing my average to become more accurate.

I would write out a formula but I can't work one  out since this is based of logic not mathematical facts so yeah.

**Comment by themoonisacheese** [comment]
i am 75% sure this is exactly how the ETA given by 2b2t is calculated.

**Comment by AverageComet250** [comment]
Oh.

I guess we can ditch it then because the one given 2b isn't always exact.

**Comment by MrGeorgen** [comment]
I tested the function with a old log and it looks really good. I assumed c to be 150 and calculated b based on F (b = 0.994 geogebra does not display it exactally)
![image](https://user-images.githubusercontent.com/65063405/104018011-6fb71080-51b9-11eb-9544-1d8f3f018044.png)
I'll test if it also works with longer queues

**Comment by MrGeorgen** [comment]
ok with a queue size 1200 I get b = 0.997
maybe we have to define b based a

**Comment by MrGeorgen** [comment]
we could use interpolation to get b from a. I added some code on queueTimeCalc branch to get enough data for it

**Comment by plebeo** [comment]
You closed this, but take a look at this:

![Cattura](https://user-images.githubusercontent.com/72709996/108824931-a1960200-75c2-11eb-9bd4-9a2a4f947382.PNG)

This is totally fckd up. 
main.js and config.json are exactly the same, running on the same machine, all configured properly. You should continue your path, as I read you aren't that far from a serious solution. Fixing this big issue would be appreciated from everyone as it's totally annoying.

**Comment by MrGeorgen** [comment]
> @MrGeorgen
> You closed this, but take a look at this:

Ok thats really broken. Do you have the same queue.json dataset on.

I think the the value for is not good because you can at graph above that it
seems to work with the right value for b.
to work around this problem the ETA could be calculated from a b value which based on point on the
function rather on the dataset.

However the dataset still must be for the "play" command and ETA at the
beginning (we need to some places before we can get a proper b).
The problem is that I assumed b is linear to a. But if you take a look at
queue.json. b = factor (I know b is a exponent. I can change the name someday)
a = queuePlace
index 0 of queuePlace is corresponds to index 0 of factor and so on.
That raises the question why it is not linear? As I understand it, it should.
Maybe it is partly but also dependent on other factors. When a lot of players
go to bed (in rl) then you move faster. mabye connecting directly after 2b2t
restarted is not comparable to other times. Because everyone before you either
uses autoReconnect or 2b2w. Those players could less likly disconnect or
something. To this out we should save the time of the day and if 2b2t
restarted recently addtionaly.

>Edit: I can help you with less-mathematical stuff, like Queue tests using more Minecraft accounts, telling you about my experience in the queue as I know a bit about it

Maybe you have experience with these other factors I talked abut above.
mc accounts are good for testing. I'm not sure how much data we need. I'll
queueing 24/7 after I finnished save these other factors. You could do that
too and post your data

**Comment by onayB09** [comment]
uhh... so with that new update, i started play command and its never joined the queue for 24 hours. then i manualy started the queue to whats gonna happen and i see this.
![image](https://user-images.githubusercontent.com/53120690/113725017-970b7400-96fb-11eb-8620-9549686df2fa.png)
can someone explain whats happening? Am i need a time travel machine to join 2b2t?

**Comment by MrGeorgen** [comment]
>uhh... so with that new update, i started play command and its never joined the queue for 24 hours. then i manualy started the queue to whats gonna happen and i see this.

at what did you run the command the queue? When I tested it, it joined right away.
At the recent update I also did not change something at the play command.
Only calculating the ETA while queuing.
However it should still join within 24 hours.

>Update: I encountered this problem today

This is possible when you move slower forward than expect.
For a few places this should be okay. However if it ETA goes up for hours,
it's a problem of course.

**Comment by MrGeorgen** [comment]
>uhh... so with that new update, i started play command and its never joined the queue for 24 hours. then i manualy started the queue to whats gonna happen and i see this.

After checking the code, I noticed that erros to the 2b2t.io api are not
handled. This means if one request fails, the command stops

**Comment by onayB09** [comment]
> > uhh... so with that new update, i started play command and its never joined the queue for 24 hours. then i manualy started the queue to whats gonna happen and i see this.
> 
> After checking the code, I noticed that erros to the 2b2t.io api are not
> handled. This should not cause 2b2w to never join the queue

I dont know how the ETA system works but its doing this randomly. Thats what im talking about. And Youre Right I Tried It Again and typed play 19:00 but program joined the queue 20:00.

**Comment by MrGeorgen** [comment]
I think I finally the answer on how to fix the play command.
I joined the queue at 14:15. 5 minutes later it showed a ETA of 6h 32m, so it
predicted that I would join the server at 20:52. In reality I joined it at
20:39.
My new implementation would look like this: after the play command is executed, it joins the queue.
A few minutes later it calculates the ETA. If the ETA is smaller than there is time left to the user specified time,
2b2w reconnets.

**Comment by MrGeorgen** [comment]
I just saw I messed up that [commit](https://github.com/themoonisacheese/2bored2wait/commit/f91298f2085b48cdc84bef503cb10eb1fa0a8628) I used partly an interpolated b value and partly a calculated one at runtime. That work so well (my last comment) must mean that those b values were almost identical.
First my new implentation of the play mentined obove would work, but really
well.
This also proves that b is indeed depended on a.
And this means [my other factor theorie](https://github.com/themoonisacheese/2bored2wait/issues/141#issuecomment-784412583) is most likely right. I guess the most
important one is connecting after a restart.

Just because I can I'll push version without interpolation to a sperate branch

**Comment by themoonisacheese** [comment]
closing, as this has been completed a while ago as far as I know.

**Comment by MrGeorgen** [comment]
> closing, as this has been completed a while ago as far as I know.

not really, most of what I did in april, was reverted. I have put all our values into geogebra (for the exponent I used `(factor - 0.999) * 10⁴`)
![image](https://user-images.githubusercontent.com/65063405/129492276-56d4ecea-a9eb-4719-afff-aa6bdbc30732.png)
I can't really explain why B, C, E, and F are where they are. However J, G, A, M, L, I and D, H, K, N are almost a line. Next I will do what I described [here](https://github.com/themoonisacheese/2bored2wait/issues/141#issuecomment-784412583)

**Comment by rob9315** [comment]
Hello @MrGeorgen, nice to see you again!
I'd like to improve the queue as well and maybe we can talk about this a little on discord? Rob9315#9332
I have had some plans as well but I didn't exactly know how to realize them.

**Comment by MrGeorgen** [comment]
> Hello @MrGeorgen, nice to see you again!
> I'd like to improve the queue as well and maybe we can talk about this a little on discord? Rob9315#9332
> I have had some plans as well but I didn't exactly know how to realize them.

yeah I'm IAmCoronaEatMe#6725. I'll send a friend request

**Comment by KozmikNano** [comment]
Closing as time calculator has essentially already been revamped
