### ISSUE TITLE
error when npm install

### ISSUE THREAD

**Issue by HW12345** [themoonisacheese/2bored2wait#142]
I typed cd C:\Users\------\Desktop\2bored2wait-master and npm install in node.js command prompt in admin mode but it showed
npm ERR! code 1
npm ERR! command failed
npm ERR! command git ls-remote ssh://git@github.com/zekesonxx/node-yggdrasil.git
npm ERR! 'git' is not recognized as an internal or external command,
npm ERR! operable program or batch file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\-------\AppData\Local\npm-cache\_logs\2020-12-04T13_09_41_503Z-debug.log
can anyone help me with this?

**Comment by themoonisacheese** [comment]
you need to install git for windows, which is normally packaged with node js
