### ISSUE TITLE
another problem

### ISSUE THREAD

**Issue by HW12345** [themoonisacheese/2bored2wait#146]
So I've followed the step 5. It didn't errors, but when I enter localhost in browser and enters, browser says This site can’t be reached. I went and type start in the command, it starts, but freeze after a few second or just stuck at the Queue is starting up thing.
also, this is my config
```
{
    "discordBot": false,
    "webserver": false,
    "ports":{
        "minecraft":25565, // port for the proxy server
       "web":80
    },
    "openBrowserOnStart": false,
    "password":"", // password for the webinterface
    "MCversion":"1.12.2",
    "logging": true, // log errors and queue place
    "reconnect": {
        "onError": true, // reconnect on error or if 2b2t kicks you
        "notConnectedQueueEnd": false // restart the queue if you are not connect at the end of it
    },
    "minecraftserver": { // the server you want to connect. Make not much sense to change it, was just added for development purpose
        "hostname": "2b2t.org",
	"is2b2t": true, // to allow proxies inbetween 2bored2wait and 2b2t
        "port": 25565,
        "version": "1.12.2",
        "onlinemode": true,
        "username": "lol" // the username to use if onlinemode is false
    },
    "notification": { // sends a message via discord if the place in the queue reaches the specified number
        "enabled": true, // you must send the bot a message once.
        "queuePlace": 20
    },
    "userStatus": true, // show username in discord bot status, in case of alts
    "antiAntiAFK": true, // to bypass antiAFK plugins
    "chunkCaching": true,
    "joinOnStart": false, // join the server when 2b2w is started
    "whitelist": false // only let the same minecraft account join 2b2w as the one connected to 2b2t
}

```
(sorry about the amount of question I've posted.)
and, after some queue, it errors again:
'''
$ node:events:306
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 0.0.0.0:25565
    at Server.setupListenHandle [as _listen2] (node:net:1285:16)
    at listenInCluster (node:net:1333:12)
    at doListen (node:net:1470:7)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
Emitted 'error' event on Server instance at:
    at Server.<anonymous> (C:\Users\Harry\Desktop\2bored2wait-master\node_modules\minecraft-protocol\src\server.js:44:12)
    at Server.emit (node:events:329:20)
    at emitErrorNT (node:net:1312:8)
    at processTicksAndRejections (node:internal/process/task_queues:80:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 25565
}
npm ERR! code 1
npm ERR! path C:\Users\-----\Desktop\2bored2wait-master
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c "node main.js"

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\-----\AppData\Local\npm-cache\_logs\2020-12-06T06_13_21_487Z-debug.log
'''

**Comment by weedoe** [comment]
> address already in use 0.0.0.0:25565
This error here leads me to believe that you have multiple instances of the bot running or your selected port is already being used by another application.

**Comment by klokwert** [comment]
Why is this issue not yet closed?

**Comment by nickcat325** [comment]
Try http://localhost:8080 or 127.0.0.1:8080

**Comment by KozmikNano** [comment]
You never turned the web server on.

**Comment by KozmikNano** [comment]
Also it seems like you are hosting a server already. In the ports section change 25565 to 25566.
