### ISSUE TITLE
Queueing randomly stops

### ISSUE THREAD

**Issue by viluzi** [themoonisacheese/2bored2wait#15]
While waiting in queue using this proxy, it randomly disconnects. not sure if that is a problem with 2b2t itself. Automatically reconnecting would be nice

**Comment by themoonisacheese** [comment]
closed as duplicate of #3

**Comment by viluzi** [comment]
wouldnt call it a duplicate. i literally get disconnected, q doesnt break. it just stops. stop button chages into start

**Comment by themoonisacheese** [comment]
ah. I can't fix that. the proxy should reconnect automatically though.

**Comment by viluzi** [comment]
all i can say its frustrating that after a while in q with it it stops. if it cant be fixed ill live with it.

**Comment by themoonisacheese** [comment]
this happens when 2b2t lags out. Except from snapping away half of etikas fan base, I can't do much about it.
