### ISSUE TITLE
Minecraft Microsoft 2fa

### ISSUE THREAD

**Issue by wylie39** [themoonisacheese/2bored2wait#154]
In 2021 Minecraft will require a Microsoft account to log in, see [Here.](https://help.minecraft.net/hc/en-us/articles/360050865492) As of right now, Microsoft has not said how Third-party launchers will continue to work if at all, see link above. We will probably have to rewrite how people log in to accommodate 2fa and other factors.

This will have implications on 2b2w, and I am starting this issue as a placeholder. (@themoonisacheese or @MrGeorgen  can you pin this?)

**Comment by MrGeorgen** [comment]
I'm not able to test this, but minecraft-protocol has already support for microsoft accounts, as you can see [here](https://github.com/PrismarineJS/node-minecraft-protocol/pull/788). Should be esay to implement

**Comment by wylie39** [comment]
2fa is not supported but we will probably have to live with that.

**Comment by MrGeorgen** [comment]
> 2fa is not supported but we will probably have to live with that.

yeah I have opened an [issue](https://github.com/PrismarineJS/node-minecraft-protocol/issues/791)
