### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by HypnoAnt** [themoonisacheese/2bored2wait#157]
![image](https://user-images.githubusercontent.com/76222456/102642720-0746b780-4156-11eb-802c-4b0599a3785b.png)

**Comment by YeetyDankEngine** [comment]
can you run the command dir

**Comment by HypnoAnt** [comment]
![image](https://user-images.githubusercontent.com/76222456/102686855-60f4c380-41e2-11eb-97d3-8bd3487678b8.png)
This Happens

**Comment by HypnoAnt** [comment]
I figured it out

**Comment by YeetyDankEngine** [comment]
noice
