### ISSUE TITLE
ReferenceError: authType is not defined

### ISSUE THREAD

**Issue by Qbox683** [themoonisacheese/2bored2wait#160]
It seems I have done everything correct, I entered everything correctly including authtype (mojang or microsoft) and i correct capitalisation. when trying to capitalise it in secrets.json, it gave the same error. full error here 
![image](https://user-images.githubusercontent.com/71836302/103061548-48353680-4571-11eb-9a6b-3db8526e54df.png)

**Comment by YeetyDankEngine** [comment]
re-download the 2b2w, `npm install` and then straight away run `npm start`. There will be a prompt to enter your detailed and other stuff.

**Comment by MrGeorgen** [comment]
I misspelled the variable name, but it only occurred when using a microsoft account. It should work now (I can't test it)
