### ISSUE TITLE
Proxy unable to connect to 2b2t

### ISSUE THREAD

**Issue by misterissac** [themoonisacheese/2bored2wait#162]
After typing npm start and pressing "start queuing". the button immediately changes back to green. The following appears in node.js:

> C:\Users\issac\Downloads\2bored2wait-master\2bored2wait-master>npm start
>
>\> 2bored2wait@1.0.0 start C:\Users\issac\Downloads\2bored2wait-master\2bored2wait-master
\> node main.js
>
>Connection error by 2b2t server. Error message: Error: getaddrinfo ENOTFOUND 2b2t.org Reconnecting...
Connection reset by 2b2t server. Reconnecting...
Reconnecting...
Reconnecting...`
>
Any help will be appreciated.

**Comment by YeetyDankEngine** [comment]
was 2b2t up at that time and/or did you have internet access

**Comment by misterissac** [comment]
Yes, I was able to join the 2b2t queue using the official minecraft client. I also tried again just now and the outcome was the same.

**Comment by MrGeorgen** [comment]
Looks like a dns resolving error. Try to enter 2b2t ip as a workaround

**Comment by misterissac** [comment]
I figured it out. The solution is to allow node.js through windows firewall on both public and private networks. Anyway, thanks for all the help!

**Comment by misterissac** [comment]
Now I tried to re-queue again and it stopped working. I tried changing the "hostname" in config.json to connect.2b2t.org but it did nothing. Again I was able to join the queue using the official client. The error msg in node.js is gone though, now it's just stuck in reconnecting:

> C:\Users\issac\Downloads\2bored2wait-master\2bored2wait-master>npm start
> 
> \> 2bored2wait@1.0.0 start C:\Users\issac\Downloads\2bored2wait-master\2bored2wait-master
> \> node main.js
> 
> Connection reset by 2b2t server. Reconnecting...
> Reconnecting...
> Connection reset by 2b2t server. Reconnecting...
> Reconnecting...
> Connection reset by 2b2t server. Reconnecting...
> Reconnecting...
> Connection reset by 2b2t server. Reconnecting...
> Reconnecting...
> $ Terminate batch job (Y/N)?
> ^C

**Comment by misterissac** [comment]
@MrGeorgen Do you mean changing "hostname" in config.json? Is there some other ip I should try?

**Comment by MrGeorgen** [comment]
> @MrGeorgen Do you mean changing "hostname" in config.json? Is there some other ip I should try?

ok 2b2t.org can not be found under my system:
```
[mrgeorgen@mrgPC ~/dev/js/2bored2wait]$ nslookup 2b2t.org 
Server:         192.168.2.1 
Address:        192.168.2.1#53 
Non-authoritative answer: 
*** Can't find 2b2t.org: No answer 
```
seems like housemaster messed something up

**Comment by AverageComet250** [comment]
I think this can be closed again now
