### ISSUE TITLE
npm install issue code ENOENT

### ISSUE THREAD

**Issue by ISmile008** [themoonisacheese/2bored2wait#163]
C:\Users\Admin\Desktop\2bored2wait-master>npm install
npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/zekesonxx/node-yggdrasil.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2020-12-26T19_23_21_615Z-debug.log

**Comment by YeetyDankEngine** [comment]
run `npm install -g npm@latest`

**Comment by YeetyDankEngine** [comment]
then try again

**Comment by ISmile008** [comment]
ok

**Comment by ISmile008** [comment]
it doesn't work

**Comment by ISmile008** [comment]
C:\Users\Admin\Desktop\2bored2wait-master>npm install -g npm@latest
C:\Users\Admin\AppData\Roaming\npm\npm -> C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
C:\Users\Admin\AppData\Roaming\npm\npx -> C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\bin\npx-cli.js
+ npm@6.14.10
updated 1 package in 9.784s

C:\Users\Admin\Desktop\2bored2wait-master>
C:\Users\Admin\Desktop\2bored2wait-master>C:\Users\Admin\Desktop\2bored2wait-master>npm install -g npm@latest
C:\Users\Admin\AppData\Roaming\npm\npm -> C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
C:\Users\Admin\AppData\Roaming\npm\npx -> C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\bin\npx-cli.js
+ npm@6.14.10
updated 1 package in 9.784s

C:\Users\Admin\Desktop\2bored2wait-master>
C:\Users\Admin\Desktop\2bored2wait-master>npm install
npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/zekesonxx/node-yggdrasil.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2020-12-27T11_13_29_029Z-debug.log

C:\Users\Admin\Desktop\2bored2wait-master>

**Comment by MrGeorgen** [comment]
you must install git
