### ISSUE TITLE
Not really a Issue but a anti Issue

### ISSUE THREAD

**Issue by klokwert** [themoonisacheese/2bored2wait#166]
There are so many issues about that the port is already in use or that port 80 couldn't be used,
Please add something that detects if that's the case and then tells the user about it and (maybe) auto chooses another port

**Comment by AverageComet250** [comment]
I think a backup port should be specified in `config.json` and it should print a warning and then attempt use that port. E.g. port 80 in use, reverting to port 8080.

**Comment by MrGeorgen** [comment]
auto choose another port won't be implemented as no other program does this
