### ISSUE TITLE
error while npm start

### ISSUE THREAD

**Issue by ISmile008** [themoonisacheese/2bored2wait#169]
C:\Users\Admin>cd Desktop\2bored2wait-master

C:\Users\Admin\Desktop\2bored2wait-master>npm start

> 2bored2wait@1.0.0 start C:\Users\Admin\Desktop\2bored2wait-master
> node main.js

$ (node:8488) UnhandledPromiseRejectionWarning: Error [TOKEN_INVALID]: An invalid token was provided.
    at Client.login (C:\Users\Admin\Desktop\2bored2wait-master\node_modules\discord.js\src\client\Client.js:206:52)
    at Object.<anonymous> (C:\Users\Admin\Desktop\2bored2wait-master\main.js:340:5)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8488) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8488) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by YeetyDankEngine** [comment]
do `npm install` first

**Comment by ISmile008** [comment]
> do `npm install` first

i did it

**Comment by klokwert** [comment]
You have probably the discord bot enabled in the config but didn't input a valid discord token

**Comment by ISmile008** [comment]
> Вероятно, у вас есть бот discord, включенный в конфигурации, но вы не ввели действительный токен discord

Is it mandatory?

**Comment by MrGeorgen** [comment]
> > Вероятно, у вас есть бот discord, включенный в конфигурации, но вы не ввели действительный токен discord
> 
> Is it mandatory?

no you can disable the discord in the config

**Comment by ISmile008** [comment]
> > > Вероятно, у вас есть бот discord, включенный в конфигурации, но вы не ввели действительный токен discord
> > 
> > 
> > Is it mandatory?
> 
> no you can disable the discord in the config

how?

**Comment by YeetyDankEngine** [comment]
flag the discord bot as false in the config.json
