### ISSUE TITLE
Docker issue

### ISSUE THREAD

**Issue by klokwert** [themoonisacheese/2bored2wait#171]
**When using docker, you have to update the start cmd from**
`/bin/sh -c /srv/app/replace_config.sh && /srv/app/replace_credentials.sh && npm start`
to
`/bin/sh -c /srv/app/replace_config.sh && /srv/app/replace_credentials.sh && npm install; npm start;`
**Otherwise it won't start**

And if something goes wrong, and you want to fix it before the docker fully exitted (**you can't edit the files when docker exitted**) you have to add something like:
`/bin/sh -c /srv/app/replace_config.sh && /srv/app/replace_credentials.sh && npm install; npm start; sleep 3600;`

Please change it at least to:
`/bin/sh -c /srv/app/replace_config.sh && /srv/app/replace_credentials.sh && npm install; npm start;`

**Comment by YeetyDankEngine** [comment]
do a pull request

**Comment by klokwert** [comment]
Why would I close it while it's not yet fixed

**Comment by MrGeorgen** [comment]
when the docker container is built `npm install` already runs, so running it again is unnecessary

**Comment by klokwert** [comment]
> when the docker container is built `npm install` already runs, so running it again is unnecessary

If I have time I will send a vid of me not being able to start it before I did run npm install

**Comment by MrGeorgen** [comment]
> > when the docker container is built `npm install` already runs, so running it again is unnecessary
> 
> If I have time I will send a vid of me not being able to start it before I did run npm install

npm install might fail after the container is built because git is not insalled anymore, which is needed to download a dependency
