### ISSUE TITLE
Are microsoft accounts supported in the current version?

### ISSUE THREAD

**Issue by jonylentzmc** [themoonisacheese/2bored2wait#175]
Hi, happy 2021, and thanks for maintaining this project updated 
I've just installed 2bored2wait on a Ubuntu 18 machine, the installation was successful but the client cant authenticate using my Microsoft account, the program runs but when I type "update" in the terminal, it only returns "authentication" instead of my queue position, I have double checked the secrets.json file and it is correct, I have tried to reinstall and even install the Docker variant without any success,
My Microsoft account has 2 factor authentication disabled
I’m able to log in and join 2b2t using my Minecraft client without a problem
I was forced by mojang to create a Microsoft account when I redeemed Minecraft, I could not create a mojang only account to play
Any suggestions on what am I doing wrong?
![auth](https://user-images.githubusercontent.com/76884929/103467105-5bdb5c80-4d2a-11eb-9e78-bc3d585dd41f.PNG)

**Comment by MrGeorgen** [comment]
i just cheeked the code and saw I forgot to `join()` after the login to the server

**Comment by jonylentzmc** [comment]
Thank you!, it's working fine now!  : )
![2b2t](https://user-images.githubusercontent.com/76884929/103468569-22f6b400-4d39-11eb-883a-317914a7abf8.PNG)
