### ISSUE TITLE
Discord bot doesn't want to come online

### ISSUE THREAD

**Issue by AverageComet250** [themoonisacheese/2bored2wait#176]
The discord bot won't come online and is completely useless at the minute.

I have it in my dms as well as in a server (so I could message it).

IT WONT COME ONLINE.

If wanted I can try fixing it and making a pr as I already have a fork that I was going to use to upgrade the web page and add electron but I'll make a separate issue about that.

**Comment by Pandapip1** [comment]
You've got the wrong repo: https://github.com/ethrx/2lazy2wait is the one you're looking for

**Comment by AverageComet250** [comment]
No this is repo I was after and I fixed the issue by going into secret.json and putting it in there manually.
