### ISSUE TITLE
Upgrading the web page and making a togglable anti-afk

### ISSUE THREAD

**Issue by AverageComet250** [themoonisacheese/2bored2wait#177]
I mentioned this on another issue I made about something else but I wanted to ask if upgrading the web page and converting it into an electron app was a good idea. I'm happy to add them myself if wanted as well as making an anti-afk (similar to the impact one) that can be run when you're not connected but aren't in queue.

I have a fork already, however it's currently the same or a commit or 2 behind that I can use.

**Comment by themoonisacheese** [comment]
If you ask yourself, in the end, what is this tool for? if you replied "it's just cool lmao" then i guess we disagree. the point of the tool was to enable you to not have a minecraft instance running while in the queue, thus saving a little on resources. adding electron for no particular reason other than "it would be cool, i guess" is not only useless but counter-productive. electron offers nothing that isn't already available, and is known to have fancy goals such as "i want my 50 kb of code to take 3 GB of ram while running".

on top of that, deriving any use from electron at all would imply pretty massive refactors for very little reason.

**Comment by AverageComet250** [comment]
I guess I can ditch the electron idea then, but I still think the web page needs a redo and an anti-afk would be really useful, as it avoids connecting to it with impact just to avoid being afk kicked.

I also think the web page authentication system is terrible and would be better off as login first, see time and position after, and uses a username as well as a password, or just your Minecraft account details as that would be more secure in a way. However that would require a hashed or encrypted secrets.json.

**Comment by MrGeorgen** [comment]
yeah the web interface needs some work, some commands are not even available in the web interface. However I won't do this because I'm terrible at frontend dev and I don't that much time anymore. Most stuff I did was around april. But you can make a pull request of course
