### ISSUE TITLE
Closing old issues that seem to be fixed

### ISSUE THREAD

**Issue by AverageComet250** [themoonisacheese/2bored2wait#178]
Plz can we have the old issues that are fixed but not closed closed as this is making it hard to work out what I need to implement in my fork to make this better as I can tell what's implemented and what isn't.

Sorry if I'm making too many issues

**Comment by MrGeorgen** [comment]
>Sorry if I'm making too many issues

no problem, I always welcome new contributions.

Yeah I can close a some issues. The Thing is something people are not replying anymore, but I'll close these

**Comment by MrGeorgen** [comment]
ok I closed many
