### ISSUE TITLE
Stop queuing command

### ISSUE THREAD

**Issue by AverageComet250** [themoonisacheese/2bored2wait#179]
Can someone tell me what the cli equivalent of the stop queuing button on the web UI is as I think it might be why my copy of 2b2w keeps failing after I have to terminate it once.

**Comment by AverageComet250** [comment]
Also I know the `stop` command exists but is that what I'm after

**Comment by YeetyDankEngine** [comment]
`stop` is to stop the queue, not the program

**Comment by AverageComet250** [comment]
Thx for the info

Is there a command to stop the whole program or do I just have to run `ctrl c`

**Comment by MrGeorgen** [comment]
> Thx for the info
> 
> Is there a command to stop the whole program or do I just have to run `ctrl c`

just  use `ctrl c`
