### ISSUE TITLE
error in npm install

### ISSUE THREAD

**Issue by Endersirio** [themoonisacheese/2bored2wait#180]
C:\Users\user>cd Destop
Impossibile trovare il percorso specificato.

C:\Users\user>cd Desktop

C:\Users\user\Desktop>cd 2bored2wait-master

C:\Users\user\Desktop\2bored2wait-master>npm install
npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/zekesonxx/node-yggdrasil.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2021-01-05T15_58_10_306Z-debug.log

**Comment by MrGeorgen** [comment]
install git
