### ISSUE TITLE
minecraft-protocol causing npm install to fail

### ISSUE THREAD

**Issue by KBenster** [themoonisacheese/2bored2wait#182]
After cloning the newest version, and running `npm install`, the program returned an error. This seems to be an error with a package named `axios`, which is a dependency of `minecraft-protocol`. Here is the output of `npm audit`

![image](https://user-images.githubusercontent.com/38230235/103977040-f6c6a300-513d-11eb-8719-1f0a1749e0c0.png)

It seems like this is the only package that is causing problems, and can likely be solved by updating to `0.21.1`. Is there any immediate solution to this?

**Comment by MrGeorgen** [comment]
because it's a xboxlive-auth dependency you should be fine when using a mojang account
