### ISSUE TITLE
I get the error ECONNRESET

### ISSUE THREAD

**Issue by RayBoy113** [themoonisacheese/2bored2wait#187]
After a few minutes in queue I was given this error message:
err Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}
Don't know why this is happening

**Comment by MrGeorgen** [comment]
not an issue of this project. [more information about this error](https://stackoverflow.com/questions/17245881/how-do-i-debug-error-econnreset-in-node-jsl)
