### ISSUE TITLE
Chunk error when joining after 2b2w is in game

### ISSUE THREAD

**Issue by RegenixMC** [themoonisacheese/2bored2wait#191]
When every I join the proxy after it has connected to the game, it lets you fly around and does not load the chunks correctly. I know this has been an issue for a long time but I was wondering if it is possible to fix. I know that you can just go through a portal or go out of render and reload the chunks but this takes a while and is annoying.

**Comment by MrGeorgen** [comment]
I don't know whats causing the issue. sometimes the client displays the chunk if you brake a block
