### ISSUE TITLE
Error when 2b2t restarts

### ISSUE THREAD

**Issue by Galaktax** [themoonisacheese/2bored2wait#194]
Sometimes when 2b2t restarts, I get this long error. It says in it, "listen EADDRINUSE: address already in use 0.0.0.0:25569," but I'm sure I am not using port 25569 for anything else, and I am not running any Minecraft servers. Also, I don't think this would affect anything, but I am running a second 2bored2wait proxy (for another account) on the same computer, using a completely different port. 

Queue is finished
Connection error by 2b2t server. Error message: Error: read ECONNRESET Reconnecting...
Connection reset by 2b2t server. Reconnecting...
Reconnecting...
Reconnecting...
$ events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 0.0.0.0:25569
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at doListen (net.js:1503:7)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Emitted 'error' event on Server instance at:
    at Server.<anonymous> (C:\Users\lando\OneDrive\Desktop\2bored2wait-V2-main-BibleBot\node_modules\minecraft-protocol\src\server.js:45:12)
    at Server.emit (events.js:315:20)
    at emitErrorNT (net.js:1345:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 25569
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 2bored2waitV2@1.0.0 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 2bored2waitV2@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lando\AppData\Roaming\npm-cache\_logs\2021-01-28T07_05_42_513Z-debug.log

**Comment by MrGeorgen** [comment]
yeah the reconnecting is buggy and starts the client and the server twice. I'll drop the reconnecting implementation in favor of PrismarineJS/node-minecraft-protocol/issues/796 when it is done

**Comment by RegenixMC** [comment]
The delay in the auto reconnect is also very low and 2b2t needs a minimum of 30 seconds when auto reconnecting
