### ISSUE TITLE
Issue when using bot with raspberry pi as host

### ISSUE THREAD

**Issue by Biodegradavide** [themoonisacheese/2bored2wait#195]
In raspbery pi the command `npm start` need _sudo_ prefix, when trying to use the discord bot, it doesn't run the command with _sudo_ and it doesn't work in raspberry pi os and ubuntu. Thanks for the support

**Comment by MrGeorgen** [comment]
do you set the port to something below 1024? Please post your error message

**Comment by YeetyDankEngine** [comment]
`cd` out of the 2b2w folder (if required) and execute `sudo 
chown _user_:` Replace _user_ with your user, but keep the colon.

**Comment by Biodegradavide** [comment]
I set the port below 1024, now i've fixed by setting a port higher than 1024
