### ISSUE TITLE
error when npm start pls help

### ISSUE THREAD

**Issue by sup1n** [themoonisacheese/2bored2wait#196]
npm ERR! code 1
npm ERR! path C:\Users\pepij\Desktop\2bored2wait-master
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node main.js

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pepij\AppData\Local\npm-cache\_logs\2021-01-30T16_15_35_426Z-debug.log

**Comment by MrGeorgen** [comment]
is there some error above

**Comment by MrGeorgen** [comment]
I'm closing this because you are not replying
