### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by RegenixMC** [themoonisacheese/2bored2wait#198]
> node main.js

C:\Users\evana\Desktop\2bored2wait-master\main.js:22
        throw("error loading config file:\n" + err);
        ^
error loading config file:
SyntaxError: Unexpected token D in JSON at position 14
(Use `node --trace-uncaught ...` to show where the exception was thrown)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 2bored2wait@1.0.0 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 2bored2wait@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\evana\AppData\Roaming\npm-cache\_logs\2021-01-31T20_32_50_331Z-debug.log

**Comment by RegenixMC** [comment]
I am running windows 10 on my pc btw

**Comment by MrGeorgen** [comment]
syntax error in the config
