### ISSUE TITLE
Add support for telegram bot announcing

### ISSUE THREAD

**Issue by preludium975** [themoonisacheese/2bored2wait#200]
It wouldn't be hard to implement it since using the Telegram Bot API is really simple, create a bot using BotFather, then add the bot to a channel/group.
![image](https://user-images.githubusercontent.com/52859929/106909389-8b520000-6700-11eb-8bf6-31e1728b220f.png)

**Comment by MrGeorgen** [comment]
3 interfaces are many. So I won't be making addional interfaces.
Feel free to open a pr though

**Comment by rob9315** [comment]
We won't implement this ourselves, if you are still interested as MrGeorgen said, open a pr it will likely be accepted.
