### ISSUE TITLE
Problem when trying to start the queue bot

### ISSUE THREAD

**Issue by Biodegradavide** [themoonisacheese/2bored2wait#202]
Hi! I'm using 2b2w since 2 week ago (thanks for this great software), but now I'm having a problem when I try to start the queue. 
It looks like the 2b2t.org address isn't reachable by Windows (If I try to ping the same address windows says that he cant find it), but I still can connect to the server via minecraft. 
The error I get from 2b2w:
```
$ start
Queue is starting up
Connection error by 2b2t server. Error message: Error: getaddrinfo ENOTFOUND 2b2t.org Reconnecting...
Connection reset by 2b2t server. Reconnecting...
Reconnecting...
Reconnecting...
$
```
And It freeze with that. I hope you can help me! 
![Cattura](https://user-images.githubusercontent.com/61192921/106957230-0da9e680-6738-11eb-9e20-fb127984c8b9.PNG)

**Comment by MrGeorgen** [comment]
I also can not ping 2b2t. But connecting in minecraft does work

**Comment by Biodegradavide** [comment]
@MrGeorgen Ok, then it's definitely a 2b2t problem

**Comment by legendofmiracles** [comment]
I don't think that this is a 2b2t problem. I also have this issue, and i can connect fine manually.

**Comment by Biodegradavide** [comment]
Did you changed the "2b2t.org" address in config.json? I'm using other ports than 25565 and 80 but I don't think thats the problem.

**Comment by legendofmiracles** [comment]
connect.2b2t.org seems to work better..

**Comment by Biodegradavide** [comment]
that address actually worked, thanks a lot!

**Comment by MrGeorgen** [comment]
ok I can change the default address
