### ISSUE TITLE
Fix for random closing of the program on raspberry pi

### ISSUE THREAD

**Issue by Biodegradavide** [themoonisacheese/2bored2wait#203]
Hi, I'm using a raspberry pi 4 with raspberry pi os lite.
I've noticed that the program randomly closes after a while.
The fix to this problem is to run main.js in background with something like https://github.com/foreversd/forever this.
I hope to have contributed in my small way.

**Comment by ChillerDragon** [comment]
wow the url is a trap :D

**Comment by Biodegradavide** [comment]
@ChillerDragon fixed, Sorry but I'm pretty new to Github. :)
