### ISSUE TITLE
Npm Start issue

### ISSUE THREAD

**Issue by Davido12** [themoonisacheese/2bored2wait#205]
excuse me but when i type npm start it shows me this
![Node js command prompt](https://user-images.githubusercontent.com/78734720/107216827-fb6cc880-6a15-11eb-9398-75f366af2098.png)

**Comment by Davido12** [comment]
Could you help

**Comment by Davido12** [comment]
@themoonisacheese

**Comment by Biodegradavide** [comment]
Have you installed the latest version of node? Which tutorial did you follow (video or text?)

**Comment by Davido12** [comment]
I got that solved but i got abother issue

**Comment by Davido12** [comment]
It is saying my account credentials are invalid and its not working

**Comment by MrGeorgen** [comment]
> It is saying my account credentials are invalid and its not working

sometimes if you spamm the auth server you temporialy banned

**Comment by Davido12** [comment]
Wdym

**Comment by Biodegradavide** [comment]
> Wdym

If you do too many login attempts in a little period, the authentication server will temporary block you.

**Comment by Davido12** [comment]
That doesnt explain why it says my account credentials are invalid

**Comment by MrGeorgen** [comment]
> That doesnt explain why it says my account credentials are invalid

if you are blocked the server will say that your credentials are invalid

**Comment by Biodegradavide** [comment]
Are you using a Mojang or Microsoft account tor playing Minecraft?
