### ISSUE TITLE
Make a discord sever for this

### ISSUE THREAD

**Issue by cristiioan** [themoonisacheese/2bored2wait#206]

**Comment by themoonisacheese** [comment]
what would that achieve?

**Comment by cristiioan** [comment]
better communication and it will be easy to post updates

**Comment by MrGeorgen** [comment]
> better communication and it will be easy to post updates

updates are posted through commits

**Comment by cristiioan** [comment]
I'm meaning that when you make a major commit you can easy ping @evryoane. Can you contact me at {Cristiioan}#8717 @MrGeorgen?

**Comment by MrGeorgen** [comment]
to get update notifications you could use the github commit rss feed.
I also don't want to write a message in discord after an update.
a bot could be used, but in that a discord server is useless because anyone
could use the themsleves
