### ISSUE TITLE
Problem with 0.0.0.0

### ISSUE THREAD

**Issue by Villygrimm** [themoonisacheese/2bored2wait#207]
$ events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 0.0.0.0:25565
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at doListen (net.js:1503:7)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Emitted 'error' event on Server instance at:
    at Server.<anonymous> (C:\Users\Zver\Desktop\2bored2wait-master\node_modules\minecraft-protocol\src\server.js:44:12)
    at Server.emit (events.js:315:20)
    at emitErrorNT (net.js:1345:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 25565
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 2bored2wait@1.0.0 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 2bored2wait@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Zver\AppData\Roaming\npm-cache\_logs\2021-02-09T15_29_54_766Z-debug.log

**Comment by Villygrimm** [comment]
Here's the problem

**Comment by cristiioan** [comment]
How you get it?

**Comment by cristiioan** [comment]
Can you send the config file?

**Comment by Villygrimm** [comment]
I do not know how to attach the file I only know how to attach the video and github format

**Comment by Villygrimm** [comment]
I can send you something in the file

**Comment by Villygrimm** [comment]
{"discordBot": false,"webserver": true,"ports":{"minecraft":25565,"web":9080},"openBrowserOnStart":true,"password":"","MCversion":"1.12.2","logging":true,"reconnect":{"onError":true,"notConnectedQueueEnd":false},"minecraftserver":{"hostname":"twerion.net","is2b2t":false,"port":25565,"version":"1.12.2","onlinemode":false,"username":"lol"},"notification":{"enabled":true,"queuePlace":20},"userStatus":true,"antiAntiAFK":true,"chunkCaching":true,"joinOnStart":true,"whitelist":false}

here's what's in the file

**Comment by MrGeorgen** [comment]
do you have minecraft server running on port 25565?

**Comment by MrGeorgen** [comment]
> {"discordBot": false,"webserver": true,"ports":{"minecraft":25565,"web":8080},"openBrowserOnStart":true,"password""","MCversion":"1.12.2","logging":true,"reconnect":{"onError":true,"notConnectedQueueEnd":false},"minecraftserver":{"hostname":"twerion.net","is2b2t":false,"port":25565,"version":"1.12.2","onlinemode":false,"username":"lol"},"notification":{"enabled":true,"queuePlace":20},"userStatus":true,"antiAntiAFK":true,"chunkCaching":true,"joinOnStart":true,"whitelist":false}
> 
> here's what's in the file

you also have the config of the test script which you most likly don't want
because it does not join 2b2t

**Comment by cristiioan** [comment]
Lock like node is making the sever on ip 0.0.0.0 with is not possible to route. Is an invalid ip. https://en.wikipedia.org/wiki/0.0.0.0

**Comment by Villygrimm** [comment]
> у вас есть сервер minecraft, работающий на порту 25565?
yes but it's not running

**Comment by MrGeorgen** [comment]
> Lock like node is making the sever on ip 0.0.0.0 with is not possible to route. Is an invalid ip. https://en.wikipedia.org/wiki/0.0.0.0

listen on 0.0.0.0 means it listens on all ip addresses
