### ISSUE TITLE
[Bug] ETA displaying incorrectly

### ISSUE THREAD

**Issue by Kore-Development** [themoonisacheese/2bored2wait#209]
Earlier the ETA was about 19 hours but 2b2w saw it as about 9 hours. I assume it would be the same for any ETA 10 hours or above.

**Comment by Kore-Development** [comment]
It showed 19 in the tab list.

**Comment by MrGeorgen** [comment]
it does not show ETA from 2b2t. the ETA is calculated based on position in the
queue. This results in better ETA most of the time.
I can add an info on README because it is not obvious
