### ISSUE TITLE
Can't cast fishing rod

### ISSUE THREAD

**Issue by umutozbay6** [themoonisacheese/2bored2wait#21]
I've been autofishing and decided to use the proxy. When i log back in i have the fishing rod in my active hotbar slot. I can't right click to use the fishing rod.
I can use bows and eat food. I tried using other fishing rods but still no luck. I can't cast them either.

**Comment by themoonisacheese** [comment]
I have a feeling that's related to #2 . will investigate.

**Comment by wylie39** [comment]
Was this fixed with #51 or is it still a problem?

**Comment by AverageComet250** [comment]
I think this needs closing
