### ISSUE TITLE
Reconnect problem

### ISSUE THREAD

**Issue by Gusarich** [themoonisacheese/2bored2wait#210]
I set up 2b2w on dedicated server so I can not lost queue even when I have my computer off or Internet problems. 

I thought if 2b2w running on remote server, it will be ok to reconnect from my computer any time. 
In queue lobby it works fine, I can reconnect and I won't lose my position
But then I joined game, left from spawn, went long distance, build a base, and then tried reconnect. After connecting back I saw myself in creative mode (its just visual), and map have returned to some state that was like hour before I reconected. 
Im not able to do any thing, even break a block or jump :(

It will be best tool for 2b2t if you fix it

**Comment by cristiioan** [comment]
Lock like a cache issue

**Comment by Gusarich** [comment]
> Lock like a cache issue

I did few more tests
When I start & stop 2b2w through CLI it also glitching.
When I close comand line and start again by `npm start` glitch dissapears.

**Comment by MrGeorgen** [comment]
2b2w only resends chunk packets. However if a is broken, the new block is not
is not updated in the chunk cache. The plan is use https://github.com/Rob9315/mcproxy as a library for caching. Far more things like time are also properly cached. However I did not test it yet. I just read the code.

>When I start & stop 2b2w through CLI it also glitching.
When I close comand line and start again by npm start glitch dissapears.

Didn't notice that. I checked the code and saw that the cache is not delected
after a disconnect

**Comment by Gusarich** [comment]
> 2b2w only resends chunk packets. However if a is broken, the new block is not
> is not updated in the chunk cache. The plan is use https://github.com/Rob9315/mcproxy as a library for caching. Far more things like time are also properly cached. However I did not test it yet. I just read the code.
> 
> > When I start & stop 2b2w through CLI it also glitching.
> > When I close comand line and start again by npm start glitch dissapears.
> 
> Didn't notice that. I checked the code and saw that the cache is not delected
> after a disconnect

So is it fixed now since you added deleting cache in Code?

**Comment by MrGeorgen** [comment]
> > 2b2w only resends chunk packets. However if a is broken, the new block is not
> > is not updated in the chunk cache. The plan is use https://github.com/Rob9315/mcproxy as a library for caching. Far more things like time are also properly cached. However I did not test it yet. I just read the code.
> > > When I start & stop 2b2w through CLI it also glitching.
> > > When I close comand line and start again by npm start glitch dissapears.
> > 
> > 
> > Didn't notice that. I checked the code and saw that the cache is not delected
> > after a disconnect
> 
> So is it fixed now since you added deleting cache in Code?

I think so, but I didn't test it on 2b2t

**Comment by Gusarich** [comment]
> > > 2b2w only resends chunk packets. However if a is broken, the new block is not
> > > is not updated in the chunk cache. The plan is use https://github.com/Rob9315/mcproxy as a library for caching. Far more things like time are also properly cached. However I did not test it yet. I just read the code.
> > > > When I start & stop 2b2w through CLI it also glitching.
> > > > When I close comand line and start again by npm start glitch dissapears.
> > > 
> > > 
> > > Didn't notice that. I checked the code and saw that the cache is not delected
> > > after a disconnect
> > 
> > 
> > So is it fixed now since you added deleting cache in Code?
> 
> I think so, but I didn't test it on 2b2t

Just checked
Bug isn't fixed but it seems less glitchy now.
Before I was seeing myself like in creative mode and I was unable to walk and do other things
But now I see myself not in creative and I seems like able to walk and jump, but I still can't do anything.

Here is screenshot https://imgur.com/a/RM2O4fM

**Comment by Gusarich** [comment]
Bug is still there, but I can move now
Bug fixes when I enter portal or kill myself

**Comment by Gusarich** [comment]
I believe it can be fixed by adding same clearCache call when player connect or disconnect from proxy server, or something like that.

**Comment by MrGeorgen** [comment]
> I believe it can be fixed by adding same clearCache call when player connect or disconnect from proxy server, or something like that.

that would make the cache completly unless. You would fly in a empty world
