### ISSUE TITLE
Ability to specify host

### ISSUE THREAD

**Issue by zax2002** [themoonisacheese/2bored2wait#211]
I use another proxy between Minecraft and 2b2w. It would be nice to be able to run a 2b2w Minecraft server on localhost, for example

**Comment by MrGeorgen** [comment]
set minecraftserver.hostname in the config

**Comment by MrGeorgen** [comment]
or you mean the address 2b2w listens on

**Comment by zax2002** [comment]
> or you mean the address 2b2w listens on

Yes, exactly
