### ISSUE TITLE
Start Queue bug

### ISSUE THREAD

**Issue by zax2002** [themoonisacheese/2bored2wait#212]
When you click the "Start queuing" button in the web interface, it turns red, but after a second it turns green again. Also, when updating the page, the button says "Start queuing", despite the fact that `/update` returns `"isInQueue": true`.
The second part of the bug is that when you click on this button second time (sending a request `/start` while already in queue), the proxy crashes with the error `EADDRINUSE`, including disconnecting from 2b2t

<details><summary>Error</summary>

```javascript
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 127.0.0.1:1337
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1503:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:8)
Emitted 'error' event on Server instance at:
    at Server.<anonymous> (/root/2b2t/2bored2wait/node_modules/minecraft-protocol/src/server.js:44:12)
    at Server.emit (events.js:315:20)
    at emitErrorNT (net.js:1345:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 1337
}
```

</details>

<details><summary>Config</summary>

```json5
{
    "discordBot": false,
    "webserver": true,
    "ports": {
       "minecraft": 1337, // port for the proxy server
       "web": 2337
    },
    "address": { // address 2b2w listens on
        "minecraft": "localhost",
        "web": "0.0.0.0"
    },
    "openBrowserOnStart": false,
    "password": "i found someone's enderchest, he has the same items as me, threw them into lava", // password for the webinterface
    "MCversion": "1.12.2",
    "logging": true, // log errors and queue place
    "reconnect": {
        "onError": true, // reconnect on error or if 2b2t kicks you
        "notConnectedQueueEnd": true // restart the queue if you are not connect at the end of it
    },
    "minecraftserver": { // the server you want to connect. Make not much sense to change it, was just added for development purpose
        "hostname": "connect.2b2t.org",
        "is2b2t": true, // to allow proxies inbetween 2bored2wait and 2b2t
        "port": 25565,
        "version": "1.12.2",
        "onlinemode": true,
        "username": "zax2002" // the username to use if onlinemode is false
    },
    "notification": { // sends a message via discord if the place in the queue reaches the specified number
        "enabled": false, // you must send the bot a message once.
        "queuePlace": 20
    },
    "userStatus": false, // show username in discord bot status, in case of alts
    "antiAntiAFK": true, // to bypass antiAFK plugins
    "chunkCaching": true,
    "joinOnStart": false, // join the server when 2b2w is started
    "whitelist": false // only let the same minecraft account join 2b2w as the one connected to 2b2t
}
```
</details>

<details><summary>Screenshots</summary>

not queuing
![image](https://user-images.githubusercontent.com/25406324/108397852-78bfe680-7229-11eb-83bd-9eaf2ad11ebe.png)
clicked first time
![image](https://user-images.githubusercontent.com/25406324/108397748-5928be00-7229-11eb-99b4-e07d4bcf3ae3.png)
clicked second time
![image](https://user-images.githubusercontent.com/25406324/108398001-9b51ff80-7229-11eb-9ce5-b741dc646fc4.png)

<details>

**Comment by zax2002** [comment]
I think it's this bug #207, but its true cause was not found there

**Comment by MrGeorgen** [comment]
The queue is started twice because the button does not update correctly

**Comment by zax2002** [comment]
Yes, this is the bug

**Comment by MrGeorgen** [comment]
the variable name the client checks is 'inQueue' but the server returns it as
'IsInQueue'

**Comment by zax2002** [comment]
Also, I think it's not very good, as for the API, that a repeated call to `/start` causes a crash

**Comment by MrGeorgen** [comment]
> Also, I think it's not very good, as for the API, that a repeated call to /start causes a crash

yeah using the start command twice also causes a crash

**Comment by plebeo** [comment]
So are you going to fix this? It's really annoying @MrGeorgen

**Comment by MrGeorgen** [comment]
> So are you going to fix this? It's really annoying @MrGeorgen, just to know.

the webinterface is fixed. the api however not
