### ISSUE TITLE
Can 2b2w join the world by itself?

### ISSUE THREAD

**Issue by zax2002** [themoonisacheese/2bored2wait#215]
Can 2b2w join the world by itself if I am not connected to it from Minecraft at the end of the queue? I just got `Connection reset by 2b2t server` three times already, after `P: 1`, when I was not connected to 2b2w from Minecraft, I don't think it's an accident

**Comment by MrGeorgen** [comment]
unless you the `reconnect.notConnectQueueEnd` set it joins the world.
But the 2b2t anti-afk will kick you because  the 2b2w anti-anti-afk is
currently broken #192

**Comment by zax2002** [comment]
Thanks, for some reason I thought that this parameter is responsible for something else
