### ISSUE TITLE
I keep getting this issue

### ISSUE THREAD

**Issue by ISlipoff** [themoonisacheese/2bored2wait#218]
C:\Users\<REDACTED>\Desktop\2bored2wait-master>node main.js

C:\Users\<REDACTED>\Desktop\2bored2wait-master\main.js:25
        throw("error loading config file:\n" + err);
        ^
error loading config file:
SyntaxError: Unexpected token D in JSON at position 14
(Use `node --trace-uncaught ...` to show where the exception was thrown)

How do I fix this?

**Comment by MrGeorgen** [comment]
invalid json syntax in your config

**Comment by ISlipoff** [comment]
Am I supposed to leave this?

{
    "discordBot": DISCORDBOT_FLAG,
    "webserver": WEBSERVER_FLAG,

**Comment by ISlipoff** [comment]
Here is my current config:

{
    "discordBot": DISCORDBOT_FLAG,
    "webserver": WEBSERVER_FLAG,
    "ports":{
        "minecraft":25565, // port for the proxy server
       "web":80
    },
    "address":{ // address 2b2w listens on
    	"minecraft": "0.0.0.0",
	"web": "0.0.0.0"
    },
    "openBrowserOnStart": false,
    "password":"", // password for the webinterface
    "MCversion":"1.12.2",
    "logging": true, // log errors and queue place
    "reconnect": {
        "onError": true, // reconnect on error or if 2b2t kicks you
        "notConnectedQueueEnd": true
    },
    "minecraftserver": { // the server you want to connect. Make not much sense to change it, was just added for development purpose
        "hostname": "2b2t.org",
	"is2b2t": true, // to allow proxies inbetween 2bored2wait and 2b2t
        "port": 25565,
        "version": "1.12.2",
        "onlinemode": true,
        "username"<Redacted>"
    },
    "notification": { // sends a message via discord if the place in the queue reaches the specified number
        "enabled": true, // you must send the bot a message once.
        "queuePlace": 20
    },
    "userStatus": true, // show username in discord bot status, in case of alts
    "antiAntiAFK": true, // to bypass antiAFK plugins
    "joinOnStart": true, // join the server when 2b2w is started
    "whitelist": false
}

**Comment by zax2002** [comment]
Replace DISCORDBOT_FLAG and WEBSERVER_FLAG with `true` or `false`, depending on whether you want to enable discord notifications and webserver

**Comment by ISlipoff** [comment]
I'm now getting this issue

$     C:\Users\<Redacted>\Desktop\2bored2wait-master\main.js:304
        if (config.discordBot) dc.user.setActivity(string);
                                       ^

TypeError: Cannot read property 'setActivity' of null
    at activity (C:\Users\<Redacted>\Desktop\2bored2wait-master\main.js:304:33)
    at join (C:\Users\<Redacted>\Desktop\2bored2wait-master\main.js:157:2)
    at Timeout.startQueuing [as _onTimeout] (C:\Users\<Redacted>\Desktop\2bored2wait-master\main.js:148:2)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

**Comment by zax2002** [comment]
Are you specified `BotToken`? Do you really need discord notifications?

**Comment by ISlipoff** [comment]
Yes, I have got Bot token specified I have just disabled Discord Notifications because I enabled them by accident. I am still getting the error.

**Comment by zax2002** [comment]
Exactly the same error?

**Comment by ISlipoff** [comment]
I am getting this now:

C:\Users\saw12\Desktop\2bored2wait-master>node main.js
Connection error by 2b2t server. Error message: Error: Invalid credentials. Invalid username or password. Reconnecting...
Reconnecting...
Connection error by 2b2t server. Error message: Error: Invalid credentials. Invalid username or password. Reconnecting...
Reconnecting...
Connection error by 2b2t server. Error message: Error: Invalid credentials. Invalid username or password. Reconnecting...
Reconnecting...
Connection error by 2b2t server. Error message: Error: Invalid credentials. Invalid username or password. Reconnecting...
Reconnecting...
Connection error by 2b2t server. Error message: Error: Invalid credentials. Invalid username or password. Reconnecting...
Reconnecting...
Connection error by 2b2t server. Error message: Error: Invalid credentials. Invalid username or password. Reconnecting...
Reconnecting...
Connection error by 2b2t server. Error message: Error: Invalid credentials. Invalid username or password. Reconnecting...



I have specified everything correctly like MC Credentials etc

**Comment by ISlipoff** [comment]
I'm now getting this 

Connection error by 2b2t server. Error message: Error: Invalid credentials. Invalid username or password. Reconnecting...
Reconnecting...
Connection error by 2b2t server. Error message: Error: Invalid credentials. Invalid username or password. Reconnecting...
Reconnecting...
Connection error by 2b2t server. Error message: Error: Invalid credentials. Invalid username or password. Reconnecting...
Reconnecting...
Connection error by 2b2t server. Error message: Error: Invalid credentials. Invalid username or password. Reconnecting...
Reconnecting...
Connection error by 2b2t server. Error message: Error: Invalid credentials. Invalid username or password. Reconnecting...
Reconnecting...
Connection error by 2b2t server. Error message: Error: Invalid credentials. Invalid username or password. Reconnecting...
Reconnecting...
Connection error by 2b2t server. Error message: Error: Invalid credentials. Invalid username or password. Reconnecting...
$ ^C

I have specified everything correctly

**Comment by ISlipoff** [comment]
Oh nevermind I didn't input the password

**Comment by ISlipoff** [comment]
So it is now fixed. 

 God I can't believe I missed out on that password field *Facepalm*
