### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by CoolCosmo** [themoonisacheese/2bored2wait#220]
[2021-02-24T02_39_02_771Z-debug.log](https://github.com/themoonisacheese/2bored2wait/files/6033002/2021-02-24T02_39_02_771Z-debug.log)
This is the log of it not working.
I'm trying to use this with version 1.12.2-Impact_4.9.1

**Comment by zax2002** [comment]
Make sure the `C:\Users\Spencer\Desktop\2bored2wait-master\package.json` file exists

**Comment by CoolCosmo** [comment]
![package json proof](https://user-images.githubusercontent.com/79555279/108981691-d4cba600-7641-11eb-88b9-1ec542a3c7bf.PNG)
That's what I thought it was saying the problem was, but as you can see, it's there.

**Comment by zax2002** [comment]
Did you run `npm install` before `npm start`?  There is no `node_packages` folder in your screenshot

**Comment by CoolCosmo** [comment]
Yes I did.  However, I think I might have changed the examples before I installed, where in the youtube video they installed then change the example.  This is the only thing that I think I might have done differently from the tutorial.

**Comment by zax2002** [comment]
Not sure if it can help, but try `npm init`. Also make sure you are in `2bored2wait-master` directory in terminal before running npm

**Comment by AgressiveBoy123** [comment]
I'm having the same issue. 
[2021-02-28T18_04_40_246Z-debug.log](https://github.com/themoonisacheese/2bored2wait/files/6057443/2021-02-28T18_04_40_246Z-debug.log)
I can't find any solution for this error. I literally tried everything but it doesn't work.

**Comment by zax2002** [comment]
> I'm having the same issue.
> [2021-02-28T18_04_40_246Z-debug.log](https://github.com/themoonisacheese/2bored2wait/files/6057443/2021-02-28T18_04_40_246Z-debug.log)
> I can't find any solution to this error. I literally tried everything but it doesn't work.

You have a completely different error. Run just `node main.js`. The problem is in the `main.js` file. Maybe you didn't set discord bot and webserver flags in the config
