### ISSUE TITLE
connecting to the 2b2t via localhost doesn't work

### ISSUE THREAD

**Issue by Diregamer1** [themoonisacheese/2bored2wait#221]
I tried testing out joining into the queue via localhost like in the video linked. it ended up kicking me out with the message "io. netty.channel. AbstractChannel$AnnotatedConnectException: Connection refused: no further information". here is my config as during the time of the attempt to connect. 
`{
    "discordBot": false,
    "webserver": true,
    "ports":{
        "minecraft":25565, // port for the proxy server
       "web":8080
    },
    "address":{ // address 2b2w listens on
    	"minecraft": "192.168.1.84",
	"web": "127.0.0.1"
    },
    "openBrowserOnStart": true,
    "password":"GarriNTheo", // password for the webinterface
    "MCversion":"1.12.2",
    "logging": true, // log errors and queue place
    "reconnect": {
        "onError": true, // reconnect on error or if 2b2t kicks you
        "notConnectedQueueEnd": false // restart the queue if you are not connect at the end of it
    },
    "minecraftserver": { // the server you want to connect. Make not much sense to change it, was just added for development purpose
        "hostname": "connect.2b2t.org",
	"is2b2t": true, // to allow proxies inbetween 2bored2wait and 2b2t
        "port": 25565,
        "version": "1.12.2",
        "onlinemode": true,
        "username": "lol" // the username to use if onlinemode is false
    },
    "notification": { // sends a message via discord if the place in the queue reaches the specified number
        "enabled": true, // you must send the bot a message once.
        "queuePlace": 20
    },
    "userStatus": true, // show username in discord bot status, in case of alts
    "antiAntiAFK": true, // to bypass antiAFK plugins
    "joinOnStart": false, // join the server when 2b2w is started
    "whitelist": false // only let the same minecraft account join 2b2w as the one connected to 2b2t
}`
anything to help?

**Comment by Diregamer1** [comment]
the issue seems to be that you need to connect with the same ip as the minecraft address in the address section. in case other people are going to go closed issue surfing like i did.

**Comment by MrGeorgen** [comment]
if you set the address to 0.0.0.0 you can connect via all IPs
