### ISSUE TITLE
Adding a personalized server icon

### ISSUE THREAD

**Issue by plebeo** [themoonisacheese/2bored2wait#223]
I suggest this as a useful enhancement, it'll be easier to recognize the server in the server list and also will be cooler to see.

Anyway, as this isn't the most important goal to achieve at the moment, if you can give me a hint about how to do it I'll do it by myself.

**Comment by MrGeorgen** [comment]
minecraft-protocol does not support server icons out of the box.
However as you can see in the [documentation](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/docs/API.md) you can create custom ping responses.
The format of the response you can see [here](https://wiki.vg/Server_List_Ping).
You create pr here but you could also consider making a pr a
minecraft-protocol as this could be usefull to other users of the library as
well.

**Comment by plebeo** [comment]
Thank you.
