### ISSUE TITLE
install dependency error

### ISSUE THREAD

**Issue by namanhishere** [themoonisacheese/2bored2wait#226]
![image](https://user-images.githubusercontent.com/53372786/109483793-3f516b80-7ab2-11eb-95e1-ae0a6164d301.png)
I have a problem while installing the dependency "mcproxy". I hack with the link in the package.json and the project still alive. maybe the problem caused by I type something in package.json but when I try to clone the package.json from the github, the problem still here
The installing log
[2021-03-01T10_15_41_729Z-debug.log](https://github.com/themoonisacheese/2bored2wait/files/6060842/2021-03-01T10_15_41_729Z-debug.log)

P/s: In the past, I uses 2b2w as queue waiting system, but when I stay at queue 1, I cannot connect to 2b2t, the Player Table did not show my name also

**Comment by MrGeorgen** [comment]
i can not reproduce the error

**Comment by MrGeorgen** [comment]
you have to install git
