### ISSUE TITLE
Support for webhook

### ISSUE THREAD

**Issue by Doogie13** [themoonisacheese/2bored2wait#229]
Discord webhooks are easier to use than bots for the user so why not make the user just input a webhook and recieve messages via that. Obviously you cant control 2b2w with it but you can with the webserver.

**Comment by MrGeorgen** [comment]
I guess the webserver must be availbe for the public then.
However without tls and a strong password this would not be secure

**Comment by rob9315** [comment]
i like this idea, sorry for it being overlooked for so long

**Comment by cristiioan** [comment]
@rob9315 While it is a good idea, as @MrGeorgen said there is need for a good security
