### ISSUE TITLE
error

### ISSUE THREAD

**Issue by tuvgugukgukz** [themoonisacheese/2bored2wait#232]
im getting this error:
internal/modules/cjs/loader.js:1017
  throw err;
  ^

Error: Cannot find module 'C:\Users\Boros Soma\discordBot.js'
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1014:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:884:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}

**Comment by tuvgugukgukz** [comment]
im using windows powershell

**Comment by wylie39** [comment]
Did you run `npm start`?

**Comment by tuvgugukgukz** [comment]
is this normal? PS C:\Users\Boros Soma> npm install
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\Boros Soma\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Boros Soma\package.json'
npm WARN Boros Soma No description
npm WARN Boros Soma No repository field.
npm WARN Boros Soma No README data
npm WARN Boros Soma No license field.

up to date in 1.361s
found 0 vulnerabilities

**Comment by wylie39** [comment]
are you in the folder that you downloaded?

**Comment by tuvgugukgukz** [comment]
what folder?

**Comment by wylie39** [comment]
take a look at this video: https://www.youtube.com/watch?v=oWeCmZNYAW4

**Comment by tuvgugukgukz** [comment]
[2021-02-24T02_39_02_771Z-debug.log](https://github.com/themoonisacheese/2bored2wait/files/6134640/2021-02-24T02_39_02_771Z-debug.log)
im getting this

**Comment by tuvgugukgukz** [comment]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.11
3 info using node@v14.16.0
4 verbose stack Error: ENOENT: no such file or directory, open 'C:\Users\Spencer\Desktop\2bored2wait-master\package.json'
5 verbose cwd C:\Users\Spencer\Desktop\2bored2wait-master
6 verbose Windows_NT 10.0.19042
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 verbose node v14.16.0
9 verbose npm  v6.14.11
10 error code ENOENT
11 error syscall open
12 error path C:\Users\Spencer\Desktop\2bored2wait-master\package.json
13 error errno -4058
14 error enoent ENOENT: no such file or directory, open 'C:\Users\Spencer\Desktop\2bored2wait-master\package.json'
15 error enoent This is related to npm not being able to find a file.
16 verbose exit [ -4058, true ]

**Comment by MrGeorgen** [comment]
does the package.json exits?

**Comment by tuvgugukgukz** [comment]
yes
