### ISSUE TITLE
help

### ISSUE THREAD

**Issue by tuvgugukgukz** [themoonisacheese/2bored2wait#233]
[2021-03-13T08_41_03_267Z-debug.log](https://github.com/themoonisacheese/2bored2wait/files/6136371/2021-03-13T08_41_03_267Z-debug.log)
pls help

**Comment by czho** [comment]
Making multiple issues is not going to get you helped faster, with that said you are using a fork of 2b2w called 2lazy2wait that was made to add discord bot functionality, this has since been added to normal 2b2w. I suggest you follow this guide [here](https://www.youtube.com/watch?v=oWeCmZNYAW4).

**Comment by MrGeorgen** [comment]
>Making multiple issues is not going to get you helped faster, with that said you are using a fork of 2b2w called 2lazy2wait that was made to add discord bot functionality, this has since been added to normal 2b2w. I suggest you follow this guide here.

yeah that causes 2lazy2wait to break. it also is not maintained anymore
