### ISSUE TITLE
npm start err

### ISSUE THREAD

**Issue by nordicator** [themoonisacheese/2bored2wait#235]
whenever i do npm start this happens:

> 2bored2wait@1.0.0 start C:\Users\ayaan\Desktop\2bored2wait-master
> node main.js

C:\Users\ayaan\Desktop\2bored2wait-master\main.js:25
        throw("error loading config file:\n" + err);
        ^
error loading config file:
SyntaxError: Unexpected token M in JSON at position 57
(Use `node --trace-uncaught ...` to show where the exception was thrown)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 2bored2wait@1.0.0 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 2bored2wait@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ayaan\AppData\Roaming\npm-cache\_logs\2021-03-19T14_03_08_830Z-debug.log

**Comment by nordicator** [comment]
pls help

**Comment by wylie39** [comment]
it looks like a problem with your config file. can you post it?

**Comment by nordicator** [comment]
{
    "discordBot": true,
    "webserver": true,
    "ports":{
        "minecraft":MINECRAFT_PROXY_PORT, // port for the proxy server
       "web":8080
    },
    "address":{ // address 2b2w listens on. if you leave it on 0.0.0.0 you can via all IPs
    	"minecraft": "0.0.0.0",
	"web": "0.0.0.0"
    },
    "openBrowserOnStart": false,
    "password":"", // password for the webinterface
    "MCversion":"1.12.2",
    "logging": true, // log errors and queue place
    "reconnect": {
        "onError": true, // reconnect on error or if 2b2t kicks you
        "notConnectedQueueEnd": false // restart the queue if you are not connect at the end of it
    },
    "minecraftserver": { // the server you want to connect. Make not much sense to change it, was just added for development purpose
        "hostname": "connect.2b2t.org",
	"is2b2t": true, // to allow proxies inbetween 2bored2wait and 2b2t
        "port": 25565,
        "version": "1.12.2",
        "onlinemode": true,
        "username": "lol" // the username to use if onlinemode is false
    },
    "notification": { // sends a message via discord if the place in the queue reaches the specified number
        "enabled": true, // you must send the bot a message once.
        "queuePlace": 20
    },
    "userStatus": true, // show username in discord bot status, in case of alts
    "antiAntiAFK": true, // to bypass antiAFK plugins
    "joinOnStart": false, // join the server when 2b2w is started
    "whitelist": false // only let the same minecraft account join 2b2w as the one connected to 2b2t
}

**Comment by nordicator** [comment]
i also want to use a discord bot i put the token in secrets.json

**Comment by nordicator** [comment]
kk
lemme do rn

**Comment by nordicator** [comment]
how do i make discord bot onlline?

**Comment by nordicator** [comment]
now it shows a money sign

**Comment by nordicator** [comment]
nvm it works now thx so much

**Comment by nordicator** [comment]
how do i put the server in my server list

**Comment by nordicator** [comment]
nvm i got it
