### ISSUE TITLE
SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by Qbox683** [themoonisacheese/2bored2wait#236]
[2021-03-13T08_41_03_267Z-debug.log](https://github.com/themoonisacheese/2bored2wait/files/6200250/2021-03-13T08_41_03_267Z-debug.log) for full log

**Comment by czho** [comment]
Two things I see, first, don't use 2lazy2wait, its an old separate fork made to add discord bot to 2b2w, this has been added to 2b2w, 2lazy2wait is now broken and has a bunch of issues. You can find the download for 2bored2wait at [https://github.com/themoonisacheese/2bored2wait/archive/refs/heads/master.zip](url). Second, update your node version with `npm i node@15` in cmd in the same folder as 2b2w.
