### ISSUE TITLE
Im getting some error that i dont understand when trying to npm install

### ISSUE THREAD

**Issue by onayB09** [themoonisacheese/2bored2wait#239]
Hello. Im Getting Error When Trying To npm install. Heres a screenshot.
![image](https://user-images.githubusercontent.com/53120690/112752345-5add6280-8fdb-11eb-811f-92257727fe83.png)
And heres the debug.log
[2021-03-28T12_39_18_778Z-debug.log](https://github.com/themoonisacheese/2bored2wait/files/6217302/2021-03-28T12_39_18_778Z-debug.log)
Thanks İf Someone Helps Me

**Comment by czho** [comment]
Install git here: [https://git-scm.com/downloads](url).

**Comment by onayB09** [comment]
Thank You, Finaly I can wait on queue in this program

**Comment by onayB09** [comment]
I installed it and its worked but now im getting a different error
![image](https://user-images.githubusercontent.com/53120690/112761306-5b89ef00-9003-11eb-920b-e73dbb03905e.png)

**Comment by czho** [comment]
you have to make a config file, copy config.example.json into config.json and modify it so it works.

**Comment by onayB09** [comment]
Do you know what Discord_flag means, error comes in this line
![image](https://user-images.githubusercontent.com/53120690/112793701-6ded4280-906e-11eb-9d10-93eee8cdb608.png)

**Comment by onayB09** [comment]
Making discordBot and webserver true solved the problem. thanks you.
