### ISSUE TITLE
I have a problem after npm start

### ISSUE THREAD

**Issue by 000-whoami-000** [themoonisacheese/2bored2wait#242]
![Screenshot 2021-04-01 122720](https://user-images.githubusercontent.com/48528416/113273786-aa76a380-92e5-11eb-95e1-d4d22c7bae02.png)
![Screenshot 2021-04-01 122643](https://user-images.githubusercontent.com/48528416/113273789-ab0f3a00-92e5-11eb-942c-e3dd38b02275.png)

Could u halp <3

**Comment by 000-whoami-000** [comment]
![Screenshot 2021-04-01 125140](https://user-images.githubusercontent.com/48528416/113277089-11e22280-92e9-11eb-9c14-10b9064eeae0.png)

**Comment by 000-whoami-000** [comment]
![Screenshot 2021-04-01 125341](https://user-images.githubusercontent.com/48528416/113277347-4c4bbf80-92e9-11eb-9914-ec59f5a561dd.png)

**Comment by 0x0bedlag0x0** [comment]
yhea i got the exact same problem

**Comment by 000-whoami-000** [comment]
> yhea i got the exact same problem

Did you fix it?

**Comment by 0x0bedlag0x0** [comment]
no but i think that we need to change some stuff in the config file like discordbot, webserver and ports (this is just a guess im not really good at this stuff)

**Comment by LikeableMoneky** [comment]
I have the exact same problem, does anyone know how to fix it plz!

**Comment by wylie39** [comment]
Can you guys please post your configuration file?

**Comment by 000-whoami-000** [comment]
Yep

**Comment by 000-whoami-000** [comment]
[config.zip](https://github.com/themoonisacheese/2bored2wait/files/6253194/config.zip)
Other way i can't found) extract)

**Comment by 000-whoami-000** [comment]
> Can you guys please post your configuration file?

[config.zip](https://github.com/themoonisacheese/2bored2wait/files/6253198/config.zip)
Other way i can't found) extract)

**Comment by onayB09** [comment]
> ![Screenshot 2021-04-01 122720](https://user-images.githubusercontent.com/48528416/113273786-aa76a380-92e5-11eb-95e1-d4d22c7bae02.png)
> ![Screenshot 2021-04-01 122643](https://user-images.githubusercontent.com/48528416/113273789-ab0f3a00-92e5-11eb-942c-e3dd38b02275.png)
> 
> Could u halp <3

idk wheres the problem but theres a lots of warn in the npm install. maybe the problem starts here.
