### ISSUE TITLE
I can't run minecraft during bot is working

### ISSUE THREAD

**Issue by 000-whoami-000** [themoonisacheese/2bored2wait#246]
so, i run bot, and when trying to run minecraft during bot is running i have a massage as this from minecraft, and que in web stop
![Screenshot 2021-04-04 131828](https://user-images.githubusercontent.com/48528416/113505578-5c150f00-9548-11eb-9939-d0527928fe9f.png)

**Comment by MrGeorgen** [comment]
do you read the token from the .minecraft directory? the launcher might notice
that
