### ISSUE TITLE
Limbo Bug

### ISSUE THREAD

**Issue by E1ZY** [themoonisacheese/2bored2wait#249]
Chunks don't load after death.
![2021-04-06_22 59 36](https://user-images.githubusercontent.com/53375704/113771616-482a0280-972c-11eb-8467-ae5a36cddcba.png)
![2021-04-05_18 45 19](https://user-images.githubusercontent.com/53375704/113771620-495b2f80-972c-11eb-844c-cbfc0ee64489.png)

**Comment by E1ZY** [comment]
I am also starting to phase through the ground after death.

Also if I enter Nether through the portal I start phasing through the the ground and can't move around

**Comment by E1ZY** [comment]
Also other stuff won't load such as some skins from tab menu

**Comment by MrGeorgen** [comment]
> Chunks don't load after death.
> ![2021-04-06_22 59 36](https://user-images.githubusercontent.com/53375704/113771616-482a0280-972c-11eb-8467-ae5a36cddcba.png)
> ![2021-04-05_18 45 19](https://user-images.githubusercontent.com/53375704/113771620-495b2f80-972c-11eb-844c-cbfc0ee64489.png)

just to be sure, you did not reconnect?

**Comment by E1ZY** [comment]
no, I did not reconnect

**Comment by E1ZY** [comment]
updating to the current master branch didn't fix my problem

**Comment by E1ZY** [comment]
although tab menu now is loading properly

**Comment by MrGeorgen** [comment]
I'll test it. It has been a few months since I last joined 2b2t

**Comment by E1ZY** [comment]
although it works fine in vanilla.

After a few tests, I figured out that it doesn't work with those 3 mods:
kamiblue-2.03.17-2bec86e9d
OptiFine_1.12.2_HD_U_F5
wdlforge-4.0.1.7-SNAPSHOT

**Comment by E1ZY** [comment]
prly kamiblue messes smth up but I don't have any of packet-related modules enabled, I guess 
![image](https://user-images.githubusercontent.com/53375704/115257249-9087ee00-a138-11eb-9fce-944aed80f473.png)

**Comment by MrGeorgen** [comment]
there were other kamiblue issues as well #147.
>although it works fine in vanilla.

After a few tests, I figured out that it doesn't work with those 3 mods:
kamiblue-2.03.17-2bec86e9d
OptiFine_1.12.2_HD_U_F5
wdlforge-4.0.1.7-SNAPSHOT

does only optifine work? it should do any packet specific stuff

**Comment by E1ZY** [comment]
I tried to play with Impact only and I still phase through ground

**Comment by E1ZY** [comment]
I think maybe there is a problem with forge

**Comment by E1ZY** [comment]
and also my ETA bugs all the time 
![image](https://user-images.githubusercontent.com/53375704/115787248-8d0b9580-a3ca-11eb-8e28-a96ad029d3bf.png)

**Comment by E1ZY** [comment]
> and also my ETA bugs all the time
> ![image](https://user-images.githubusercontent.com/53375704/115787248-8d0b9580-a3ca-11eb-8e28-a96ad029d3bf.png)

like it gets negative all the time

**Comment by E1ZY** [comment]
> I think maybe there is a problem with forge

nope only forge without mods works fine

**Comment by rob9315** [comment]
Is this fixed now? Was it a problem with 2bored2wait?

**Comment by E1ZY** [comment]
nope. I guess this is some problem with nodejs or libraries and stuff
