### ISSUE TITLE
Default server (2b2t)

### ISSUE THREAD

**Issue by AverageComet250** [themoonisacheese/2bored2wait#250]
I was going through my config after resetting 2b2w and moving to my fork, and noticed that it uses `connect.2b2t.org` rather than `2b2t.org`. I decided to connect to the IP in the config and found that I still end up 700th in the queue, so I don't see why there's a reason for using `connect.2b2t.org` and not the normal IP. Is there a reason, or is it just the queue server IP?

**Comment by MrGeorgen** [comment]
some people had problems with the dns resoltion. #48 #162
Changing the domain fixed it. You connect to the same server with both domains
though

**Comment by AverageComet250** [comment]
I noticed that they point to the same server, but what actually is the point of having `connect.2b2t.org`? Does anyone here know, or should the Reddit community be asked this question?

**Comment by themoonisacheese** [comment]
IIRC there used to be a connection problem that got fixed by using connect. Can't remember what it was but it was a stability improvement, I think.
