### ISSUE TITLE
packet caching in a own library

### ISSUE THREAD

**Issue by MrGeorgen** [themoonisacheese/2bored2wait#255]
currently the packet caching is based on a fork of [mcproxy](https://github.com/rob9315/mcproxy).
First of all mcproxy is not maintained anymore. It's functionallity is also
far more than is needed for 2b2w. We only use Conn.ts
The reason I do not want to implement it in 2b2w is that packet caching could
be usefull for others as well. In mcidle, a packet caching proxy for c++
someone [requested a js mineflayer version](https://github.com/qubard/mcidle-cpp/issues/1). I have also seen someone using the cachePacket.js we had back in the day in a anti-afk proxy I can't find anymore

**Comment by czho** [comment]
this is a good idea, Ive used that library before for an project and it needs work, theirs random errors, a weird bug where chunks dont save randomly even when they should, things like that only exist cause it is not maintained anymore. Another issue is 2b2t possibly updating as the test server is very stable compared to the main server, mcproxy doesn't anywhere say thing it doesn't support 1.16, but it defiantly doesn't after hours of trying to get it to work, getting the same error.

**Comment by MrGeorgen** [comment]
the maintainer does respond to issues and prs again
