### ISSUE TITLE
Error when starting main.js

### ISSUE THREAD

**Issue by DavidSaguna** [themoonisacheese/2bored2wait#256]
![image](https://user-images.githubusercontent.com/51415612/114343502-ac9ef480-9b66-11eb-9a41-3a7b37d0b563.png)

**Comment by MrGeorgen** [comment]
after restructuring the project #253, some filepaths were not changed

**Comment by AverageComet250** [comment]
thanks, @MrGeorgen, I was manually fixing this myself and just saw this now.

I guess this issue is my fault, for not fixing file paths in the webserver.

**Comment by MrGeorgen** [comment]
yeah with so many places with the filepaths it's esay to overlooks. I didn't notice it because never use the webinterface
