### ISSUE TITLE
Randomly get timed out

### ISSUE THREAD

**Issue by DeadReaper451** [themoonisacheese/2bored2wait#262]
I have tried 3 times to use this leaving my computer on and at a random point every time it just randomly times out. Am I supposed to be checking it every once in a while to keep it going?

Connection error by 2b2t server. Error message: Error: read ETIMEDOUT Reconnecting...
14:01	Connection reset by 2b2t server. Reconnecting...
14:02	Reconnecting... 
14:02	Reconnecting... 
23:18	Connection reset by 2b2t server. Reconnecting...

**Comment by MrGeorgen** [comment]
is your internet stable? because your connection timed out
