### ISSUE TITLE
Discord Bot status is frozen and ETA counts down below 0

### ISSUE THREAD

**Issue by Doomer-Cat** [themoonisacheese/2bored2wait#263]
![DeepinScreenshot_select-area_20210421212651](https://user-images.githubusercontent.com/81427193/115603154-198d5980-a2e0-11eb-83a8-7c17e54d3067.png)

**Comment by Doomer-Cat** [comment]
Update: after 300 positions the bot has updated status but eta is still counting down

**Comment by MrGeorgen** [comment]
should be fixed after I revert a commit recently
