### ISSUE TITLE
Packaging program into more user friendly application

### ISSUE THREAD

**Issue by czho** [themoonisacheese/2bored2wait#266]
I constantly see issues on this github of users not knowing or understanding how to work 2b2w. Most of these come from the non standerd way of installing the program, you have to deal with npm and handle everything in the terminal. My proposed solution to this is using the npm package, pkg to package 2b2w into an executable and then editing the instructions for users to use the webserver control thing to control it. It also might be smart that with that packaged app, to bundle an already working config so most users can just double click it and it works fine. Only real thing a user would have to do is put in there account details.

**Comment by MrGeorgen** [comment]
This can be done using nexe. I have already written a build script, but it
currently does not have much use because if just the bineray is downloaded the
config file won't be in the right location

**Comment by themoonisacheese** [comment]
Main.js could start by detecting if the appropriate files are present and generate them if not, doing a fist run thing of sorts
