### ISSUE TITLE
Can't login to minecraft after using 2b2w?

### ISSUE THREAD

**Issue by FL8KT** [themoonisacheese/2bored2wait#270]
After I used 2b2w for the first time I can't log in to the Minecraft client anymore.
Does anyone have a solution for this problem![image](https://user-images.githubusercontent.com/67736220/116006463-b2d3ad00-a60b-11eb-8d7a-4e2c71a8f494.png)

**Comment by jakebry** [comment]
Also experiencing same issue. few hours sunk in nothing yet :/

**Comment by DontNeedAName** [comment]
The program somehow messes up your launcher_accounts.json. Just delete it and login with your accounts again. That fixes it.

**Comment by KozmikNano** [comment]
I believe that happens because of the way that it grabs data from the launcher.

**Comment by M4axim** [comment]
it happened to me too the easy way to login is to just add acc on button and should work normaly

**Comment by ImKindaSus** [comment]
> I believe that happens because of the way that it grabs data from the launcher.

Yes
