### ISSUE TITLE
place in queue: none

### ISSUE THREAD

**Issue by dimitarkolevdtd** [themoonisacheese/2bored2wait#271]
After starting the tool and clicking on the start queuing button, my place in the queue is still "none" 20 minutes later. My minecraft launcher is revoking me from entering my profile, so I can't check what happens if I connect to localhost.

Steps to reproduce:
Use windows 10 pro as OS with a copy of minecraft.
Have this config.json file: https://pastebin.com/tayatftz
Have the option to auto start the browser on and have your default browser be brave
Open cmd.exe in the 2bored2wait-master folder.
Run npm start
Click on the start queuing button.

Expected behaviour:
The tool starts counting down after a few minutes.
The ability to run minecraft 1.12

Actual behaviour:
Half of the time the connection gets revoked.
When 2b2t does accept the connection the tool does nothing.

I have no idea why this is happening.

**Comment by dimitarkolevdtd** [comment]
I found the problem. It appears that the secrets were incorrectly extracted from my launcher. I entered them manually and it worked.

**Comment by Kazthwak** [comment]
I am having the same or similar problem myself. My place in queue and ETA are None. Every few minutes I get disconnected from the queue. What did you mean secrets? were you talking about username and password?

**Comment by KozmikNano** [comment]
> I am having the same or similar problem myself. My place in queue and ETA are None. Every few minutes I get disconnected from the queue. What did you mean secrets? were you talking about username and password?


Yes, this means passwords, the grab info from launcher has been removed so there would be less confusion. Try deleting your config file or download the release 1.3.1 and selecting 2 when the update available message shows up.

**Comment by Kazthwak** [comment]
I have just tried that and been disconnected yet again. I only installed yesterday so i think I am already on 1.3.1. My queue and ETA remain at None and I am still getting disconnected from the queue. I am on a raspberry pi and I can join the queue normally if that makes a difference.

**Comment by Kazthwak** [comment]
I have tried installing on a Chromebook running Gallium OS and am having the same problem.

**Comment by KozmikNano** [comment]
Eta and queue none was fixed by: #431
