### ISSUE TITLE
How to connect to minecraft, if 2b2w is hosted on a server instead of same pc.

### ISSUE THREAD

**Issue by soham9229** [themoonisacheese/2bored2wait#276]
Yesterday, I spent my whole day figuring out to use and host 2b2w on replit.com And I was pretty successful to host 2b2w and get into Queue. But now I dont know what IP should i put into my minecraft client so that I would get connected to the server physically. Please Someone help me. 

Replit Link : https://replit.com/@FudgePlayz/2bored2wait-2B2T-Proxy

**Comment by MrGeorgen** [comment]
I have no idea how replit works. You have to look it up on their website

**Comment by soham9229** [comment]
ok np about replit.com
But What If I am running 2b2w on a different pc and want to play minecraft on a different pc. Then how do i connect to the server.
