### ISSUE TITLE
Using 2b2w and minecraft on 2 different Pc

### ISSUE THREAD

**Issue by soham9229** [themoonisacheese/2bored2wait#277]
ok np about replit.com
But What If I am running 2b2w on a different pc and want to play minecraft on a different pc. Then how do i connect to the server.

_Originally posted by @soham9229 in https://github.com/themoonisacheese/2bored2wait/issues/276#issuecomment-830679496_

**Comment by KozmikNano** [comment]
Ok so first you need to find out if both PCs are on the same WiFi. If they are then you need to get the ip address of the hosting pc. Use that as the server up. If you aren’t on the same WiFi then you need to port forward the hosting pc to your public ip address. (Look up a guided online on how to port forward). Next get the public up of the hosting pc and use that as the server address.

**Comment by MrGeorgen** [comment]
see also #230

**Comment by soham9229** [comment]
ok thanks
