### ISSUE TITLE
complete rewrite

### ISSUE THREAD

**Issue by rob9315** [themoonisacheese/2bored2wait#279]
@MrGeorgen 
I am currently working on a complete rewrite to fix multiple issues, also using typescript. I think it is ready soon™.
There are only some little things remaining to fix. How is your opinion of typescript?
As a side note, I will separate the Conn part of mcproxy from the basic usable program I built as a demo on top.
May I request Contributor role?

**Comment by MrGeorgen** [comment]
I really like typescript. How feature complete is your rewrite? is there a
public repo?

>May I request Contributor role?

Can this be done manually? The only way I know is through a pr

**Comment by themoonisacheese** [comment]
Contributor is given automatically when some of your code gets merged into
master. As far as making you a collaborator, I personally have no issue
with that, if @MrGeorgen is ok with that I can do it no problem.

**Comment by rob9315** [comment]
PR is now open [here](https://github.com/themoonisacheese/2bored2wait/pull/281)

**Comment by MrGeorgen** [comment]
>Contributor is given automatically when some of your code gets merged into
master. As far as making you a collaborator, I personally have no issue
with that, if @MrGeorgen is ok with that I can do it no problem.

Sure go ahead. I actually recently though about focusing more at other
activities / projects

**Comment by themoonisacheese** [comment]
@rob9315 has been added as a  collaborator.

**Comment by rob9315** [comment]
@MrGeorgen I have now started writing the typescript version. I'd suggest you look at [this repo](https://github.com/rob9315/2b2wTS) if you want to follow the progress

**Comment by rob9315** [comment]
The rewrite is taking shape, configuration is done, now only some small touches are still necessary

**Comment by AverageComet250** [comment]
Status update by any chance? I haven’t been playing 2b for the last 6 months or so, so I haven’t looked at this project, but I’m seeing recent pushes, etc, tho all the threads look outdated

**Comment by KozmikNano** [comment]
> Status update by any chance? I haven’t been playing 2b for the last 6 months or so, so I haven’t looked at this project, but I’m seeing recent pushes, etc, tho all the threads look outdated

This project works mostly as intended, only issue is the webserver which needs to be updated anyways! Some more features have been added and it works a lot better then it used to!

**Comment by rob9315** [comment]
will be moved to rust instead at some point

**Comment by KozmikNano** [comment]
> will be moved to rust instead at some point

💀why do you do this to yourself rob
