### ISSUE TITLE
Chunk  Loading Error 

### ISSUE THREAD

**Issue by soham9229** [themoonisacheese/2bored2wait#282]
So whenever you join the server after having 2b2w proxy in queue, the chunk you are in and the chunk besides  it doesnt load properly. I just shows a empty hole in the world. 
This also happens if you get disconnected from the instance and try to reconnect

**Comment by rob9315** [comment]
I don't think we can fix this. It is an issue with mineflayer, as the code to update the lighting information is still missing.
