### ISSUE TITLE
Add prismarine viewer

### ISSUE THREAD

**Issue by etiaro** [themoonisacheese/2bored2wait#284]
It would be nice to see in browser how antiafk is doing, and it's as easy to add as import prismarine-viewer and run one command on 'spawn' event:

mineflayerViewer(bot, { port: 3007, firstPerson: false })

**Comment by rob9315** [comment]
From my experience mineflayer Viewer has always been crashing a lot, which could be a problem. but adding it is not hard, so this is a good idea and will be a toggleable option in the future

**Comment by Luigit12** [comment]
Also it really doesnt like the void like queue on 2b

**Comment by cristiioan** [comment]
> Also it really doesnt like the void like queue on 2b

@Luigit12 This can be solved by using a is in queue check for activating it.

**Comment by Luigit12** [comment]
> > Also it really doesnt like the void like queue on 2b
> 
> @Luigit12 This can be solved by using a is in queue check for activating it. 
> 

Yeah i guess you dont really need the viewer in queue 😁

**Comment by cristiioan** [comment]
@Luigit12 if you are intrested this can be added to @rob9315 rewrite
