### ISSUE TITLE
Link in read me is still broken, working link provided.

### ISSUE THREAD

**Issue by KozmikNano** [themoonisacheese/2bored2wait#286]
https://github.com/themoonisacheese/2bored2wait/releases

**Comment by KozmikNano** [comment]
Instead of sending it to file location you should send it to the releases page that way it is more user friendly. Just an idea

**Comment by MrGeorgen** [comment]
> Instead of sending it to file location you should send it to the releases page that way it is more user friendly. Just an idea

you mean the config file?

**Comment by KozmikNano** [comment]
In the readme file it looks like your trying to send it to a file, instead you should just put the full link (https:// included)

**Comment by KozmikNano** [comment]
Ok looks like you just fixed it, fully works now🙂

**Comment by MrGeorgen** [comment]
yeah I though relative links would work
