### ISSUE TITLE
question

### ISSUE THREAD

**Issue by KozmikNano** [themoonisacheese/2bored2wait#288]

**Comment by KozmikNano** [comment]
@MrGeorgen I plan on making a video about how to use and setup the 2b2w system. I am doing this because @themoonisacheese’s video is outdated due to the recent changes.  Now the main question I have is that do you want to use my video under the video section? No shoutouts or anything are needed and if you need me to update, remove or add things to it then you just tell me. If you don’t want to have my video then I 100% understand!

**Comment by rob9315** [comment]
There are going to be some changes to the code soon, maybe also how to set it up. I would wait a week or so until these are through.

**Comment by KozmikNano** [comment]
Ok, I will wait a week or when ever I see the code update dramatically, then I will make a video.

**Comment by MrGeorgen** [comment]
on windows the executables don't work properly at the moment

**Comment by KozmikNano** [comment]
Ok that is good to know, how is it supposed to work? I mainly use a raspberry pi as my server but I did plan on doing a tutorial for windows and the raspi. Also how come the server the proxy connects to is connect.2b2t.org instead of 2b2t.org?

**Comment by MrGeorgen** [comment]
some had issues with resolving 2b2t.org but I can not confirm that. I'll
change it back

**Comment by KozmikNano** [comment]
Ok, I had changed my to that and I haven’t had any issues

**Comment by MrGeorgen** [comment]
it works now on windows. you can do your video

**Comment by KozmikNano** [comment]
Alright cool! I will make a video then post a link here!
