### ISSUE TITLE
General desync issues

### ISSUE THREAD

**Issue by themoonisacheese** [themoonisacheese/2bored2wait#29]
I'm pretty sure this is what causes #2 and #21 but I can't manage to fix it.

right now I think 2 things are happening:

the first is that the player's entityID is not in sync with the servers, so when the player recieves packets ordering it to eg apply an effect, it applies it to a random entity instead of itself. This problem is compounded by the fact that the proxyClient's entityID seems to always be 0.

the second half of the problem is that the player recieves packets telling it to spawn in the overworld twice. This is a problem described at https://wiki.vg/Protocol#Respawn . Spawning the player in dimension 1 (the end) might fix this problem, but then the client thinks it's in the end until respawn. careful control of packet order might fix this, but the first half of the problem still exists.

Help is very much wanted, as I just spent a good part of my weekend trying to fix this without any shred of success.

**Comment by mostafakerim** [comment]
You can get the entityID from the login packet and save it for when the proxyClient connects. The login packet looks like this: `{"entityId":<entityID>,"gameMode":0,"dimension":1,"difficulty":0,"maxPlayers":0,"levelType":"flat","reducedDebugInfo":false}` in the queue.
