### ISSUE TITLE
auto update docker readme

### ISSUE THREAD

**Issue by MrGeorgen** [themoonisacheese/2bored2wait#293]
the action fails while trying to update the dockerhub readme. https://github.com/themoonisacheese/2bored2wait/runs/2520427311
it does not work with a access token. https://github.com/peter-evans/dockerhub-description/issues/10
@themoonisacheese either put you password as a github secret or if you don't
want to do this, you could create a dummy account which is only in the
2bored2wait organization

maybe their is also some other way of updating the readme

**Comment by themoonisacheese** [comment]
fixed.
