### ISSUE TITLE
leaving the project behind

### ISSUE THREAD

**Issue by MrGeorgen** [themoonisacheese/2bored2wait#294]
First of all I don't play on 2b2t anymore. So I do not use 2b2w personally.
I don't want to spend that much time with gaming and programming in general because I'm
fosusing on other things now. And if I programm I want it to be usefull for me.

Some of are probably pretty surprised by this because I was very active the
last week. I wanted to finnish things I already began( build a single exe and
auto build the docker container because I won't update it frequently anymore).

However I really grew with the project. This is the first project I ever wrote
more than a 100 lines. I started working on it April last year. I enjoyed the
lockdown more than most people. Just a bit of school work to do and the rest
of the day working on 2b2w. Because my code was really bad it took long to
create my first pr.

I also want to thank all contributers, @themoonisacheese , the prismarinejs
team for creating such good libraries and @rob9315.

I will still answer on pull requests and some issues.
You can probably compare me with @themoonisacheese activity.

But I am certain this project will not die. @rob9315 will most likely
finnished moving the code to typescript and he might do other stuff as well. And the good
pull requests will continue

**Comment by themoonisacheese** [comment]
it's been fantastic having you and you're always welcome back. I've rencently been considering working on 2b2w more, although i do not know how or when that will manifest.

Thank you for all of your contributions, 2b2w is as much (if not more) of your work than mine.

**Comment by rob9315** [comment]
Thanks for keeping this project alive!

**Comment by cristiioan** [comment]
Sad
