### ISSUE TITLE
Add auto-disconnect

### ISSUE THREAD

**Issue by MarkBremer** [themoonisacheese/2bored2wait#295]
Please add an option to disconect from the server if you leave the proxy.

Thank you :)

**Comment by KozmikNano** [comment]
I will look into this but no promise on adding it.

**Comment by cristiioan** [comment]
It dosen't make sense what you wish. I preffer to have my accpunt 24/7. Do you mean like in cae you don't connect back after a few minutes? Abetter thing should be auto disconect baed on hearts you jave and if somone is nearby.
