### ISSUE TITLE
Detect when queue is broken

### ISSUE THREAD

**Issue by DarkoGNU** [themoonisacheese/2bored2wait#3]
So... there are situations like:
- I was 240th or something like that and I instantly went to place 80th. It was going down to 60th, and I was stuck for over 10 minutes. Probably some bug, I reconnected.
- I was maybe 80th again and I got 1st instantly. I didn't join for over 10 minutes. I disconnected.
- some cases like just getting stuck, without any instant position change
It happens to me sometimes both with the proxy and when I just use Impact. These anomalies should be detected and the proxy should begin queuing again.
Sorry for poor English :|

**Comment by starcraft66** [comment]
@themoonisacheese make the proxy send "/queue main" in chat when the queue breaks in order to be re-queued without losing your place or having to reconnect.

**Comment by themoonisacheese** [comment]
Thanks for the help, however the hard part is detecting when the queue is broken in the first place.

**Comment by ngt1133** [comment]
When you in queue, your position types in the chat. When queue is broken, server stops typing your queue. So

**Comment by starcraft66** [comment]
Yep, if you don't receive a chat message indicating your position in queue withing a 15-second window, consider the queue broken and send the message.

**Comment by themoonisacheese** [comment]
that's actually a very good point. will do.

**Comment by AverageComet250** [comment]
Just thought I'd ask if this has been implemented yet and if this should actually be closed

**Comment by MrGeorgen** [comment]
> Just thought I'd ask if this has been implemented yet and if this should actually be closed

code in this project hast not been implemented, but it is really long ago that I had this problem, so hausemaster might fixed it
