### ISSUE TITLE
Invalid session id

### ISSUE THREAD

**Issue by Rattlyy** [themoonisacheese/2bored2wait#30]
`err Error: Invalid credentials. Invalid username or password.`
I've relogged in minecraft.net alot of times.

**Comment by themoonisacheese** [comment]
did it work once? are you sure you provided the right credentials? did you use your email adress or your minecraft username?

**Comment by zRattly** [comment]
Yep
also used email

**Comment by MrGeorgen** [comment]
> I've relogged in minecraft.net alot of times.

sometimes this wion't help. after 30 minutes it should work again
