### ISSUE TITLE
Question: Separate tool that updates this program?

### ISSUE THREAD

**Issue by KozmikNano** [themoonisacheese/2bored2wait#300]
How would it sound if i made a tool that would install/update 2bored2wait to it latest version?

**Comment by rob9315** [comment]
I am opposed to integrating auto-update into this program, though you can obviously make your own program that auto-updates 2bored2wait. If you decide to make one, you can submit a pr to mention it in the readme.

**Comment by KozmikNano** [comment]
Alright cool, thanks!
