### ISSUE TITLE
Typescript require for Ubuntu user

### ISSUE THREAD

**Issue by namanhishere** [themoonisacheese/2bored2wait#305]
I found that the mcproxy require to istall tsc ( typescript) for ubuntu user. So maybe the mcproxy module can install it if it does not installed
[2021-05-15T15_42_26_832Z-debug.log](https://github.com/themoonisacheese/2bored2wait/files/6487687/2021-05-15T15_42_26_832Z-debug.log)

**Comment by namanhishere** [comment]
I fixed it by installing typescript via npm

**Comment by rob9315** [comment]
I am sorry, will be fixed right away

**Comment by czho** [comment]
found same issue though it was with the lib it self and not me using ubuntu on my vps
