### ISSUE TITLE
Discord Token check missing

### ISSUE THREAD

**Issue by rob9315** [themoonisacheese/2bored2wait#306]
[here](https://github.com/themoonisacheese/2bored2wait/blob/8455f1af0270a4e17f28eb8c3ce8dcb678ec962b/main.js#L78) or [here](https://github.com/themoonisacheese/2bored2wait/blob/8455f1af0270a4e17f28eb8c3ce8dcb678ec962b/main.js#L92) a check is needed to make sure no discord Client is created in case of no token being supplied. This was also (one) reason for [this issue](https://github.com/themoonisacheese/2bored2wait/issues/296).

**Comment by KozmikNano** [comment]
I know a fix to this. It implements my solution to turning off update messages. I could program this if you would like!

**Comment by rob9315** [comment]
A separate pr per issue would be very nice. It helps identifying future issues and makes partial rollbacks easier. I also know how to fix this but have not yet come to doing so.

**Comment by KozmikNano** [comment]
Ok, I will start working on it tomorrow and it should be working in 2-7 days.

**Comment by rob9315** [comment]
fixed
