### ISSUE TITLE
Connection reset by 2b2t server. Reconnecting...

### ISSUE THREAD

**Issue by z0mbieslayer** [themoonisacheese/2bored2wait#308]
Exactly as the title says. It was working fine the first time I tried it, and then it never worked after that. I've restarted my computer and everything. Help would be much appreciated.

**Comment by KozmikNano** [comment]
I would recommend deleting the .2bored2wait folder then rerunning the program.

**Comment by z0mbieslayer** [comment]
That didn't fix it unfortunately.

**Comment by KozmikNano** [comment]
Is your computer connected to a dns server?

**Comment by z0mbieslayer** [comment]
no

**Comment by KozmikNano** [comment]
Ok, two things, first can you connect to 2b2w? If not then it may be a network issue. If yes then try the developer way in the readme.

**Comment by z0mbieslayer** [comment]
im assuming you mean 2b2t? yes, i can connect.

**Comment by KozmikNano** [comment]
I’d mean that sorry.

**Comment by z0mbieslayer** [comment]
I have also tried the developer way, no dice. I have no clue what the issue is.

**Comment by KozmikNano** [comment]
Me neither it’s really weird that it wouldn’t work I have no further ideas to help sorry.

**Comment by z0mbieslayer** [comment]
That's alright, thanks anyways.

**Comment by z0mbieslayer** [comment]
Got it working. For some reason using the launcher for logging in didn't work so specifying my credentials manually fixed it.

**Comment by rob9315** [comment]
That sounds like an actual issue, it was probably a problem with there not being a check if the current token is valid
