### ISSUE TITLE
Precompiled binaries for ARM

### ISSUE THREAD

**Issue by KozmikNano** [themoonisacheese/2bored2wait#316]
I noticed that today @themoonisacheese had changed the readme to reflect that the install for Linux and Mac are the same as windows. At the current moment this isn’t true. Reason is below:

**Comment by KozmikNano** [comment]
Ok, so you know how on windows you run ".exe" files. Well on Linux it is ".sh", ".deb" or ".appimage". Mac, I am unfamiliar with so I have no idea its file extension is. The binary for the nonwindows platforms doesn't have a file extension. This causes many problems for the platforms that run then. Because of that, the readme should be reverted back or the binaries need to be fixed.

**Comment by themoonisacheese** [comment]
that is simply not true. the precompiled binaries can be invoked from console or just a file browser, as they're native binaries built for that operating system. Unix and unix-like systems (ie mac os) don't care about file extensions as much as windows does.

now, it does appear as though the binaries have some problems, but it is unclear if that is an issue with the builds or user error.

**Comment by rob9315** [comment]
Programs on linux (and macos?) don't have file extensions. They might have to be set executable with the command `chmod +x filename` though.

**Comment by KozmikNano** [comment]
This is the error you will get: 
![38EDE15E-A712-4897-BF10-BCA5C3309F34](https://user-images.githubusercontent.com/77017394/118808761-d4752c80-b877-11eb-89f7-1df6480c5314.jpeg) @themoonisacheese

**Comment by KozmikNano** [comment]
> Programs on linux (and macos?) don't have file extensions. They might have to be set executable with the command `chmod +x filename` though.

I have already done this. My main desktop is a Linux environment.

**Comment by rob9315** [comment]
https://askubuntu.com/questions/648555/bash-program-cannot-execute-binary-file-exec-format-error
What are you trying to run this on? I assume something like a raspberry pi or similar, these executables are only built for x86 architecture, I don't know if nexe can build for arm.

**Comment by themoonisacheese** [comment]
this is indeed a problem with architecture. i'm trying to figure out if nexe can build for arm but in the meantime you're welcome to run either through docker or cloning.

**Comment by KozmikNano** [comment]
Ok thanks for helping me figure that out. I used box86 and it still wouldn’t work witch confused me greatly! Also is there a place where I can dm you?

**Comment by themoonisacheese** [comment]
all my links are available on my website that can be found on my profile or at http://poggers.website

**Comment by KozmikNano** [comment]
Thanks, nice url lol.
