### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by seeth3r** [themoonisacheese/2bored2wait#32]
https://prnt.sc/poc8uj how to fix

**Comment by seeth3r** [comment]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.12.0
3 info using node@v12.13.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle 2bored2wait@1.0.0~prestart: 2bored2wait@1.0.0
6 info lifecycle 2bored2wait@1.0.0~start: 2bored2wait@1.0.0
7 verbose lifecycle 2bored2wait@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle 2bored2wait@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Seeth\Desktop\2\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Users\Seeth\AppData\Local\Microsoft\WindowsApps;C:\Users\Seeth\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Seeth\AppData\Roaming\npm
9 verbose lifecycle 2bored2wait@1.0.0~start: CWD: C:\Users\Seeth\Desktop\2
10 silly lifecycle 2bored2wait@1.0.0~start: Args: [ '/d /s /c', 'node main.js' ]
11 silly lifecycle 2bored2wait@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle 2bored2wait@1.0.0~start: Failed to exec start script
13 verbose stack Error: 2bored2wait@1.0.0 start: `node main.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid 2bored2wait@1.0.0
15 verbose cwd C:\Users\Seeth\Desktop\2
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v12.13.0
19 verbose npm  v6.12.0
20 error code ELIFECYCLE
21 error errno 1
22 error 2bored2wait@1.0.0 start: `node main.js`
22 error Exit status 1
23 error Failed at the 2bored2wait@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by themoonisacheese** [comment]
it looks like the data I was expecting and what was sent didn't match. were you able to connect to 2b2t normally at that time?
