### ISSUE TITLE
cant run discord bot when the exe is closed

### ISSUE THREAD

**Issue by TheCamperGamer** [themoonisacheese/2bored2wait#321]
i want to log into 2b2t at 10:00am but i have to turn off my pc and i cant make the discord bot run with my pc offline (is it possible to run it online or something?)

**Comment by KozmikNano** [comment]
The main reason you can’t run the discord bot while it is closed is because of security reasons. Now I would recommend investing in a raspberry pi if you have to turn off your pc at night. It is only $35 and is very power efficient.

**Comment by rob9315** [comment]
You have to have your computer running for the discord bot to be logged in from this program. If you need to turn off your computer , I would recommend, just as KozmikNano said, to get a raspberry pi. If that isn't an option you might be able to use a cloud hosting service instead.
