### ISSUE TITLE
Possible to use 2b2w on a Raspberry Pi and later join on main PC?

### ISSUE THREAD

**Issue by NZ510** [themoonisacheese/2bored2wait#322]
Hello guys, 
since my Raspberry Pi is running 24/7 I came up with the Idea of using it to join the queue and later joining on my main PC.
I installed Minecraft Java 1.12.2 with 'Pi Apps' and it launches fine.

When I start 2b2w with the Discord bot it says 'Connection reset by 2b2t server, reconnecting' on the console of the Pi.
On the other hand, joining the server with the Raspberry Pi works fine, so I guess it's a software sided problem?
Is it even possible to start the queue with the Pi and later join with my main PC?

Thanks for your help

**Comment by KozmikNano** [comment]
Yes you can start the 2b2w program on the pc or pi and play on the other. For the problem with connecting you might have typed in the wrong info. Delete the whole program and the config file, then rerun it. I own a raspi my self so if you need any help connecting to the pi or pc you can @ me

**Comment by NZ510** [comment]
Okay so I got it working. 
Before the Pi I tested it on my main PC. When 2b2w asked if it should get the account data from the launcher I said 'yes' and it worked. However on the Pi for some reason it didn't work. Fix is that you just give the program your email and password and that's it. I don't know it that's a bug? Mabye because usually you can't get Minecraft Java for Pi? I don't know.
Anyways thank you all for contributing to this program! :)

**Comment by KozmikNano** [comment]
@NZ510 The reason that it didn’t work on the pi is because the launcher for Minecraft on the pi is a older version that this project is intended for. Sadly us pi users cannot do anything about this!

**Comment by NZ510** [comment]
Oh okay. I also read that the thing with Mojang accounts being moved to Microsoft accounts the old launcher wont't be available anymore. But the Pi-Apps team of Minecraft Java is already working on a fix for that.

**Comment by KozmikNano** [comment]
> But the Pi-Apps team of Minecraft Java is already working on a fix for that.

Good to know I have been waiting a while to get the latest stuff. So that makes me happy that they are working on it!

**Comment by NZ510** [comment]
@KozmikNano One more question: When I want to connect to 2B2T on my main PC I guess I take the IP of the Pi as the server IP instead of localhost?

**Comment by rob9315** [comment]
> When I want to connect to 2B2T on my main PC I guess I take the IP of the Pi as the server IP instead of localhost?

yes, exactly

**Comment by KozmikNano** [comment]
If you need help finding that ip just type `hostname -I` On the terminal of the pi

**Comment by NZ510** [comment]
Alright, thanks for you help :)

**Comment by KozmikNano** [comment]
Np
