### ISSUE TITLE
"Connection reset by 2b2t server. Reconnecting..."

### ISSUE THREAD

**Issue by Mister-Three** [themoonisacheese/2bored2wait#323]
Launching the 2bored2wait and then entering start doesn't start anything and all I see is it printing "Connection reset by 2b2t server. Reconnecting..." Whenever I type "start"
image: 
https://user-images.githubusercontent.com/81454774/119577347-791bd080-bd88-11eb-9cc1-ded5f83704be.png

**Comment by KozmikNano** [comment]
Ok, first thing: did you use the search from launcher option?
Second thing make sure you have entered the correct account info.

**Comment by Mister-Three** [comment]
> Ok, first thing: did you use the search from launcher option?
> Second thing make sure you have entered the correct account info.

works now, it was an issue with auto detect for mc info

**Comment by KozmikNano** [comment]
@Mister-Three Good to hear, it seems that the auto detect system seems to be broken, so I will have to look into that!

**Comment by rob9315** [comment]
It is an untold fact that this is broken. It has been for a long time already. It should work by pinging the server for it's general info, but that was always broken on non-vanilla servers and lately as well for the vanilla servers. This is an issue in node-minecraft-protocol and I don't know if it can be fixed at all.

**Comment by rob9315** [comment]
Wrong thing, my bad. You were talking about launcher data, right? So it should read your current token from the existing files of your minecraft installation. Though tokens can get invalidated, which is the one big flaw with launcher data.
Currently this is not working as it should. The preferred method is using your credentials directly.
