### ISSUE TITLE
error when using start command

### ISSUE THREAD

**Issue by HW12345** [themoonisacheese/2bored2wait#324]
whenever I use start command, the console just say:
$ (node:8776) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at cb (C:\Users\(user)\Desktop\node_modules\minecraft-protocol\src\client\auth.js:97:51)
    at C:\Users\(user)\Desktop\node_modules\yggdrasil\src\utils.js:73:15
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `2bored2wait-windows-x86-0.1.36 --trace-warnings ...` to show where the warning was created)
(node:8776) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8776) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by soham9229** [comment]
try doing `npm install` once again

**Comment by HW12345** [comment]
> try doing `npm install` once again
I use the exe one and I don't need to npm install

**Comment by KozmikNano** [comment]
Please delete the config file and try to run it again. I think your config file is corrupt or it has typos in it.

**Comment by rob9315** [comment]
> $ (node:8776) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '**name**' of undefined
> at cb (C:\Users(user)\Desktop\node_modules\minecraft-protocol\src\client\auth.js:97:51)
> at C:\Users(user)\Desktop\node_modules\yggdrasil\src\utils.js:73:15

This means that you are using an old version of launcher-profiles.json that isn't supported anymore.
You will have to delete your launcher-profiles.json file in the root of the minecraft config directory (`%appdata%\.minecraft\` if I remember correctly).
Even better would be if you just used the *manual authentication*, as the launcher-profiles.json method is irreparably broken at the moment or rather it changes too often.
