### ISSUE TITLE
proxy doesnt work

### ISSUE THREAD

**Issue by xdfchvbjknml** [themoonisacheese/2bored2wait#325]
When I try to join the queue the connection is getting restarted.
![obraz](https://user-images.githubusercontent.com/71084688/119841092-d12c1180-bf05-11eb-81f9-b4f0824c9183.png)

**Comment by KozmikNano** [comment]
Did you use the search for credentials when setting it up. That feature is broken right nowa

**Comment by xdfchvbjknml** [comment]
no, signed manually

**Comment by KozmikNano** [comment]
I would recommend deleting the config file located at `Home directory of your user/.2bored2wait/config/local.json`

**Comment by KozmikNano** [comment]
The rerun the program

**Comment by xdfchvbjknml** [comment]
deleted, reruned and still doesn't work
![obraz](https://user-images.githubusercontent.com/71084688/119981245-af8e6100-bfbd-11eb-9058-feb6ec3aaeb7.png)

**Comment by xdfchvbjknml** [comment]
yes, i can connect to 2b2t from game

**Comment by KozmikNano** [comment]
that is really weird. I am kinda clueless on this one, sorry.

**Comment by xdfchvbjknml** [comment]
it got fixed after recent updates
