### ISSUE TITLE
potion effects or fire doesnt show

### ISSUE THREAD

**Issue by ooodlllars** [themoonisacheese/2bored2wait#33]

**Comment by themoonisacheese** [comment]
can't fix unless i rewrite minecraft-protocol.

**Comment by sijanec** [comment]
The sudden popularization of 2b2w caused the 2b2t admin to try and run the server with as little respect to the wiki.vg protocol as possible, trying to make 2b2w (or minecraft-protocol) unusable.

**Comment by themoonisacheese** [comment]
it may, but i'm pretty sure this specific problem has always been in minecraft-protocol.

**Comment by NBTX** [comment]
@themoonisacheese I have done a lot of in depth research into the Minecraft protocol and I have implemented my own Minecraft server (though it is in Java) and both it and `minecraft-protocol` have far more functionality than is needed.

I will try writing a replacement for the protocol package that we can use specifically for this package.

**Comment by AverageComet250** [comment]
@NBTX did you ever finish that protocol package?

If yes, then could you send a link to it, and if no, then this issue needs closing, cause a custom protocol package really isnt necessary

**Comment by MrGeorgen** [comment]
>a custom protocol package really isnt necessary

I agree it would require to much work

>then this issue needs closing

I'm not sure about that. Do potion effects and fire show now?

**Comment by AverageComet250** [comment]
I'm not sure. I'm currently out of house, but I can connect 2b2w to a private server and test it when I get back

Thanks,
Shravan Mandava

________________________________

**Comment by MrGeorgen** [comment]
>I'm not sure. I'm currently out of house, but I can connect 2b2w to a private server and test it when I get back

nice you also answer on the go.
I could test it too but not today
