### ISSUE TITLE
Docker container fails to start

### ISSUE THREAD

**Issue by Ashesh3** [themoonisacheese/2bored2wait#334]
While starting a docker instance from the command specified in Readme file, 

`docker run 2bored2wait/2bored2wait:latest -d -p 80:8080 -p 25565:25565 -e NODE_CONFIG='{"username": "user@domain.com", "mcPassword": "myverysecretpassword", "BotToken": "mydiscordbottoken"}'`

Replacing the above values with me own account details,

The instance fails to start due to the error:

![image](https://user-images.githubusercontent.com/3626859/120668689-51291d00-c4ac-11eb-96fc-842784671563.png)

`node: bad option: -d`

Removing `-d` from the command, the docker contains exits immediately after outputting the configuration on the screen.

![image](https://user-images.githubusercontent.com/3626859/120668656-48384b80-c4ac-11eb-8676-37b1803a23dd.png)

**Comment by HyCore** [comment]
same

**Comment by rob9315** [comment]
The docker instructions seem to be outdated with a docker cli update. It seems this is a problem of where the -d option is placed. It should probably be before the docker-repo name. Can you please try
```shell
docker run -d 2bored2wait/2bored2wait:latest -p 80:8080 -p 25565:25565 -e NODE_CONFIG='{"username": "youremail", "mcPassword": "yourpassword", "BotToken": "yourtoken"}'
```
If this works, we'll change the readme

**Comment by Ashesh3** [comment]
@rob9315 I tried the above command, the container starts and instantly exits after outputting the config

```
root@mail:~# docker run -d 2bored2wait/2bored2wait:latest -p 80:8080 -p 25565:25565 -e NODE_CONFIG='{"username": "x123@gmail.com", "mcPassword": "xxx5#x", "BotToken": "x.YLjo8A.x"}'
c40a6775f4cc8f6a967cc8aa67ed8bae892a42b6648d801bb4e3d743add65b1f
root@mail:~# docker ps --all
CONTAINER ID   IMAGE                            COMMAND                  CREATED         STATUS                     PORTS     NAMES
c40a6775f4cc   2bored2wait/2bored2wait:latest   "docker-entrypoint.s…"   3 seconds ago   Exited (0) 2 seconds ago             elegant_lederberg
root@mail:~# docker logs c40a6775f4cc
{
  username: 'xx123@gmail.com',
  mcPassword: 'xxxx',
  BotToken: 'x.x.x'
}
root@mail:~#
```

I made sure those ports aren't used already and i even tried different ports, it just exits immediately, my info is correct, it works locally without docker.

**Comment by Ashesh3** [comment]
For some reason the latest docker container has the version 0.1.38 which gets stuck on start as there is an update available. (0.1.39)

![image](https://user-images.githubusercontent.com/3626859/120738271-320ea780-c50d-11eb-8b02-1372fd15e15b.png)

I am using the latest container, but the version is behind. 

```
root@mail:~# docker pull 2bored2wait/2bored2wait:latest
latest: Pulling from 2bored2wait/2bored2wait
Digest: sha256:2059c4234936b384919ff13e06eebe46e36119e5613a6258071181be8ba9c270
Status: Image is up to date for 2bored2wait/2bored2wait:latest
docker.io/2bored2wait/2bored2wait:latest
```

**Comment by KozmikNano** [comment]
Can you hit enter then enter all the info regarding your account? If yea then you you can say no to update messages. I do realize this is a problem but I can’t fix it

**Comment by Ashesh3** [comment]
> Can you hit enter then enter all the info regarding your account? If yea then you you can say no to update messages. I do realize this is a problem but I can’t fix it

I can not do any of that, i do not have a shell inside the docker when it starts. If you mean i should shell into the stopped container and manually restart the process, then that defeats the purpose of using docker for me. 

I hope we are able to fix it and making it work just by starting the container without going through manually efforts.

**Comment by KozmikNano** [comment]
Yeah let me get you a config file option you can type so then you can run it

**Comment by KozmikNano** [comment]
Here is what the config file will look like. Please fill in the blank sections. This will disable that message!
`{
  "mcPassword": "",
  "updatemessage": "n",
  "username": "",
  "BotToken": "",
  "discordBot": false
}`

**Comment by Ashesh3** [comment]
> Here is what the config file will look like. Please fill in the blank sections. This will disable that message!
> 
> {
> "mcPassword": "",
> "updatemessage": "n",
> "username": "",
> "BotToken": "",
> "discordBot": false
> }

Thank you for this but seems like the issue is something else, if i start my docker container with those options, it again exits immediately after it starts.

```
root@mail:~# docker run -d 2bored2wait/2bored2wait:latest -p 8080:8080 -p 25565:25565 -e NODE_CONFIG='{"username": "x@gmail.com", "mcPassword": "x#x", "BotToken": "x.x.x","updatemessage": "n"}'
1aedbf593fb2b8945cf91430a9a601f150a0877e81bfb318f60d53d54243da78
root@mail:~# docker ps --all
CONTAINER ID   IMAGE                            COMMAND                  CREATED              STATUS                          PORTS     NAMES
1aedbf593fb2   2bored2wait/2bored2wait:latest   "docker-entrypoint.s…"   7 seconds ago        Exited (0) 5 seconds ago                  suspicious_lehmann
root@mail:~# docker logs 1aedbf593fb2
{
  username: 'x@gmail.com',
  mcPassword: 'xxBxhm',
  BotToken: 'x.YLjo8A.x',
  updatemessage: 'n'
}
```

As you can see, the docker stops as soon as it starts, i am not sure what the issue is.

**Comment by KozmikNano** [comment]
Try removing the brackets, it might not work but it is worth a try.

**Comment by Ashesh3** [comment]
Doesn't work but starting a 2b2w container with `sh` as entry point (instead of the default one) then running `npm start` after setting that ENV variable works.

But still not the appropriate solution.

**Comment by KozmikNano** [comment]
That is very true. Sorry I am not able to help fully as I am not familiar with docker.

**Comment by Ashesh3** [comment]
> That is very true. Sorry I am not able to help fully as I am not familiar with docker.

No worries, thank you for your time. I appreciate it! Hopefully the maintainers can shine some light to the issue.

**Comment by KozmikNano** [comment]
> > That is very true. Sorry I am not able to help fully as I am not familiar with docker.
> 
> No worries, thank you for your time. I appreciate it! Hopefully the maintainers can shine some light to the issue.

Hopefully, at the current moment I am actually trying to become a contributor status so then I can recompile stuff when ever.

**Comment by KozmikNano** [comment]
@Ashesh3 try this ```shell
docker run -d -p 80:8080 -p 25565:25565 -e NODE_CONFIG='{"username":"example@domain.com","mcPassword":"password","updatemessage":"n","BotToken":""}' 2bored2wait/2bored2wait:latest```

**Comment by rob9315** [comment]
can you please see if this issue was resolved after the latest version update?

**Comment by Ashesh3** [comment]
@KohimaNayagato Thanks that worked!
@rob9315 Readme looks good now, works.
