### ISSUE TITLE
Still problems after reconnecting

### ISSUE THREAD

**Issue by Gusarich** [themoonisacheese/2bored2wait#337]
I already opened issue here long time ago #210 
Thought it will be fixed... Not really.
After reconnecting it seems like normal, but I can't move. Even if I just rotate my head it every time gets me back to first position. Only way I can move is on boat (maybe horses, didn't check).
When I try to leave boat it just glitches and I can't even fall in water to kill myself and fix glitch...

**Comment by KozmikNano** [comment]
Question, are you on the latest version and have cleared all data such as the .2bored2wait folder?

**Comment by Gusarich** [comment]
> Question, are you on the latest version and have cleared all data such as the .2bored2wait folder?

I actually installed it on new dedicated server.

**Comment by Gusarich** [comment]
Tried again. I just can't move. It teleports me back everytime. The only way I can move is boat. But even when I'm riding it, it like teleports me for a moment and gets back... Impossible to play or even fishing..

**Comment by Gusarich** [comment]
Hm. Enabled blink in my cheat client. In like 15 sec I got kicked from proxy server for keep-alive error. After connecting again glitch waa fixed.

I hope that will work every time. Will check tomorrow

**Comment by Gusarich** [comment]
After fixing, I can reconnect without problems.
Don't know why first time that glitch was there, but now it works almost perfect.
