### ISSUE TITLE
Does this still works? been trying to connect from two days and it always resets (reconnect) at 100-200!!

### ISSUE THREAD

**Issue by hari01584** [themoonisacheese/2bored2wait#340]
Seriously never worked for me, Whenever i reach something like 100-200, it always reconnects and queue start from end again!! 😞 

Quite irritating but idk why its happening, initially i thought it might be my network problem, but now im not too sure! Had it running for a whole night and it reconnected for 4 times, the best case going upto 127 in queue :(!!

**Comment by KozmikNano** [comment]
The most advise I can think of is you deleting all the files from the program(including the config) and installing exactly how the readme states. Try both of the installing versions too.

**Comment by hari01584** [comment]
Alright, got it working, the problem was with my network provider!! I changed to mobile data and successfully connected to 2b2t servers.
