### ISSUE TITLE
[Not A Bug] Successfully got 2bored2wait running into android device, with full features using Termux!!

### ISSUE THREAD

**Issue by hari01584** [themoonisacheese/2bored2wait#341]
This is not a bug but a small discovery, which i would like to share here :)!!

Pretty much the title says it! Finally got 2bored2wait running into my android device! (Android 10)!! Here screenshot!
![06355f0a-9167-4bd4-9023-2e6a4baf6dcd](https://user-images.githubusercontent.com/31770598/123311271-9937de80-d544-11eb-9d2c-ae97baf75488.jpg)

I am sure that many might have already succeeded doing this but nevertheless I am leaving small instructions to get it working:
1. Install Termux latest version from F-Droid (Playstore version is deprecated and obsolete) [*link here*](https://f-droid.org/en/packages/com.termux/)
2. Go into termux and  [follow this](https://www.freecodecamp.org/news/building-a-node-js-application-on-android-part-1-termux-vim-and-node-js-dfa90c28958f/)  small tutorial to install nodejs.
3. Clone this repo using `git clone https://github.com/themoonisacheese/2bored2wait` then cd into the directory `cd 2bored2wait`.
4. Finally do `npm install` and `npm start`, if nothing goes wrong you will see it starting and working :)!!

Although i did manage to pull this off but i am afraid that this might not be good enough, I don't know if it is just me but i get too many reconnects when trying to queue up, **_So please do comment below if it worked for you!! I am not sure this is stable enough to queue using android._**

My Inspiration? Welp i have a raspberry but i didn't like it running whole night for queue because there's no guarantee that i will not experience power outage, and in that event my raspberry will turn off terminating everything! So i thought it might be amazing if somehow this could be implemented on android, since android need not to be on power supply for 24x7 and they are quite handy, So i tried to use termux, If this helps then write below :)!

**Comment by KozmikNano** [comment]
Cool discovery! Quick question does it run with your screen off?

**Comment by hari01584** [comment]
> Cool discovery! Quick question does it run with your screen off?

I am certain some part of it runs (as i was able to ask for update from discord bot) but i think queue system **might** be broken or not that functional.

**Comment by Bluefox187** [comment]
I also tried this 1 month ago and it worked. Its so amazing.

**Comment by Bluefox187** [comment]
> 
> 
> I also tried this 1 month ago and it worked. Its so amazing.
> Its a livesafer while in school.

im using it all day

**Comment by Bluefox187** [comment]
It's cool to see that somebody else discovered it as well. 

Back when I discovered that you can use it with Termux I also wanted to make a post about it but then I forgot it. Also you made a great job making this post.

**Comment by Bluefox187** [comment]
Btw. : When I did "npm update" it showed that it added mineflayer and prismarineviewer. Are there any active commands for that yet?

**Comment by hari01584** [comment]
Lots of messages here, why not have all that in one single comment? Might look more neat :)!!

I think mineflayer and prismarineviewer are just dependency to run the tool, not sure where exactly they are used.

**Comment by QbitBLue** [comment]
For me, it didn't work, sadly. Although I might have done something wrong.
It starts with the usual "Queue is starting up", but nothing happens afterwards. When I type update, it says 2b2t is offline, although 2b2w is working just fine on PC.

**Comment by timof121** [comment]
very ez

**Comment by themoonisacheese** [comment]
> Btw. : When I did "npm update" it showed that it added mineflayer and prismarineviewer. Are there any active commands for that yet?

We use mineflayer and prismarine viewer for the anti-afk system.

**Comment by sebascontacto** [comment]
![image](https://github.com/themoonisacheese/2bored2wait/assets/135523244/37b4ba64-40a1-4d69-b210-0437a7ad2250)
  I get that how do I solve it?

**Comment by KozmikNano** [comment]
@sebascontacto try this:
`sudo apt-get install libssl-dev`

**Comment by sebascontacto** [comment]
![image](https://github.com/themoonisacheese/2bored2wait/assets/135523244/15b29ba1-d7ce-42a0-986d-53b0e3f71185)

**Comment by KozmikNano** [comment]
Did you edit default.json? If so please remove the edits.

**Comment by sebascontacto** [comment]
no im only use termux

**Comment by sebascontacto** [comment]
can you help me?

**Comment by sebascontacto** [comment]
can you send me to edit it?

**Comment by KozmikNano** [comment]
> can you send me to edit it?

https://github.com/themoonisacheese/2bored2wait/issues/551

Here is the original config

**Comment by sebascontacto** [comment]
![image](https://github.com/themoonisacheese/2bored2wait/assets/135523244/d30d5e87-c2db-483c-b258-c8346e224b79)

**Comment by KozmikNano** [comment]
Support for @sebascontacto has been moved to #551

**Comment by hari01584** [comment]
For all those who have been trying to do this lately, I recommend looking into installing Debian, and on top of that 2bored2wait, I have yet to confirm this myself however, since termux is rolling down its own packages, and they are many times incompatible, there are lots of dependency issues, and also that root permission problem. You cannot and _should not_ get in vanilla termux, thereby try doing it debian way, it fixed many things and turns life simpler.

Here a good link where you can install it - [https://github.com/sp4rkie/debian-on-termux](debian-on-termux)

**Comment by KozmikNano** [comment]
Thank you @hari01584

**Comment by sebascontacto** [comment]
the link does not work on pc
