### ISSUE TITLE
[SUGGESTION] 2bored2wait Discord Server

### ISSUE THREAD

**Issue by Bluefox187** [themoonisacheese/2bored2wait#342]
It would be really nice if someone could make a discord server for this project with github bot and support channel and stuff.
I would be down to help.

**Comment by qualk** [comment]
Same

**Comment by BruhBruhStupidCoder** [comment]
Same

**Comment by KozmikNano** [comment]
Well I have great new! A discord server is in the development, and a awesome bot to go with it! It is kinda hard to develop right now as we have school/jobs and other projects to work on.

**Comment by Bluefox187** [comment]
> Well I have great news! A discord server is in the development, and a awesome bot to go with it! It is kinda hard to develop right now as we have school/jobs and other projects to work on.

I have enough time as I have summer holidays right now for the next 4 weeks.
So if I should help DM me on discord: Bluefox#1337

**Comment by utsavman1234** [comment]
yeah pls do it

**Comment by rob9315** [comment]
ok here is a discord server where you can get help: 
https://discord.gg/SSevK7atVB
make sure to FOLLOW THE RULES there.
