### ISSUE TITLE
The file secret.json doesn't appear

### ISSUE THREAD

**Issue by Smokygit99** [themoonisacheese/2bored2wait#343]
The file secret.json doesn't appear in the folder.

**Comment by KozmikNano** [comment]
We no longer have that file in the recent updates. Is there a place that says you need them?

**Comment by Smokygit99** [comment]
Yes, I had seen the video tutorial on youtube to install 2bored2wait

**Comment by Smokygit99** [comment]
> Sì, avevo visto il video tutorial su youtube per installare 2bored2wait


So where should I put the minecraft credentials?

**Comment by KozmikNano** [comment]
Sadly all the videos are outdated. Please look at the readme for the instructions.

**Comment by Smokygit99** [comment]
Ok thanks

**Comment by KozmikNano** [comment]
> > Sì, avevo visto il video tutorial su youtube per installare 2bored2wait
> 
> So where should I put the minecraft credentials?

No need too they will get them when you run the program. Do not click the option to grab from launcher though.
