### ISSUE TITLE
Request: automatic program for 2b2w

### ISSUE THREAD

**Issue by Smokygit99** [themoonisacheese/2bored2wait#345]
I wanted to ask if it is possible to create a python program to automatically write things into the prompt. For example, you can set the program to start automatically when the computer opens, which writes "npm start" and "play 13:00" (for example), so if the queue lasts more than 4 hours I can be sure to play. Thank you

**Comment by KozmikNano** [comment]
Right now I am actually creating a GUI!

**Comment by Smokygit99** [comment]
It's a good idea.

**Comment by hari01584** [comment]
For the meantime what about using web APIs to do all this stuff? As far as i remember web apis have these things right?

**Comment by KozmikNano** [comment]
The web APIs are not capable of letting you enter your info. The most GUI like thing would to put your info in the config file. For now it would be easiest to enter it into command prompt as usual.

**Comment by rob9315** [comment]
You can simply pipe the output of your program into node.
Something like this will work as a simple shell script:
```sh
echo "play 8:30" | npm start
```
You can do the same with a python script. Even better yet, you can start a subprocess and write to its stdin (Standard Input).
Here an example in javascript:
```js
const cp = require('child_process');
let process = cp.exec('npm start');
process.stdin?.write('play 8:30\n');
```
It should work the same way for python.

**Comment by Smokygit99** [comment]
Ok, thanks
