### ISSUE TITLE
Can't start 2Bored2Wait.

### ISSUE THREAD

**Issue by MattLongcock** [themoonisacheese/2bored2wait#349]
When I start 2b2w, It lets me input my login details, and when I do that I get this message 

```
Starting 2b2w
$ [Error: EACCES: permission denied, open 'config/local.json'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: 'config/local.json'
}
```

**Comment by rob9315** [comment]
Please give some more information, such as:
- which OS you are on
- how you started 2b2w
- where you saved 2b2w to

**Comment by KozmikNano** [comment]
Try running the command but with a `sudo` in the front. Ex:
```sudo npm start```

**Comment by KozmikNano** [comment]
Also you should update your version on node:

```
sudo apt purge nodejs 

curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -

sudo apt install nodejs```

**Comment by qualk** [comment]
no, use 'curl -sL https://deb.nodesource.com/setup_16.x | sudo bash -' 
the newer the better
