### ISSUE TITLE
wont start queue

### ISSUE THREAD

**Issue by Ozynt** [themoonisacheese/2bored2wait#367]
When I try to start the queue on my ubuntu PC I get this error (using a Microsoft account) ![image](https://user-images.githubusercontent.com/58683893/128718360-c91688c1-4cd7-4658-a4e6-d332c91120ea.jpeg)

**Comment by rob9315** [comment]
please ask here: https://discord.gg/qbz8hFNG,
We have nothing to do with the microsoft authentication.
Make sure you double checked you have the correct credentials.

**Comment by Ozynt** [comment]
got it working now idk how tho. Still got some issues with my vps server.

**Comment by rob9315** [comment]
good to hear
