### ISSUE TITLE
Getting kicked from 2b2t after a few seconds

### ISSUE THREAD

**Issue by NoobTracker** [themoonisacheese/2bored2wait#377]
Okay, now it happened a second time, I got kicked a few seconds after I finished queue, with a message like "Connection reset by 2b2t server" and "Reading position in queue from tab failed! Is the queue empty, or the server isn't 2b2t?". That only happens in the newer versions, I previously used 1.0.0 I think. I have no clue how to troubleshoot that, I'm using a RasPi with some experimental Node versio for Arm6, and I'm 99% sure I don't get kicked because of my hacks, I turned some of them off before joining this time, just to be extra safe.

**Comment by rob9315** [comment]
This issue might have been resolved with a new version of [`mcproxy`](https://github.com/rob9315/mcproxy) feel free to reopen if the issue still persists
