### ISSUE TITLE
I do not have a secrets.json example or secrets.json

### ISSUE THREAD

**Issue by Thehappycoder123** [themoonisacheese/2bored2wait#378]
I am trying to follow the install tutorial but I do not have the secrets.json or secrets.json example folders. Also, I do not have a local.json file.

**Comment by KozmikNano** [comment]
Hello! So I see that you are trying to install it using the tutorial. This won’t work, you have to instead follow the instructions on the readme of this project.

**Comment by Thehappycoder123** [comment]
Ok
