### ISSUE TITLE
Use Websockets

### ISSUE THREAD

**Issue by Emilius123** [themoonisacheese/2bored2wait#38]
Seriously, why doesn't this use Websockets?
They'd be easy to implement, modern and not spam the entire network log!

I'd personally love to implement that, if you're too lazy.

**Comment by themoonisacheese** [comment]
Because i have no clue how to use them.
Feel free to use them.

Le sam. 18 janv. 2020 à 19:03, Emil Albrecht <notifications@github.com> a
écrit :
