### ISSUE TITLE
Cant start queue

### ISSUE THREAD

**Issue by TheMegaBlaze** [themoonisacheese/2bored2wait#383]
2b2t is currently offline. Trying to reconnect. But 2b2t is online.

**Comment by TheMegaBlaze** [comment]
> 2b2t в настоящее время отключен. Пытаюсь подключиться снова. Но 2b2t находится в сети.

(restart was 1 day ago)

**Comment by rob9315** [comment]
try restarting the program, your computer or possibly your router. if nothing fixes the problem make sure you don't have a firewall misconfiguration issue. If nothing helps, maybe try your luck with the [rewrite](https://github.com/rob9315/2b2wTS) of this project
