### ISSUE TITLE
Is it possible to run 2bored2wait on the server computer and connect to your own computer according to the time?

### ISSUE THREAD

**Issue by ObsidianOption** [themoonisacheese/2bored2wait#397]
Is it possible to run 2bored2wait on the server computer and connect to your own computer according to the time?
idk

**Comment by czho** [comment]
yea of course thats what a vps is

**Comment by ObsidianOption** [comment]
Azure B1s 
cpu 1 core 1gb ram
ubuntu 20.14 lts

**Comment by KozmikNano** [comment]
> Is it possible to run 2bored2wait on the server computer and connect to your own computer according to the time?
> idk

Yes this is possible. If you would like a walkthrough on how to do this pls join the discord server and then ping @2bored2waitsupport
