### ISSUE TITLE
IP or Username whitelist

### ISSUE THREAD

**Issue by 20plays** [themoonisacheese/2bored2wait#398]
Hello, using this program could be rather insecure due to the fact that anyone on the network or anyone on the internet (if the proxy is port forwarded) can join this server and play 2b on your account.

Could a feature be added where you can only play with the account linked/configured to/in the proxy, or an IP whitelist feature? Thanks lots!

**Comment by KozmikNano** [comment]
Good point m, I will definitely be looking into this!

**Comment by MrGeorgen** [comment]
there is a [whitelist config option](https://github.com/themoonisacheese/2bored2wait/blob/f146ee7bbd1a12635a27eda15886e1760aa27b3e/config/default.json#L40). ip whitelist however is not implemented

**Comment by VoicelessRoar** [comment]
On Linux, just use UFW.

**Comment by 20plays** [comment]
> there is a [whitelist config option](https://github.com/themoonisacheese/2bored2wait/blob/f146ee7bbd1a12635a27eda15886e1760aa27b3e/config/default.json#L40). ip whitelist however is not implemented

Thanks!



> On Linux, just use UFW.

Would work if I didn't use the vps for other things, thank you for the help

**Comment by 20plays** [comment]
> > there is a [whitelist config option](https://github.com/themoonisacheese/2bored2wait/blob/f146ee7bbd1a12635a27eda15886e1760aa27b3e/config/default.json#L40). ip whitelist however is not implemented
> 
> Thanks!
> 
> > On Linux, just use UFW.
> 
> Would work if I didn't use the vps for other things, thank you for the help

Wow, am I dumb. Can just whitelist that one port to the one address. Thank you both for your time.

**Comment by KozmikNano** [comment]
Closing becuase it was resolved.
