### ISSUE TITLE
I can't start queueing 

### ISSUE THREAD

**Issue by MellDa1024** [themoonisacheese/2bored2wait#40]
err Error: getaddrinfo ENOTFOUND authserver.mojang.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'authserver.mojang.com'
}

error says this when i press start queueing.
what should i do?
(My secrets.json are right)

**Comment by themoonisacheese** [comment]
it looks like a temporary problem with mojang's authentification servers. try again later.

**Comment by MellDa1024** [comment]
Actually it happened 2 days ago :( should i wait more?

**Comment by themoonisacheese** [comment]
it should be fine by now. if you can connect without it, you should be able to connect with it.

**Comment by MellDa1024** [comment]
nevermind, i can connect 2b2t with minecraft client, i can login in minecraft.net, but i can't use 2B2W.
