### ISSUE TITLE
Kicks me out when I try to join 2b2t

### ISSUE THREAD

**Issue by Fantoscope** [themoonisacheese/2bored2wait#402]
When I try to join 2b2t It disconnects me and puts me back at the start of the queue. Any suggestions on what I should do?

**Comment by KozmikNano** [comment]
Are you connecting to the server (2b2t.org) or the proxy?

**Comment by Fantoscope** [comment]
2b2t.org depressingly

**Comment by Fantoscope** [comment]
Where do I find the proxy?

**Comment by KozmikNano** [comment]
If you are playing Minecraft on the same computer you are hosting 2bored2wait then connect to `localhost` if not you need to find the ip…

**Comment by Fantoscope** [comment]
If im running it on a raspberry pi and I want to connect from my main PC do i need to use localhost or my IP

**Comment by KozmikNano** [comment]
You need to use the ip. On your pi run the command `hostname -i` That is the ip you will want to use.

**Comment by KozmikNano** [comment]
localhost (as the name implies) is for when your locally hosting something on that same pc. Then there are two other ip adress types that common user should know about:
Public Ip- the things everyone can see if they aren’t on your WiFi 
Private Ip- Stiff that only people on your WiFi can see.

In this case I believe your pi and main pc are on the same network so using the private ip is just fine!

**Comment by Fantoscope** [comment]
Aight thanks bro

**Comment by KozmikNano** [comment]
No problem :)
