### ISSUE TITLE
problem when starting the queue

### ISSUE THREAD

**Issue by xyr3x0** [themoonisacheese/2bored2wait#404]
after doing the microsoft login into my account the usual "Finished setting up 2b2w. Type 'Start' to start the queue." comes up but after i type start i get a long message that reads:

$ (node:6375) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at Object.authenticate (/Users/.../.../2bored2wait-master/node_modules/minecraft-protocol/src/client/microsoftAuth.js:37:29)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6375) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6375) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

what should I do?
I'm on the latest macos

**Comment by KozmikNano** [comment]
This is a known issue and will be fixed soon.

**Comment by xyr3x0** [comment]
Oh ok cool

**Comment by KozmikNano** [comment]
Seems to still not work, I will do some more testing…

**Comment by KozmikNano** [comment]
Alright, i have done more test and the problem seems to no longer exist!
