### ISSUE TITLE
cannot run it in ARM Devices

### ISSUE THREAD

**Issue by nooberman12121** [themoonisacheese/2bored2wait#414]
when i try to run it, it gives me this error

-bash: ./2bored2wait-linux-x86-3.0.0: cannot execute binary file: Exec format error

i am running rapbian on a raspberry pi 4
i am accessing it through a SSH program, "putty"

**Comment by KozmikNano** [comment]
Please use the other install method instead.

**Comment by nooberman12121** [comment]
what other install method

**Comment by KozmikNano** [comment]
https://github.com/themoonisacheese/2bored2wait#other-platforms-including-arm--raspberry-pi

**Comment by KozmikNano** [comment]
Sorry I miss clicked

**Comment by nooberman12121** [comment]
ty
