### ISSUE TITLE
SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by nooberman12121** [themoonisacheese/2bored2wait#415]
(This was all done on a raspberry pi through SSH)

Error when i use the command npm start in the 2b2w directory:

pi@raspberrypi:~/2bored2wait $ npm start

> 2bored2wait@3.0.0 start
> node check.js

Please wait...
(node:15169) UnhandledPromiseRejectionWarning: /home/pi/2bored2wait/main.js:85
                dc.login(discordBotToken??config.get('BotToken')).catch(()=>{
                                         ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at start (/home/pi/2bored2wait/check.js:58:9)
    at /home/pi/2bored2wait/check.js:50:17
    at Array.every (<anonymous>)
(node:15169) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15169) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by KozmikNano** [comment]
Did you do `npm install` before running?

**Comment by rob9315** [comment]
Your node version is too old, please upgrade to v16

**Comment by KozmikNano** [comment]
> Your node version is too old, please upgrade to v16

I would check out nvm to install node 16. Makes it super easy and quick to setup.
