### ISSUE TITLE
How does the pos in queue work?

### ISSUE THREAD

**Issue by ThnksCJ** [themoonisacheese/2bored2wait#422]
im making a bot and i want the pos in queue and estimated time is there a simplifyed code of how it works?

**Comment by KozmikNano** [comment]
There is indeed a output of the time and queue! Most of the time generation vars can be found around here: https://github.com/themoonisacheese/2bored2wait/blob/109cfbb6a1ba437dd2ada9999bc27d91e48509c7/main.js#L210 just look through the function and you may be able to find what you are looking for.

**Comment by KozmikNano** [comment]
Glad I could help, good luck on your future development on your bot and enjoy the rest of your week!
