### ISSUE TITLE
socketClosed

### ISSUE THREAD

**Issue by ItsOnlyMyUsername** [themoonisacheese/2bored2wait#428]
Some time after launch, I sometimes get socketClosed. It just throws me out, sometimes it happens right while waiting in queue. I received information from the vps provider that there were no failures with the Internet. I also added  client.on('kicked') handler to the script and I get {"text":"§6You have lost connection to the server"} there.

**Comment by KozmikNano** [comment]
Try hosting on your own computer to see if it’s indeed the vps being the fault.

**Comment by ItsOnlyMyUsername** [comment]
No, it's the same on the local machine. Hmm, I also noticed that when I run 3 accounts on different machines, all 3 get socketClosed at the approximate time. I can not understand what it is connected with.

**Comment by KozmikNano** [comment]
Do you share the ip’s with other people?

**Comment by ItsOnlyMyUsername** [comment]
wdym?

**Comment by ItsOnlyMyUsername** [comment]
if you have ip machines - no. i used 2 vps and my local machine. On personal accounts purchased from Mojang

**Comment by KozmikNano** [comment]
Hmmm, so what account type are they? (Microsoft or Mojang)

**Comment by ItsOnlyMyUsername** [comment]
Microsoft.

**Comment by ItsOnlyMyUsername** [comment]
I would also like to clarify, I load new chunks, and I sometimes chat. Kicks not for afk.

**Comment by themoonisacheese** [comment]
Please check your hacked client. During testing I was often kicked because my client was outdated and hack methods were being detected. Please also make sure that you haven't removed the no-pass filters on the proxy.

For example, minecraft-protocol will automatically respond to keep-alive packets, but will also forward them to the client by default, which prompts the client to respond a second time, leading to a kick after some time playing.

**Comment by ItsOnlyMyUsername** [comment]
After testing for several hours, I can say that I get socketClosed even without a hacked client, and without logging into the game from the client at all. packet filters are present. My first server is in the Netherlands, the second in Russia. Could it be a ping issue? He sometimes earns a mark of 100.

> Пожалуйста, проверьте взломанный клиент. Во время тестирования меня часто кикали, потому что мой клиент устарел и выявлялись методы взлома. Также убедитесь, что вы не удалили непропускающие фильтры на прокси-сервере.
> 
> Например, minecraft-протокол будет автоматически отвечать на пакеты поддержки активности, но также будет пересылать их клиенту по умолчанию, что побуждает клиента ответить во второй раз, что приводит к кику после некоторого времени игры.

**Comment by nickcat325** [comment]
Update 2b2w then `run npm update && npm start`

**Comment by KozmikNano** [comment]
> After testing for several hours, I can say that I get socketClosed even without a hacked client, and without logging into the game from the client at all. packet filters are present. My first server is in the Netherlands, the second in Russia. Could it be a ping issue? He sometimes earns a mark of 100.

Are you still having this issue?

**Comment by KozmikNano** [comment]
If you are feel free to open!
