### ISSUE TITLE
Error when trying to start 2b2w

### ISSUE THREAD

**Issue by jameshackerbond** [themoonisacheese/2bored2wait#429]
> 2bored2wait@3.0.5 start
> node check.js

Please wait...
(node:78549) UnhandledPromiseRejectionWarning: /home/debian/2bored2wait/main.js:85
                dc.login(discordBotToken??config.get('BotToken')).catch(()=>{
                                         ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at start (/home/debian/2bored2wait/check.js:58:9)
    at /home/debian/2bored2wait/check.js:50:17
    at Array.every (<anonymous>)
(node:78549) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:78549) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by KozmikNano** [comment]
Delete your config and try a different bot token. If the issue persists try it without the bot token.

**Comment by jameshackerbond** [comment]
> Delete your config and try a different bot token. If the issue persists try it without the bot token.

iroot@vps-54b17f69:/home/debian/2bored2wait-3.0.5# npm start

> 2bored2wait@3.0.4 start
> node check.js


                                                                                                                       ╭───────────────────────────────────╮
                                                                                                                       │                                   │
                                                                                                                       │   New Update Available! → 3.0.5   │
                                                                                                                       │                                   │
                                                                                                                       ╰───────────────────────────────────╯

To continue type 1. To edit settings type 2. 1
Please wait...
/home/debian/2bored2wait-3.0.5/main.js:85
                dc.login(discordBotToken??config.get('BotToken')).catch(()=>{
                                         ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at start (/home/debian/2bored2wait-3.0.5/check.js:58:9)
    at /home/debian/2bored2wait-3.0.5/check.js:41:25
    at Interface._onLine (readline.js:327:5)
npm ERR! code 1
npm ERR! path /home/debian/2bored2wait-3.0.5
npm ERR! command failed
npm ERR! command sh -c node check.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-05-11T12_39_46_817Z-debug.log
root@vps-54b17f69:/home/debian/2bored2wait-3.0.5#

**Comment by KozmikNano** [comment]
What version node are you using?

**Comment by Edouard127** [comment]
@jameshackerbond Your error means you're running a version of node. js that does not support nullish coalescing.
I recommend you using Node 14, Node 16.6 (for discord v13) or higher, I am not sure of the exact version, so you can test with Node 14, 16.6 and so on

**Comment by KozmikNano** [comment]
> @jameshackerbond Your error means you're running a version of node. js that does not support nullish coalescing.
> I recommend you using Node 14, Node 16.6 (for discord v13) or higher, I am not sure of the exact version, so you can test with Node 14, 16.6 and so on

Node 14-to the latest works and we use discord v12 (might update later)
