### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by txst54** [themoonisacheese/2bored2wait#43]
I started the proxy and entered my email and password but I recieved this error when I typed 'npm start'
events.js:180
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn cmd',
  path: 'cmd',
  spawnargs: [ '/c', 'start', '""', '/b', 'http://localhost:80' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 2bored2wait@1.0.0 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 2bored2wait@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wang1\AppData\Roaming\npm-cache\_logs\2020-02-23T03_03_20_599Z-debug.log

**Comment by themoonisacheese** [comment]
are you sure you've ran `npm install`? there are dependencies that need to be installed first.

**Comment by txst54** [comment]
Yes I ran npm install before npm start but the error still occurs

**Comment by themoonisacheese** [comment]
please try setting the web port to something higher than 2000 and try again.

**Comment by txst54** [comment]
I tried using netstat -an and used the port for 127.0.0.1 as the web port but it did not work. The web port was also higher than 2000. The same error occurred again.

**Comment by txst54** [comment]
It worked after I disabled the open browser on start function in config.json and I manually accessed the localhost in my browser. Thanks!

**Comment by themoonisacheese** [comment]
cool. just for the future, ports displayed by netstat -an are the ports currently in use and you specifically need to avoid using them for a new connection.

do you happen to be using a web browser that is neither firefox or chrome?
