### ISSUE TITLE
new queue system

### ISSUE THREAD

**Issue by 1drw** [themoonisacheese/2bored2wait#430]
2b has updated to a new queue system and it no longer shows the queue number on tab, resulting in 2b2w being unable to get the queue number to display in the window

it still queues you but u cant tell where u are in queue without connecting to localhost

**Comment by KozmikNano** [comment]
As soon as my school year is done I will look into this :3

**Comment by nickcat325** [comment]
This is going to be difficult to fix because the code that controls this has not been updated in a long. I found the problem. it's main.js line 223.

**Comment by KozmikNano** [comment]
This may be easier then we think, we just have to update and reconfigure the requests.
