### ISSUE TITLE
connection refused

### ISSUE THREAD

**Issue by neilhuang007** [themoonisacheese/2bored2wait#433]
ECONNREFUSED 127.0.0.1:443
2bored2wait-master % npm start

> 2bored2wait@3.0.7 start
> node check.js

node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: connect ECONNREFUSED 127.0.0.1:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 443
}

**Comment by KozmikNano** [comment]
Try running this with admin rights

**Comment by nickcat325** [comment]
Run `npm update`. If you are still having problems run `npm list` and post output. Also make sure 2b2w is up to date.

**Comment by KozmikNano** [comment]
Pls run npm —version

**Comment by neilhuang007** [comment]
emmm I don't have a web server running

**Comment by neilhuang007** [comment]
why tis it this?
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/Users/neilhuang007/—version'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []

**Comment by neilhuang007** [comment]
I do have the node package downloaded and runed

**Comment by neilhuang007** [comment]
ok I do fix this problem, I wish you can post the tutorial on the readme so that people have the same problem can solve it just by reading the readme

**Comment by KozmikNano** [comment]
It is tho, under manual install it has the instructions that work and have been tested! Glad you were able to fix your problem tho :)
