### ISSUE TITLE
Binaries may be broken!

### ISSUE THREAD

**Issue by KozmikNano** [themoonisacheese/2bored2wait#439]
I will test to see if it was just a bad apple or not after I merge the next pull request!

**Comment by themoonisacheese** [comment]
From what I can remember, the next version we use is a beta of 2.x, and now 3.x is out. If that is actual, upgrading is probably advisable.

**Comment by nickcat325** [comment]
Do you think my commit broke it? https://github.com/themoonisacheese/2bored2wait/commit/27a0d33ff4b617c706142ee9065d061bb8739e0a It only started happening when I made that commit.

**Comment by KozmikNano** [comment]
No no no, this issue is caused by us trying to make  binaries for node 16. rob discovered that node 14 is the maximum for nexe

**Comment by rob9315** [comment]
I am switching the entire release workflow to be manually triggered and using `vercel/pkg` in favor of `nexe`, they have prebuilt binaries for recent node versions and seem to be faster

**Comment by rob9315** [comment]
@themoonisacheese take a look at #440

**Comment by rob9315** [comment]
fixed
