### ISSUE TITLE
The "Restart the queue if you're not connected at the end of it" button doesn't work

### ISSUE THREAD

**Issue by ChaosSilenceHD** [themoonisacheese/2bored2wait#44]
So when I go to school and leave the queue running to hope that I'm in a lower number than before, since it keeps running, but when I come back, the queue is disconnected and I need to turn it on again.
Does this have something to do with server restarts or is it just a bug of some kind? And if it is because of restarts, how do I start it again while being absent?

**Comment by themoonisacheese** [comment]
if the server restarts, the queue is supposed to log back in but sometimes it can't.
if you open the web port on your router, you should be able to navigate to your public IP address and control the proxy from there. please use a password when doing this.

you can see your public ip adress at https://www.whatismyip.com/ .
you can navigate to the web page by going to http://ip-goes-here:port-goes-here.
