### ISSUE TITLE
how to use the Mac version?

### ISSUE THREAD

**Issue by neilhuang007** [themoonisacheese/2bored2wait#442]
I can't open the file, can you link the app or anything that opens the Mac version file?

**Comment by KozmikNano** [comment]
Hey! At the current moment the binaries are broken, please use the manual install meathod

**Comment by KozmikNano** [comment]
> npm update

Instead of update you can just run npm install that way we can ensure all the packages you install are the correct version. We have specivide specific versions of packages and updates like to break the code!

**Comment by nickcat325** [comment]
> Instead of update you can just run npm install that way we can ensure all the packages you install are the correct version. We have specivide specific versions of packages and updates like to break the code!

You're right, forgot to mention `npm install` . `npm update` by it's self might not install required packages.

**Comment by neilhuang007** [comment]
ok thank you guys for replying my issue, I've never ever seen a issue replied in just a few hours continuously, and I do figure out how to use the Mac version
