### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by EbatteSratte** [themoonisacheese/2bored2wait#443]
crash when i choose continue type 1.  or To edit settings type 2.  i send 2 the press enter and crash

**Comment by EbatteSratte** [comment]
> May i please have the log?
how?

**Comment by KozmikNano** [comment]
This is becuase your haven’t made a config yet, there is a bug right now where it will show that message even when you have the latest version. Please hit 1 to continue, there it will take you through the steps to install!

**Comment by EbatteSratte** [comment]
and i made the config yet

**Comment by EbatteSratte** [comment]
3.0.5 work

**Comment by nickcat325** [comment]
Are you using the manual install or binary(exe/application)?

**Comment by nickcat325** [comment]
The binaries break sometimes. You can try the the manual install [here](https://github.com/themoonisacheese/2bored2wait#other-platforms-including-arm--raspberry-pi). It's not a perfect solution but it works.

**Comment by KozmikNano** [comment]
I am working on a fox as we speak, please bare with me as this bug is annoying af

**Comment by KozmikNano** [comment]
Fixed with #446
