### ISSUE TITLE
problem with starting the queue with docker script

### ISSUE THREAD

**Issue by yakovleval** [themoonisacheese/2bored2wait#445]
i'm trying to run the script with docker by this command:
`docker run -i -p 8080:8080 -p 25565:25565 -e NODE_CONFIG='{"username":"user@domain.com","mcPassword":"password","updatemessage":"n","BotToken":""}' 2bored2wait/2bored2wait:latest`
(of course i'm using my credentials in `NODE_CONFIG` argument). Script starts up normally, but when i start the queue the script crashes with following message:
```
Finished setting up 2b2w. Type 'Start' to start the queue.
$ start
Queue is starting up
$ Error: Invalid credentials. Invalid username or password.
    at call (/srv/app/node_modules/yggdrasil/src/utils.js:35:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async auth (/srv/app/node_modules/yggdrasil/src/Client.js:18:12)
```
even though my credentials are right. I guess there may be a parsing bug or smth similar because when i create a `local.json` file with my credentials in it and build a docker image from the sources it doesn't crash and works normally.

**Comment by KozmikNano** [comment]
Remove your password and rerun

**Comment by yakovleval** [comment]
ok it doesn't crush now but now it's just like this:
```
Please wait...
Finished setting up 2b2w. Type 'Start' to start the queue.
$ start
Queue is starting up
$ update
Position: None 
 Estimated time until login: None
Position: None  Estimated time until login: None
```

**Comment by nickcat325** [comment]
Hmmm, we'll look into this.

**Comment by KozmikNano** [comment]
Are you using Microsoft or mojang?

**Comment by yakovleval** [comment]
Microsoft

**Comment by KozmikNano** [comment]
Ok I see the issue now, when you loged I’m the proxy think you are using mojang. You must specify that you are using Microsoft or you won’t be fully logged in!

**Comment by KozmikNano** [comment]
At the current moment the docker image is outdated and I don’t believe it has a option for that. However I am going to be fixing that soon!

**Comment by KozmikNano** [comment]
Alright, so I have fixed this and updated the documentation, just waiting to push the pull request! #457
