### ISSUE TITLE
Problem with program, cant open it

### ISSUE THREAD

**Issue by Marfei4ik** [themoonisacheese/2bored2wait#448]
(version 3.1.1) When I open the program, it opens for 1 second and then immediately close, 
But in version **3.0.8** everything works well.

**Comment by KozmikNano** [comment]
What operating system?

**Comment by rob9315** [comment]
we found the issue, @KozmikNano will implement a fix.
this only happens with existing configurations pre-v3.1.0

**Comment by Marfei4ik** [comment]
> What operating system?

Windows 10

**Comment by Marfei4ik** [comment]
> please try v3.1.0, that might help us find the issue

I downloaded version 3.1.0 and it works, also I downloaded version 3.1.2 and it works too, the error is solved
