### ISSUE TITLE
Cant start the program on my raspberry pi 3B+

### ISSUE THREAD

**Issue by somethingsleepy** [themoonisacheese/2bored2wait#454]
When i run the command `npm start` after installing nodejs... and running `npm install` and `npm update` i get the error   `SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 2bored2wait@3.1.3 start: `node check.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the 2bored2wait@3.1.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above. with the debug file being 
`  
` T13_17_45_697Z-`

debug.log                                                                                                    
0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
1 info using npm@7.5.2
2 info using node@v12.22.5
3 timing config:load:defaults Completed in 12ms
4 timing config:load:file:/usr/share/nodejs/npm/npmrc Completed in 15ms
5 timing config:load:builtin Completed in 16ms
6 timing config:load:cli Completed in 12ms
7 timing config:load:env Completed in 4ms
8 timing config:load:file:/home/sleepy/2bored2wait/.npmrc Completed in 2ms
9 timing config:load:project Completed in 6ms
10 timing config:load:file:/home/sleepy/.npmrc Completed in 1ms
11 timing config:load:user Completed in 2ms
12 timing config:load:file:/etc/npmrc Completed in 1ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 2ms
15 timing config:load:validate Completed in 2ms
16 timing config:load:setUserAgent Completed in 4ms
17 timing config:load:setEnvs Completed in 7ms
18 timing config:load Completed in 69ms
19 verbose npm-session d004d6bd61328a7a
20 timing npm:load Completed in 130ms
21 timing command:run-script Completed in 603ms
22 timing command:start Completed in 626ms
23 verbose stack Error: command failed
23 verbose stack     at ChildProcess.<anonymous> (/usr/share/nodejs/@npmcli/promise-spawn/index.js:64:27)
23 verbose stack     at ChildProcess.emit (events.js:314:20)
23 verbose stack     at maybeClose (internal/child_process.js:1022:16)
23 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
24 verbose pkgid 2bored2wait@3.1.3
25 verbose cwd /home/sleepy/2bored2wait
26 verbose Linux 5.15.32-v7+
27 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
28 verbose node v12.22.5
29 verbose npm  v7.5.2
30 error code 1
31 error path /home/sleepy/2bored2wait
32 error command failed
33 error command sh -c node check.js
34 verbose exit 1`                                                                                       
does anyone know how i can fix this?

**Comment by KozmikNano** [comment]
Please update your node to v16 or higher

**Comment by somethingsleepy** [comment]
That resolved the Issue. Thx man
