### ISSUE TITLE
queue ends at one, and just restarts

### ISSUE THREAD

**Issue by Kaixvny** [themoonisacheese/2bored2wait#456]
i had 2b2w working and as soon as it hit pos 5 i joined, and at pos 1, it waited for a bit and then just restarted to last position!

is this is a issue cause i didnt install mcproxy yet? (i dont know if i need it but i should ask before i try to wait 5 hours again)

**Comment by nickcat325** [comment]
I'll look into it. I can't promise i'll be able to fix it.

**Comment by KozmikNano** [comment]
> i had 2b2w working and as soon as it hit pos 5 i joined, and at pos 1, it waited for a bit and then just restarted to last position!
> 
> is this is a issue cause i didnt install mcproxy yet? (i dont know if i need it but i should ask before i try to wait 5 hours again)

You don’t need to install mcproxy as it comes with the basic install methods and the binaries! Please try again and tell me how it goes. Are you by any chance using the web pannel?

**Comment by nickcat325** [comment]
This should be fixed with the new update.

**Comment by KozmikNano** [comment]
This was hopefully fixed with #452 Please reopen if the issue persists!
