### ISSUE TITLE
Configuration Questions

### ISSUE THREAD

**Issue by Akinatron** [themoonisacheese/2bored2wait#459]
1) If I activate antiAFK, does the program leave the connected character for a while until I connect?

2) What can I do in the AntiAFK config section?

**Comment by KozmikNano** [comment]
> * If I activate antiAFK, does the program leave the connected character for a while until I connect?

AntiAFK will control your character until the antiAntiAfk kicks you (or until you reconnect)
> * What can I do in the AntiAFK config section?

<https://github.com/themoonisacheese/2bored2wait/issues/388#issuecomment-940465931>
