### ISSUE TITLE
webserver issue

### ISSUE THREAD

**Issue by eylon707** [themoonisacheese/2bored2wait#463]
whenever i enter the url localhost:8080 the program closes by itself and shuts down the queue and entering the server localhost in minecraft doesnt do anything this is probably retarded af and im doing something wrong but i would like help thx

**Comment by KozmikNano** [comment]
I believe I helped you in the discord server!

**Comment by rob9315** [comment]
the single executable version does not have support for the webserver, closing this as it's a known issue but no one is writing a fix.

for future readers:
if you ran into this issue, use the manual install method instead or feel free to contribute a fix

**Comment by AntiCheap** [comment]
Can someone explain the issue?
