### ISSUE TITLE
cant type start

### ISSUE THREAD

**Issue by Marfei4ik** [themoonisacheese/2bored2wait#465]
when i trying to type "start", i having a error:
![image](https://user-images.githubusercontent.com/101808859/178486536-4587ce90-d0aa-4664-b995-ddae4163f9b1.png)

**Comment by rob9315** [comment]
something is wrong with your account, check if you can sign in with the credentials at https://minecraft.net and double-check they are correct in your config file at `C:\Users\USERNAME\AppData\Roaming\2bored2wait\Config\`

**Comment by rob9315** [comment]
probably needs a nicer error message but no real problem with 2bored2wait, closing
