### ISSUE TITLE
Crash in queu and cycle infinite.

### ISSUE THREAD

**Issue by bastianmarin** [themoonisacheese/2bored2wait#466]
I left a microsoft account queuing at one point this happened and I stayed in an infinite loop trying to reconnect.

![Sin título](https://user-images.githubusercontent.com/55340002/179367452-9648c11d-f535-439c-99ee-10a0248f57cb.png)

**Comment by KozmikNano** [comment]
@rob9315 Have you seen this before?

**Comment by nickcat325** [comment]
[@bastianmarin](https://github.com/themoonisacheese/2bored2wait/issues/466#issue-1306872573) I would go through your power settings.
