### ISSUE TITLE
ELIFECYCLE error when running npm start

### ISSUE THREAD

**Issue by FluddTheWadder8** [themoonisacheese/2bored2wait#47]
I get this error when running npm start.
Does not matter if openBrowserOnStart is set to true or false.
![error](https://user-images.githubusercontent.com/37462865/76851758-d37de080-6817-11ea-9fc6-95dda61b6ae7.PNG)

**Comment by themoonisacheese** [comment]
try changing the web port to something above 1024.
if that doesn't work, change every instance of '0.0.0.0' to '127.0.01' in main.js.

**Comment by dommilosz** [comment]
Run it as admin
