### ISSUE TITLE
why don't we use slash command?

### ISSUE THREAD

**Issue by kdh8219** [themoonisacheese/2bored2wait#480]
![2022-09-01-01-18-50](https://user-images.githubusercontent.com/65698239/187729098-01cb860e-9068-40ce-86b9-1c7e4cd9d1a2.gif)

**Comment by KozmikNano** [comment]
Becuase i haven’t added it yet. I just recently update to 1.16 please give me time to add slash commands. Also I have school so I need a lot of time XD
