### ISSUE TITLE
error, help please

### ISSUE THREAD

**Issue by Marfei4ik** [themoonisacheese/2bored2wait#481]
![image](https://user-images.githubusercontent.com/101808859/188696650-3bc78afe-42a5-45fc-86f1-07a9f9ae0c5a.png)

**Comment by themoonisacheese** [comment]
EADDRINUSE means you already have a server running on port 8080. maybe 2b2w  is   already running, or you are hosting a website on that port (some vscode extensions do that).
closing as user error.

**Comment by KozmikNano** [comment]
You can open default.json and change your port
