### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Dino-log** [themoonisacheese/2bored2wait#487]
![image](https://user-images.githubusercontent.com/66836260/191497968-9bbecbb7-84b1-409e-a76e-a5b03c2e077d.png)

**Comment by Dino-log** [comment]
![image](https://user-images.githubusercontent.com/66836260/191498795-c61e12db-0de2-49f2-b1c7-68e2d0347cba.png)

**Comment by rob9315** [comment]
the webserver doesn't work on the executable version, use instead the manual installation method or feel free to contribute a fix for this issue
