### ISSUE TITLE
No Commands Recognized

### ISSUE THREAD

**Issue by JaCsi-obre** [themoonisacheese/2bored2wait#495]
![Bot](https://user-images.githubusercontent.com/60991969/194448472-bd105980-a8bf-4701-9225-532fede0c5c8.jpg)
![Discord](https://user-images.githubusercontent.com/60991969/194448473-84032c1f-ac90-4a0f-a6a4-f23e765c5955.jpg)

I'm using 2 accounts and 1 discord bot, everything worked good for me until I updated from 3.0.5 to 3.3.0.

the issue lies with no commands being recognized. I can still see my place in queue in from the bots Rich Presence
I've just been looking through and copying over my config file info to the newly generated ones for each update.
Should I try adding a new bot?

I'm still getting discord notifications when I'm close to end of queue (mine is set to pos 20).
But I've also been getting notified when at position zero when in still well away from both these places in queue, randomly. unstable internet? bugs out for a second?
![2022-10-06 21_49_15-@2b2w - Discord](https://user-images.githubusercontent.com/60991969/194449307-467524cc-fabf-469e-8318-5cc406339aef.jpg)
![2022-10-06 21_51_41-C - VNC Viewer](https://user-images.githubusercontent.com/60991969/194449636-bb4376b4-f28d-43ec-8dca-d8ee72c5e7d4.jpg)

**Comment by Jmooroof** [comment]
I have the same issue (using one account and one bot)

**Comment by nickcat325** [comment]
This is my code messing up. 2b2t gets queue position from the tab list. When main is offline the position of the number is in a different place. Showing 0 in queue. Is this a major problem?

**Comment by JC-Giga** [comment]
> This is my code messing up. 2b2t gets queue position from the tab list. When main is offline the position of the number is in a different place. Showing 0 in queue. Is this a major problem?

I guess my main issue is getting notified
add an if somewhere or something to not give notification if == 0?

Any idea why I have no commands? that's the real problem for me.
Today, for some reason the discord bot broke. It was working a day or two earlier. nothing changed.

**Comment by ajddavid452** [comment]
I have this issue too

**Comment by nickcat325** [comment]
I got the packet now I need to make an algorithm that finds the queue in both cases.

**Comment by nickcat325** [comment]
Done https://github.com/themoonisacheese/2bored2wait/pull/499/commits/cbd9e4da180248184693f29d86d773dcabd30d9c

**Comment by AntiCheap** [comment]
For people having trouble running commands, did you all run multiple accounts? How?

**Comment by rob9315** [comment]
closing this, regarding commands not being recognised this is probably #522, if not open a new issue
