### ISSUE TITLE
If the player doesn't connect to the proxy by the end of the queue, start over.

### ISSUE THREAD

**Issue by ca1ek** [themoonisacheese/2bored2wait#5]
I would like to be able to run this on my Raspberry Pi at all times, so that when I want to join 2b2t I've already made some progress in the queue

* Track position in queue
* If the position in queue is 1 and player hasn't connected yet, disconnect and reconnect again.

This way, the moment I decide to join 2b2t I'll probably have already made some progress in the queue.

**Comment by themoonisacheese** [comment]
A version that stores packets you missed and sends them back when you
connect is already in the works, but i've got exams at the moment.

Le jeu. 28 mars 2019 à 20:39, Dawid Pietrzak <notifications@github.com> a
écrit :

**Comment by ca1ek** [comment]
cool, but it's not what my feature has in mind. I don't want to be able to join after passing the queue, I want to stay in the queue but not join so the moment I do join I am somewhere in the 100s, not back at the end.

Also, rebroadcasting all packets might DoS the client if the player took a long time to join since you will send them all at once

**Comment by themoonisacheese** [comment]
added this in 925cb0ed80dde6280df988b4f0a3f59acfd08717
