### ISSUE TITLE
I cannot change accounts

### ISSUE THREAD

**Issue by HarryPotter42MC** [themoonisacheese/2bored2wait#501]
I put in the wrong account in the sign in process.
it went like this:
asked me for email in the 2bored2wait x64.exe
I put the wrong account email in
clicked on the link and pasted the code (I was logged on with the wrong account on microsoft live too)
now I can use 2b2w with my wrong account and not change it. help`?

**Comment by GentlemanMC** [comment]
your credentials are under C:\Users\USERNAME\AppData\Roaming\2bored2wait\Config\
edit the files there containing the wrong account and you should be good to go

**Comment by HarryPotter42MC** [comment]
> your credentials are under C:\Users\USERNAME\AppData\Roaming\2bored2wait\Config edit the files there containing the wrong account and you should be good to go

this is my file: the password is blank because I think I did the live.com give acces thing but does it work when I now change mail and insert my password (because maybe the code still thinks I used the link but not anymore)
{
  "accountType": "microsoft",
  "mcPassword": "",
  "username": "mymail@mail.com",
  "updatemessage": "Y",
  "BotToken": "ADJabhwjzdabWJdAWjzgd(its working)",
  "discordBot": true
}
