### ISSUE TITLE
Dependency issue. TypeError: registry.supportFeature is not a function

### ISSUE THREAD

**Issue by nickcat1** [themoonisacheese/2bored2wait#504]
When I connect with minecraft, I get this errer and Minecraft does not connect to the proxy. 2b2w does not crash. I think it's because i'm on Linux and registry.supportFeature seems to be for Windows. Idk.

```
TypeError: registry.supportFeature is not a function
    at toNotch (/home/nicholas/Documents/Code/2b2w/2bored2wait/node_modules/prismarine-item/index.js:51:20)
    at /home/nicholas/Documents/Code/2b2w/2bored2wait/node_modules/@rob9315/mcproxy/lib/packets.js:93:58
    at Array.map (<anonymous>)
    at generatePackets (/home/nicholas/Documents/Code/2b2w/2bored2wait/node_modules/@rob9315/mcproxy/lib/packets.js:93:44)
    at Conn.generatePackets (/home/nicholas/Documents/Code/2b2w/2bored2wait/node_modules/@rob9315/mcproxy/lib/conn.js:71:47)
    at Conn.sendPackets (/home/nicholas/Documents/Code/2b2w/2bored2wait/node_modules/@rob9315/mcproxy/lib/conn.js:67:14)
    at /home/nicholas/Documents/Code/2b2w/2bored2wait/main.js:343:9
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by nickcat325** [comment]
I've found 2 workarounds for this issue. I'm not sure what dependency change caused the issue but I know it's not just Linux with the problem.
Passover: use my code https://github.com/themoonisacheese/2bored2wait/pull/499 to get connection messages. Make sure you get the message "Queued for server main." and not "You are already queued to server main." If not restart 2b2w. When you are low in queue quit 2b2w and immediately join 2b2t directly.
Downgrade the dependencies: Download 2b2w 3.2.0. use `yarn install` then, `yarn start` optionally you can overwrite the main.js and check.js updates over this version.

**Comment by KozmikNano** [comment]
Do you think this may be a result of the latest comit?

**Comment by nickcat325** [comment]
It may be the latest comit. I'll have to see.

**Comment by nickcat325** [comment]
@KozmikNano Yup that was it. Reverting 2b2w to before https://github.com/themoonisacheese/2bored2wait/commit/4c9bc2a7ab92581b93805db1d16645edb1bc6dbe fixes the problem.

**Comment by KozmikNano** [comment]
Thanks! I will revert the dep change and update you when I have.

**Comment by KozmikNano** [comment]
There we go

**Comment by nickcat325** [comment]
> Nvm, I changed it back and it works just fine. I'm not sure what caused this.
@KozmikNano I meant to say that it wasn't minecraft-data. It was probably an unlocked dependency. I compared the yarn integrity and I see ~30 differences. Maybe an unlocked dependency change. I'm not sure. Anyways you can redo that change.
GitHub seems to have messed up the message order.

**Comment by KozmikNano** [comment]
Yes, I can revert back to the later version.
