### ISSUE TITLE
Bot stopped working enitrely

### ISSUE THREAD

**Issue by JaCsi-obre** [themoonisacheese/2bored2wait#505]
![2022-10-22 22_14_31-Window](https://user-images.githubusercontent.com/60991969/197369881-ea318e4f-f3d2-41b0-860a-78311b7d18ce.jpg)

I previously had been able to use commands in the bot, see my other issue report.

I during last runtime the computer was shutdown, turned it back on a day later and started the bot again
however, I got this error.

help pls? the notification of place in the queue is very convenient
I made a new bot token to try and troubleshoot but didn't change anything.

should I replace the discord.js file in reference?
I am able to use it when discord bot is disabled.

**Comment by nickcat325** [comment]
First, are you using the [executable/binary](https://github.com/themoonisacheese/2bored2wait#quick-install-64-bit-systems) or are you using the [manual Install](https://github.com/themoonisacheese/2bored2wait#manual-install-32-bit-systems-and-fallback-for-quick-install)?
If you are using the [manual Install](https://github.com/themoonisacheese/2bored2wait#manual-install-32-bit-systems-and-fallback-for-quick-install) try `npm install && npm update` in the 2B2W folder.

**Comment by Santiag09** [comment]
I had messed around with the code in mine once and now it doesn't work at all even after i reset it got a new installantion and everything
