### ISSUE TITLE
virus total flagged as a virus is this a mistake

### ISSUE THREAD

**Issue by TheDy1an** [themoonisacheese/2bored2wait#518]
was flagged as a Trojan.Agent.Win32.2853154 is this a mistake? Sorry for the bother if it is a false positive but would like answers.

**Comment by rob9315** [comment]
decide for yourself. the source is available, you can check how the binaries were produced. if you do not trust an executable, do not run it.

**Comment by themoonisacheese** [comment]
We "recently" changed nexe version ans if i was to guess malware devs tend to use such tools as well, leading to false positives. Nothing we can do on our end except send a nicely worded email to antivirus companies.

As always, use you brain on the internet. If your brain says no, then don't.
