### ISSUE TITLE
discord bot error

### ISSUE THREAD

**Issue by inchan1208** [themoonisacheese/2bored2wait#522]
![image](https://user-images.githubusercontent.com/75877181/210510748-f3a4204a-69dc-4576-ab8f-8a94108fcb45.png)
i send a command but the bot say error always

**Comment by Nishant1500** [comment]
I checked the source code and found this regex:

Seems like you need to pass something like this:
`start <number>:<number>` <- any number you want

**Comment by RexBluefox** [comment]
Thats not the problem. Any command returns not found. Even the help command

**Comment by Nishant1500** [comment]
Can you invite me to the testing server where the bot is right now?

**Comment by Ten2O** [comment]
Same issue, I think everyone has it.

**Comment by rob9315** [comment]
discord bots need to have the `Message Intent` to be able to read messages' contents. this can be enabled in the discord application portal. if you don't have this intent the bot receives an empty string and finds that it doesn't match any case so it points to the help section
