### ISSUE TITLE
Problem with my Accounts

### ISSUE THREAD

**Issue by TOBIBLASTER00912** [themoonisacheese/2bored2wait#529]
I want to change the minecraft account (Microsoft) but it doesnt let me! I tried to delete the settings and put the email in i wanted but it still uses the account of the other email! Pls help
Thx for reading

**Comment by JanCantCode** [comment]
have you attempted setting the values of default.json and local.json to {} and {}?

**Comment by TOBIBLASTER00912** [comment]
No but im trying it

**Comment by rob9315** [comment]
That will not work, the problem (i think) is related to the prismarine-js libraries we use for authentication caching the login tokens somewhere. That location seems to be somewhere within the `node_modules/prismarine-auth` folder.

**Comment by TOBIBLASTER00912** [comment]
Ahhh i see i tried it but now it keeps crashing
![16749086822193381659026435223020](https://user-images.githubusercontent.com/120951381/215266266-0bac0b0c-704e-4d2e-aa77-fe9e189c6b1f.jpg)

**Comment by TOBIBLASTER00912** [comment]
But do you have any ideas how can i fix this?

**Comment by rob9315** [comment]
The binaries have a lot of problems that the manual install doesn't have. do a manual install as described in the readme and see then

**Comment by TOBIBLASTER00912** [comment]
Ok thanks

**Comment by TOBIBLASTER00912** [comment]
I have a problem... I cant use git for some reason (srry for german picture) 
![16749092119248152970276072817747](https://user-images.githubusercontent.com/120951381/215266596-398c7333-3101-499b-84de-aa139d3e78e9.jpg)

**Comment by rob9315** [comment]
git and node don't come preinstalled with windows.

https://git-scm.com/
https://nodejs.org/en/

**Comment by TOBIBLASTER00912** [comment]
But i have both installed

**Comment by rob9315** [comment]
that means that they are not on your PATH, try restarting and if that doesn't work look into how to add stuff to your path in windows

**Comment by TOBIBLASTER00912** [comment]
Omg im so dumb i dont knew i had to install git AS A SETUP! i did only install the pack with npm install

**Comment by TOBIBLASTER00912** [comment]
It is still not working it uses the wrong account

**Comment by rob9315** [comment]
then the location where the tokens are stored was changed, try looking at your `.minecraft` folder, don't forget to enable hidden folders

**Comment by TOBIBLASTER00912** [comment]
Nope its not in the .minecraft folder

**Comment by TOBIBLASTER00912** [comment]
Is it possible that its not working because i accidentally saved the wrong email? I saved it and thats why i cant use my other

**Comment by rob9315** [comment]
assumptions are that you put the correct email into the config file, however we had multiple reports where changing the email in the config file didn't result in it changing the user who is logging in

**Comment by rob9315** [comment]
there should be a directory in `.minecraft` named `nmp-cache`, that one should contain the cached login data. deleting it should reset the behavior of 2b2w's microsoft login

**Comment by TOBIBLASTER00912** [comment]
Ok thanks

**Comment by TOBIBLASTER00912** [comment]
Yes it worked thank you so much!!
