### ISSUE TITLE
Error while running queue

### ISSUE THREAD

**Issue by lujo777** [themoonisacheese/2bored2wait#53]
err Error: Request blocked by CloudFlare                                                                           
    at /home/2b2t/node_modules/yggdrasil/lib/utils.js:45:19
    at /home/2b2t/node_modules/phin/lib/phin.min.js:1:1150
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

I installed it on my dedicated server.

**Comment by themoonisacheese** [comment]
sounds like a you problem
