### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by FlyingCraby** [themoonisacheese/2bored2wait#539]
$ [Error: EPERM: operation not permitted, open 'C:\WINDOWS\system32\2bored2wait.log'] {                                   errno: -4048,                                                                                                           code: 'EPERM',                                                                                                          syscall: 'open',                                                                                                        path: 'C:\\WINDOWS\\system32\\2bored2wait.log'                                                                        }       

I tried uninstalling and deleting the config file.

**Comment by FlyingCraby** [comment]
Please respond!

**Comment by AverageComet250** [comment]
Bit late, but this is an issue to do with you not being an administrator. Maybe install it somewhere else, like your docs folder.

**Comment by Amitie10g** [comment]
Supposing you're downloaded the executable (embedded script), the logs are written to the same directory of the executable. ¿In what way you're donwloaded and ran this?
