### ISSUE TITLE
mineflayer-anti-afk not working 

### ISSUE THREAD

**Issue by Goodgame322** [themoonisacheese/2bored2wait#542]
I have 2bored2wait set up on my raspberry pi, however, the anti-afk does not ever run before I connect or after I disconnect. (I confirmed this with an alt). I have 
```json
{
  "antiAntiAFK": { 
        "enabled": true,
        “config”: { 
             “actions”:  ['rotate', 'walk', 'jump', 'jumpWalk', 'swingArm', 'placeBlock', 'breakBlock'], 
              “chatting”: false
        }
    }
}
```
(the json formatting is right)
set in local.json.
Could someone please tell me what’s going wrong?

**Comment by rob9315** [comment]
I updated your comment, as now should be visible you are using the wrong quotes. Always edit the config files with a code editor and not a common text editor. Some recommendations for code editors: notepad++, vscode

**Comment by Goodgame322** [comment]
Thanks for responding
However, the smart quotes are not the issue. I typed that on my phone so sorry about that. I doing some testing right now and I think that the problem is in line 173 of main.js with !finishedqueue, as it works without it fine. I think this is because the queue never actually finishes and gets stuck on position 1 even when get into 2b2t.

**Comment by rob9315** [comment]
Feel free to try to fix it, this project would badly need bugfixing or a rewrite (which many people have already done).
