### ISSUE TITLE
Queue position broken

### ISSUE THREAD

**Issue by straboti** [themoonisacheese/2bored2wait#543]
When I strat the queue, this is what I see:
`P: 1228 E: 13h 22m - StraboCraft
P: 12 E: 0h 27m - StraboCraft
P: 115751 E: 40h 5m - StraboCraft
P: 115542 E: 40h 4m - StraboCraft
P: 116 E: 3h 27m - StraboCraft
P: 114 E: 3h 24m - StraboCraft
P: 112 E: 3h 21m - StraboCraft
P: 114917 E: 40h 2m - StraboCraft
P: 11478 E: 26h 13m - StraboCraft
P: 1145 E: 12h 59m - StraboCraft
P: 1056 E: 12h 34m - StraboCraft
P: 1054 E: 12h 33m - StraboCraft`

**Comment by Baitinq** [comment]
Can reproduce, 2b2t might have changed the version of the queue server or the viaversion protocol.

**Comment by themoonisacheese** [comment]
the proxy gets queue position from the tab list, ad the tab list has changed. as far as i can tell it stil lworks but simply reports the position wrong.
the P: indicated is actually the ETA field, as just a string of numbers, for example: 1054 = 10 min 54 seconds. will fix soonish.

**Comment by Baitinq** [comment]
I have fixed it on my fork, will send a PR tonight if it hasnt been fixed by then :)

**Comment by Baitinq** [comment]
Will do :)
