### ISSUE TITLE
Change the server and the version

### ISSUE THREAD

**Issue by ferzed** [themoonisacheese/2bored2wait#544]
I was able to change the server connection ip, but I couldn't change it.

I want to change the version in which I can enter, how can I do it?

**Comment by ferzed** [comment]
![image](https://user-images.githubusercontent.com/128242276/230175471-a2cb85cc-4d6a-4607-8c01-828e14d7c7bb.png)

**Comment by themoonisacheese** [comment]
using on a different server is not a supported use case.

once upon a time the proxy was so simple that simply changing the server address would be enough (hence the "is not 2b2t?" message) but nowadays almost all of the code relies on the target server being 1.12.2 and in a smaller capacity 2b2t.org to function. if you need to use this for another server, you will need to fork and change the code in significant ways.

**Comment by ferzed** [comment]
thanks!
