### ISSUE TITLE
cannot find module node:events

### ISSUE THREAD

**Issue by anhtlauncher** [themoonisacheese/2bored2wait#547]
tf this thing happened when i built the thing
send help xd
![image](https://user-images.githubusercontent.com/99712037/232082982-205240c0-c195-4b21-8d6a-b8b778fa0394.png)

but when i run it manually (node main.js) it worked perfectly :/
![image](https://user-images.githubusercontent.com/99712037/232083693-a6d98dae-9d31-41e7-a4a0-5f4a7d795290.png)

**Comment by ChillerDragon** [comment]
Maybe try moving the exe out of the build/ folder next to the node_modules folder.
Just a random guess :shrug: i do not have windows.

**Comment by rob9315** [comment]
building an executable has no advantages over just running it using the manual method, don't bother.
my guess is that it is packaging an older node version. `node:events` has not always existed, it was added in node 16. if you still want to get it working, try getting it to package using a newer version of node.
