### ISSUE TITLE
Getting 2bored2wait to work on termux

### ISSUE THREAD

**Issue by sebascontacto** [themoonisacheese/2bored2wait#551]
How can I setup the 2bored2wait on termux?

_Original question was edited to fit what the user is actually asking._

**Comment by KozmikNano** [comment]
Im sorry @sebascontacto I have no idea what or how termux works so I won't be able to help you. You will either have to wait until someone else assist you or ask on the discord server.

**Comment by nickcat325** [comment]
I tried Termux with no luck. I think you need root on the Android device. 2b2w works on UserLand, which can be downloaded from the Google play and F-Droid package managers. UserLand is based on Termux.

**Comment by themoonisacheese** [comment]
closig as unsupported use-case. if you can get it to work great, but please use other tools like the discord to ask and share tips on this subject.
