### ISSUE TITLE
suggestion: show chat in node terminal

### ISSUE THREAD

**Issue by AlexiDoesCode** [themoonisacheese/2bored2wait#57]
suggestion: show chat in node terminal

**Comment by klokwert** [comment]
I'm not 100% sure that this will work but here is my work:
99% sure this will work:
Place between line 198 and 199 this:
`console.log(JSON.parse(data.message));`
So you get [this](https://pastebin.com/raw/vtYCJGQt)

Or use this (this way is better):
98,9% sure this will work:
Place between line 198 and 199 this:
`logActivity(JSON.parse(data.message));`
So you get [this](https://pastebin.com/raw/f9K9ufjP)

**Comment by klokwert** [comment]
I've done some testing:
This is my result
Put between line 198 and 199:

`fixedchatmsg = JSON.parse(data.message)["text"];
if(JSON.parse(data.message)["extra"]){
JSON.parse(data.message)["extra"].forEach(function(entry) {
   fixedchatmsg = fixedchatmsg.concat(entry["text"]);
});}
console.log(fixedchatmsg);`

**Comment by klokwert** [comment]
You can also let it send all chat messages via discord but that gets messy:
`fixedchatmsg=JSON.parse(data.message).text,JSON.parse(data.message).extra&&JSON.parse(data.message).extra.forEach(function(e){fixedchatmsg=fixedchatmsg.concat(e.text)}),sendDiscordMsg(dcUser,"Chat","Received chat message:\n"+fixedchatmsg);`

**Comment by MrGeorgen** [comment]
> I've done some testing:
> This is my result
> Put between line 198 and 199:
> 
> `fixedchatmsg=JSON.parse(data.message).text,JSON.parse(data.message).extra&&JSON.parse(data.message).extra.forEach(function(e){fixedchatmsg=fixedchatmsg.concat(e.text)}),console.log(fixedchatmsg);`

make a pr if you want, but add config option for this

**Comment by rob9315** [comment]
This is a bad idea, as it will use excessive amounts of ram over time. If you still want this to exist, open a pr as MrGeorgen said and make it available as a config option
