### ISSUE TITLE
1.19 update

### ISSUE THREAD

**Issue by MrGeorgen** [themoonisacheese/2bored2wait#571]
I think a 1.19 update won't be that difficult, because pretty much the only thing that would break is mcproxy. Otherwise the only packet inspection is for getting the queue position. Everything else should work. Did someone try and know which errors occur?

**Comment by themoonisacheese** [comment]
Mainly the hold up is that none of the people who know enough to try care enough about playing 2b2t and / or this proxy to spend the time fixing it. The new rules, combined with this project already being on life support have all but sapped all want to fix it. As said before, PRs are welcome but i'm not going to do it, I've moved on to other projects.

**Comment by MrGeorgen** [comment]
Yeah even the interface is broke now, so I'm also not gonna do it
