### ISSUE TITLE
please do not quit proxy after the player logs off

### ISSUE THREAD

**Issue by xXxAaRkEtxXx** [themoonisacheese/2bored2wait#6]
i use that feature, it doesn't spawn me correctly but it works after walking with shift and clicking things for about 5 minutes even after afking while not being on the server

sorry for bad English xo

**Comment by themoonisacheese** [comment]
i'll make it an option. I didn't know that the world even loaded after a while.

**Comment by themoonisacheese** [comment]
in fact, I just won't quit at all. closing because no longer relevant
