### ISSUE TITLE
ELIFECYCLE error

### ISSUE THREAD

**Issue by BATTERYexe** [themoonisacheese/2bored2wait#60]
I have tried setting the text 0.0.0.0 to 1. whatever. I tried running administrator and i tried changing the port to above 1024. I changed it to 1048. Nothing works
![Annotation 2020-04-22 111315](https://user-images.githubusercontent.com/64132810/79964008-626ec000-848a-11ea-91d7-01d9d4384303.png)

**Comment by themoonisacheese** [comment]
enable file extension display, rename secrets.json.example to secrets.json.
