### ISSUE TITLE
Doesn't work with Node.js Webserver android. Please fix 

### ISSUE THREAD

**Issue by UltraRD** [themoonisacheese/2bored2wait#71]
![Screenshot_20200530-151709_dnodejs](https://user-images.githubusercontent.com/62796040/83322307-108b3800-a289-11ea-8ecd-9218ccad90fe.jpg)
![Screenshot_20200530-151647_dnodejs](https://user-images.githubusercontent.com/62796040/83322309-15e88280-a289-11ea-902a-14b613eb395a.jpg)
I'm running 2b2w on a Samsung A40s, using Node.js webserver Android, but it returned with these errors. Please tell me this is only a compatibility problem.

**Comment by UltraRD** [comment]
note, I'm running the newest version of NPM and Node.js

**Comment by UltraRD** [comment]
![Screenshot_20200530-154309_dnodejs](https://user-images.githubusercontent.com/62796040/83322726-b12f2700-a28c-11ea-99b6-cc6061dbb943.jpg)
I figured out the Minecraft protocol problem, but now it doesn't recognize the HTML syntax.

**Comment by themoonisacheese** [comment]
android is unsupported and there are no plans to support it.
