### ISSUE TITLE
Passwording the website

### ISSUE THREAD

**Issue by SpicyTorchic** [themoonisacheese/2bored2wait#8]
It might be a good suggestion to add a password in order to either access the website, or to click the "start queuing" button, forwarding the port to the internet means anybody could port scan you and go to the website and fiddle around with the button, and that just might not be something you want 👍 

Otherwise, thank you for such a wonderful program :)

**Comment by themoonisacheese** [comment]
done in 925cb0ed80dde6280df988b4f0a3f59acfd08717
