### ISSUE TITLE
npm install causes this:

### ISSUE THREAD

**Issue by awesomealgodoo** [themoonisacheese/2bored2wait#80]
C:\Users\bypassedit\Desktop>#!/bin/sh
'#!' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\bypassedit\Desktop>(set -o igncr ) 2>/dev/null  && set -o igncr; # cygwin encoding fix
The system cannot find the path specified.

C:\Users\bypassedit\Desktop>basedir=`dirname "$0"`
'basedir' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\bypassedit\Desktop>case `uname` in
'case' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\bypassedit\Desktop>*CYGWIN*) basedir=`cygpath -w "$basedir"`;;
'*CYGWIN*)' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\bypassedit\Desktop>esac
'esac' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\bypassedit\Desktop>NODE_EXE="$basedir/node.exe"
'NODE_EXE' is not recognized as an internal or external command,
operable program or batch file.
[ was unexpected at this time.

C:\Users\bypassedit\Desktop>if ! [ -x "$NODE_EXE" ]; then

Here are some details: I changed the npm file (not the npm.cmd) into a .bat file.

**Comment by themoonisacheese** [comment]
> Here are some details: I changed the npm file (not the npm.cmd) into a .bat file.
well there's your issue isn't it? the npm file is not made to run on bare batch.
