### ISSUE TITLE
running the proxy with npm start instigating unhandled error event exception (logs below)

### ISSUE THREAD

**Issue by DGKSK8LIFE** [themoonisacheese/2bored2wait#81]
```
> 2bored2wait@1.0.0 start /mnt/c/Users/tarek/code/2bored2wait
> node main.js

Username: events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 2bored2wait@1.0.0 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 2bored2wait@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-04T23_57_09_927Z-debug.log
```

**Comment by LoserWasTaken** [comment]
`Error: spawn cmd.exe ENOENT`
WSL issue, it thinks its running on windows and tries starting cmd which doesn't exist

**Comment by DGKSK8LIFE** [comment]
> WSL issue, it thinks its running on windows and tries starting cmd which doesn't exist

Weird. Running the linux version *should* work on WSL ubuntu.

**Comment by YeetyDankEngine** [comment]
> Weird. Running the linux version _should_ work on WSL ubuntu.
how do you know? also, are you using a virtualisation client other than Hyper-V?

**Comment by DGKSK8LIFE** [comment]
> > Weird. Running the linux version _should_ work on WSL ubuntu.
> 
> how do you know? also, are you using a virtualisation client other than Hyper-V?

I don't really. No at the time I was just using WSL IIRC.

**Comment by YeetyDankEngine** [comment]
I mean is there anything else installed

**Comment by DGKSK8LIFE** [comment]
What do you mean, "is there anything else installed"? @YeetyDankEngine

**Comment by YeetyDankEngine** [comment]
Doesn't matter.

> `Error: spawn cmd.exe ENOENT`
> WSL issue, it thinks its running on windows and tries starting cmd which doesn't exist

I believe that is a problem that only happens with WSL. Do you use WSL2?

**Comment by DGKSK8LIFE** [comment]
Yes. At the time I was using WSL2 @YeetyDankEngine

**Comment by YeetyDankEngine** [comment]
Well, I will test it on my machine and report back

**Comment by DGKSK8LIFE** [comment]
thanks

**Comment by YeetyDankEngine** [comment]
works fine for me

**Comment by DGKSK8LIFE** [comment]
weird.

**Comment by YeetyDankEngine** [comment]
the thing is, with my WSL, I set it up another way: instead of entering the username and password, I just did Ctrl+C so it exited and I had access to the root account

**Comment by DGKSK8LIFE** [comment]
Thanks. You too @YeetyDankEngine. Maybe I tried running it on a mounted drive instead of the root dir in wsl?

**Comment by YeetyDankEngine** [comment]
yea by default it runs in the mount

**Comment by YeetyDankEngine** [comment]
so do `cd ~`

**Comment by AverageComet250** [comment]
If this is resolved (using windows drive in /mnt is the issue and you just need to move into wsl home directory) then someone needs to close this as it's fixed.

**Comment by DGKSK8LIFE** [comment]
OK I can close but haven't personally tested it @AverageComet250

**Comment by YeetyDankEngine** [comment]
only close after issue is proved to be resolved

**Comment by DGKSK8LIFE** [comment]
I don't use wsl anymore. (i'm on linux) Could someone with a windows machine try?

**Comment by AverageComet250** [comment]
I'll do it later when I have time and post the results. I already have wsl2 setup and ready to go

**Comment by DGKSK8LIFE** [comment]
ty @AverageComet250

**Comment by YeetyDankEngine** [comment]
I ran the test from manjaro host into an debian VM into an arch VM into a windows VM.

**Comment by DGKSK8LIFE** [comment]
And everything worked for you? @YeetyDankEngine

**Comment by YeetyDankEngine** [comment]
> works fine for me

**Comment by DGKSK8LIFE** [comment]
ok I think I'll close now then. Ty for all the support! @YeetyDankEngine
