### ISSUE TITLE
Unable to install on Ubuntu 20.04

### ISSUE THREAD

**Issue by CStafford-14** [themoonisacheese/2bored2wait#86]
I tried installing it just now. Using the latest from the master branch.
![Terminal](https://user-images.githubusercontent.com/35039669/93596275-0bacda00-f987-11ea-90e0-89adfbbceeb6.png)

Here's the error log.
[https://pastebin.com/vFrgXbG8](https://pastebin.com/vFrgXbG8)

Do I have to install with sudo?

**Comment by MrGeorgen** [comment]
it seems you have install git, because npm tries to clone a repo via git. I don't know why this library is not npm package though.

**Comment by CStafford-14** [comment]
Git's installed as a regular package. Is it also an npm package and needs to be installed both ways?

**Comment by MrGeorgen** [comment]
git is not available as npm package. If git already installed, I no idea what caused this error. your error log link does not work correctly, can you update it?

**Comment by CStafford-14** [comment]
I work between partitions on my computer. I'm used to using git on my 18.04 partition. Turns out, I hadn't installed it in the 20.04 partition. Normally it's one of the first things I do...

After installing git and trying again, it worked with no issues. However, I can't get it to start.
`npm start` brings this up:
![Term2](https://user-images.githubusercontent.com/35039669/93643879-d62bdf00-f9ce-11ea-8c6c-d33d5f7b8035.png)
What should I do here?

**Comment by MrGeorgen** [comment]
I'm not sure, in the log I can't find information about .js files from this project.

**Comment by MrGeorgen** [comment]
I have found a similar error [here](https://github.com/HabitRPG/habitica/issues/10930) and [here](https://github.com/HabitRPG/habitica/issues/11592).
A possible fix is on this [page](https://habitica.fandom.com/wiki/Setting_up_Habitica_Locally_on_Linux), if you search for "ELIFECYCLE".
