### ISSUE TITLE
Not joining queue

### ISSUE THREAD

**Issue by 76max** [themoonisacheese/2bored2wait#9]
So I'm pretty sure I did everything correct, but when I press "Start queuing" it turns red with "Stop queuing" for a few seconds before it turns back to the "Start queuing". I tried waiting for a few minutes to see if the numbers eventually popped up, but they didn't.

**Comment by 76max** [comment]
Found temp fix, spammed Start button a few times and it works now

**Comment by themoonisacheese** [comment]
i was pretty sure you did something in particular wrong until your second message. I will investigate, but I have honestly no idea was could cause this.

**Comment by 76max** [comment]
Thank you, and loving the proxy by the way, really great job

**Comment by themoonisacheese** [comment]
I just encountered the same bug. To fix it, I launched minecraft manually. I think mojang has set up another account stealing protection that requires you to log-in in your regular client once in a while. i can't tell for sure, but that would make the most sense.

regardless, I don't think I can really fix it, so i'll be closing this. feel free to re-open it again if you think you have more info,
