### ISSUE TITLE
KeepAliveTimeout disconnect

### ISSUE THREAD

**Issue by TheMasterOfHouses** [themoonisacheese/2bored2wait#90]
Hi,
I just wanted to say that I love your script and it's very useful. But there's 1 issue.
I got into 2b2t and made my base and such, but after a while I got disconnected with the message "KeepAliveTimeout"

**Comment by themoonisacheese** [comment]
apparently not really the proxys fault.
this can happen naturally on bad internet, or if the anti-cheat kicks you.
