### ISSUE TITLE
Why is a downstream repo used in the package.json?

### ISSUE THREAD

**Issue by ZillyHuhn** [themoonisacheese/2bored2wait#92]
https://github.com/themoonisacheese/2bored2wait/blob/c73b70205cb968fca10b9c2f72007564c8f3bc9f/package.json#L12

github.com/GisliNielsen/2bored2wait seems to be a downstream fork of this repo any reason it is used there?

**Comment by themoonisacheese** [comment]
it's a product of someone 2 years ago editing package.json on their fork and being forked from there a bunch, which eventually got merged here. fixed with  f457490 .
