### ISSUE TITLE
Npm start now working.

### ISSUE THREAD

**Issue by blastmod9999** [themoonisacheese/2bored2wait#99]
After executed Npm install (with success) i tryied npm start then this happened
![image](https://user-images.githubusercontent.com/63963959/94357428-8a012e80-00a1-11eb-87a4-df9dbc7739fe.png)

**Comment by ChillerDragon** [comment]
Seems like you are using port 8080 already. Are you running a webserver? You can simply change the port in the config to a free one.

**Comment by blastmod9999** [comment]
I opened 8080 again after restart and this happen
![image](https://user-images.githubusercontent.com/63963959/94363844-bc288580-00cd-11eb-9c39-8c26356f5be6.When i tipe "localhost on browser" nothing happens.

**Comment by waterdragon78** [comment]
same on port 25565 MacOS 10.14.6

**Comment by blastmod9999** [comment]
After LOOOOONG time debbuging i found out that  it works fine without web server set to (true)
![image](https://user-images.githubusercontent.com/63963959/94365971-b9359100-00dd-11eb-8e1d-9fb591d3af17.png)
i tried 100 ports for the web server and didn t worked
this is the error for web server set to true
![image](https://user-images.githubusercontent.com/63963959/94366039-087bc180-00de-11eb-8515-12f8114a3000.png)

**Comment by MrGeorgen** [comment]
I don't know what causes this issue, but it already occurs in 015cfbacf93766f35b696d42d0ef48c6bac94bd9. However the [last version before, it got merged](https://git.redstoneunion.de/MrGeorgen/2smart2wait) does work

**Comment by MrGeorgen** [comment]
Oh seems like I failed at merging:
https://github.com/themoonisacheese/2bored2wait/blob/56ef64dd518554c4160dc4383b750125b18e147f/main.js#L41-L59
The webserver is started even if set to false and if set to true twice

**Comment by blastmod9999** [comment]
still not wk with server true(if webserver is not created i can t join o 2b2t) so i need to start it with web server

**Comment by MrGeorgen** [comment]
For me it does work. Did you with changes from the pull request?
